import crypto from 'node:crypto';
import { AtomicJsonStore } from '../platform/json-store.mjs';
const nowIso=()=>new Date().toISOString();
const scopeMatch=(item,scope)=>item.userId===scope.userId&&item.tenantId===scope.tenantId&&item.workspaceId===scope.workspaceId;
const seed=()=>({version:1,batches:[],updatedAt:null});
function parseCsv(text){const lines=String(text??'').replace(/\r/g,'').split('\n').filter(line=>line.trim());if(!lines.length)return {headers:[],rows:[]};const split=line=>line.split(',').map(value=>value.trim().replace(/^"|"$/g,''));const headers=split(lines[0]);return {headers,rows:lines.slice(1).map((line,index)=>Object.fromEntries(headers.map((header,column)=>[header,split(line)[column]??'']))).map((row,index)=>({...row,_row:index+2}))};}
function validate(kind,parsed){const required={watchlist:['canonicalId'],portfolio:['canonicalId','quantity','costBasis'],research:['type','title','note']}[kind];if(!required)throw Object.assign(new Error('Import kind is invalid'),{status:400,code:'import_kind_invalid'});const missing=required.filter(field=>!parsed.headers.includes(field));if(missing.length)throw Object.assign(new Error(`Missing required columns: ${missing.join(', ')}`),{status:400,code:'import_columns_missing',details:{missing}});const errors=[];const normalized=parsed.rows.map(row=>{const result={...row};delete result._row;if(kind==='portfolio'){result.quantity=Number(row.quantity);result.costBasis=Number(row.costBasis);if(!Number.isFinite(result.quantity)||result.quantity<=0)errors.push({row:row._row,field:'quantity',message:'Must be a positive number'});if(!Number.isFinite(result.costBasis)||result.costBasis<0)errors.push({row:row._row,field:'costBasis',message:'Must be zero or greater'});}if(kind==='watchlist'&&!String(row.canonicalId).startsWith('QI-'))errors.push({row:row._row,field:'canonicalId',message:'Must use a QI canonical identifier'});if(kind==='research'&&!['note','asset','filing','chart','event','article'].includes(row.type))errors.push({row:row._row,field:'type',message:'Unsupported research item type'});return result;});return {required,normalized,errors};}
export class ImportService{
 constructor({filePath,auditLedger}){this.store=new AtomicJsonStore(filePath,seed);this.auditLedger=auditLedger;}
 templates(){return {items:[{kind:'watchlist',columns:['canonicalId','group','note']},{kind:'portfolio',columns:['canonicalId','quantity','costBasis']},{kind:'research',columns:['type','referenceId','title','note']}],maxRows:500,acceptedFormat:'text/csv',directProductionMutation:false};}
 preview({kind,csv}){const parsed=parseCsv(csv);if(parsed.rows.length>500)throw Object.assign(new Error('Import exceeds 500-row local limit'),{status:413,code:'import_too_large'});const result=validate(kind,parsed);return {kind,headers:parsed.headers,rows:result.normalized.slice(0,50),rowCount:result.normalized.length,errorCount:result.errors.length,errors:result.errors.slice(0,100),canCommit:result.errors.length===0&&result.normalized.length>0,directProductionMutation:false,mode:'local-staging-preview'};}
 async commit(scope,input,correlationId){const preview=this.preview(input);if(!preview.canCommit)throw Object.assign(new Error('Import contains validation errors'),{status:409,code:'import_validation_failed',details:{errors:preview.errors}});let record;await this.store.update(data=>{record={importBatchId:`import-${crypto.randomUUID()}`,...scope,kind:preview.kind,rowCount:preview.rowCount,status:'staged_local',rows:preview.rows,createdAt:nowIso(),sourceName:String(input.sourceName??'inline.csv').slice(0,120),productionApplied:false};data.batches.unshift(record);data.batches=data.batches.slice(0,100);data.updatedAt=record.createdAt;return data;});await this.#audit('import.batch.staged.v1',scope,correlationId,{importBatchId:record.importBatchId,kind:record.kind,rowCount:record.rowCount});return record;}
 async list(scope){const data=await this.store.read();return {items:data.batches.filter(item=>scopeMatch(item,scope)).map(item=>({...item,rows:undefined})),directProductionMutation:false};}
 async get(scope,id){const data=await this.store.read();const item=data.batches.find(entry=>entry.importBatchId===id&&scopeMatch(entry,scope));if(!item)throw Object.assign(new Error('Import batch not found'),{status:404,code:'import_batch_not_found'});return item;}
 async #audit(eventType,scope,correlationId,details){await this.auditLedger?.append({eventType,correlationId,actor:{type:'user',id:scope.userId},tenantId:scope.tenantId,workspaceId:scope.workspaceId,details});}
}
