import crypto from 'node:crypto';
const b32='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
const enc=(buf)=>{let bits=0,v=0,o='';for(const x of buf){v=(v<<8)|x;bits+=8;while(bits>=5){o+=b32[(v>>>(bits-5))&31];bits-=5;}}if(bits)o+=b32[(v<<(5-bits))&31];return o};
const dec=(s)=>{let bits=0,v=0,a=[];for(const c of String(s).replace(/=+$/,'').toUpperCase()){const i=b32.indexOf(c);if(i<0)continue;v=(v<<5)|i;bits+=5;if(bits>=8){a.push((v>>>(bits-8))&255);bits-=8;}}return Buffer.from(a)};
const recoveryHash=(code)=>crypto.createHash('sha256').update(String(code).trim().toUpperCase()).digest('hex');
export const hotp=(secret,counter)=>{const b=Buffer.alloc(8);b.writeBigUInt64BE(BigInt(counter));const h=crypto.createHmac('sha1',dec(secret)).update(b).digest();const o=h[19]&15;return String((h.readUInt32BE(o)&0x7fffffff)%1e6).padStart(6,'0')};
export function totpCode(secret,now=Date.now()){return hotp(secret,Math.floor(now/30000));}
export class MfaService{
 constructor({repository,auditLedger,secretProtector,issuer='Qelly Intelligence'}={}){this.repository=repository;this.auditLedger=auditLedger;this.secretProtector=secretProtector;this.issuer=issuer}
 secret(factor){return factor?.secret?this.secretProtector?.unprotect(factor.secret,{purpose:`mfa:${factor.user_id}`})??factor.secret:null}
 async begin(user,correlationId){const secret=enc(crypto.randomBytes(20));const protectedSecret=this.secretProtector?.protect(secret,{purpose:`mfa:${user.userId}`})??secret;await this.repository.upsertMfaFactor({userId:user.userId,secret:protectedSecret,status:'pending'});await this.auditLedger?.append({eventType:'auth.mfa.enrollment.started.v2',correlationId,actor:{type:'user',id:user.userId},outcome:'success',details:{method:'totp',secretStorage:this.secretProtector?.mode??'legacy-local'}});return {secret,otpauth:`otpauth://totp/${encodeURIComponent(this.issuer)}:${encodeURIComponent(user.primaryEmail)}?secret=${secret}&issuer=${encodeURIComponent(this.issuer)}&digits=6&period=30`,status:'pending'};}
 verifyCode(secret,code,now=Date.now()){const c=Math.floor(now/30000);return /^\d{6}$/.test(String(code))&&[-1,0,1].some(d=>hotp(secret,c+d)===String(code));}
 generateRecoveryCodes(){return Array.from({length:10},()=>`${crypto.randomBytes(3).toString('hex').toUpperCase()}-${crypto.randomBytes(3).toString('hex').toUpperCase()}`)}
 async confirm(user,code,correlationId){const f=await this.repository.getMfaFactor(user.userId);const secret=this.secret(f);if(!f||!secret||!this.verifyCode(secret,code))throw Object.assign(new Error('Invalid authenticator code'),{status:400,code:'mfa_code_invalid'});const codes=this.generateRecoveryCodes();await this.repository.activateMfaFactor(user.userId,codes.map(recoveryHash));await this.auditLedger?.append({eventType:'auth.mfa.enabled.v2',correlationId,actor:{type:'user',id:user.userId},outcome:'success',details:{method:'totp',recoveryCodes:codes.length,secretEncrypted:Boolean(this.secretProtector)}});return {enabled:true,recoveryCodes:codes};}
 async status(userId){const f=await this.repository.getMfaFactor(userId);return {enabled:f?.status==='active',method:f?'totp':null,recoveryCodesRemaining:Number(f?.recovery_codes_remaining??0),secretProtection:this.secretProtector?.mode??'legacy-local'};}
 async disable(user,code,correlationId){const f=await this.repository.getMfaFactor(user.userId);const secret=this.secret(f);if(!f||!secret||!this.verifyCode(secret,code))throw Object.assign(new Error('Invalid authenticator code'),{status:400,code:'mfa_code_invalid'});await this.repository.disableMfaFactor(user.userId);await this.auditLedger?.append({eventType:'auth.mfa.disabled.v2',correlationId,actor:{type:'user',id:user.userId},outcome:'success',details:{method:'totp'}});return {enabled:false};}
 async consumeRecoveryCode(user,code,correlationId){const normalized=String(code??'').trim().toUpperCase();if(!/^[A-F0-9]{6}-[A-F0-9]{6}$/.test(normalized))throw Object.assign(new Error('Recovery code format is invalid'),{status:400,code:'recovery_code_invalid'});const result=await this.repository.consumeMfaRecoveryCode(user.userId,recoveryHash(normalized));if(!result?.consumed)throw Object.assign(new Error('Recovery code is invalid or has already been used'),{status:400,code:'recovery_code_invalid'});await this.auditLedger?.append({eventType:'auth.mfa.recovery-code.consumed.v1',correlationId,actor:{type:'user',id:user.userId},outcome:'success',details:{remaining:result.remaining}});return {verified:true,recoveryCodesRemaining:result.remaining,assurance:'recovery-code'};}
 async regenerateRecoveryCodes(user,code,correlationId){const f=await this.repository.getMfaFactor(user.userId);const secret=this.secret(f);if(!f||f.status!=='active'||!secret||!this.verifyCode(secret,code))throw Object.assign(new Error('A valid authenticator code is required'),{status:400,code:'mfa_code_invalid'});const codes=this.generateRecoveryCodes();await this.repository.activateMfaFactor(user.userId,codes.map(recoveryHash));await this.auditLedger?.append({eventType:'auth.mfa.recovery-codes.regenerated.v1',correlationId,actor:{type:'user',id:user.userId},outcome:'success',details:{count:codes.length}});return {recoveryCodes:codes,recoveryCodesRemaining:codes.length};}
}
