export function instrumentSeed() {
  const at = '2026-07-24T00:00:00.000Z';
  const instruments = [
    { canonicalId:'QI-CRYPTO-BTC',assetClass:'crypto',name:'Bitcoin',shortName:'Bitcoin',status:'active',primarySymbol:'BTC',currency:'USD',precision:8,jurisdiction:'GLOBAL',sector:'Digital Assets',industry:'Layer 1',venueIds:['QELLY-GLOBAL'],identifiers:[{type:'qelly',value:'QI-CRYPTO-BTC',source:'Qelly'}],contracts:[],symbols:[{symbol:'BTC',venueId:'QELLY-GLOBAL',validFrom:'2009-01-03',validTo:null}],relationships:[],issuerId:null,calendarId:'CAL-24X7',createdAt:at,updatedAt:at},
    { canonicalId:'QI-CRYPTO-ETH',assetClass:'crypto',name:'Ethereum',shortName:'Ethereum',status:'active',primarySymbol:'ETH',currency:'USD',precision:8,jurisdiction:'GLOBAL',sector:'Digital Assets',industry:'Smart Contract Platform',venueIds:['QELLY-GLOBAL'],identifiers:[{type:'qelly',value:'QI-CRYPTO-ETH',source:'Qelly'}],contracts:[],symbols:[{symbol:'ETH',venueId:'QELLY-GLOBAL',validFrom:'2015-07-30',validTo:null}],relationships:[],issuerId:null,calendarId:'CAL-24X7',createdAt:at,updatedAt:at},
    { canonicalId:'QI-EQUITY-AAPL',assetClass:'equity',name:'Apple Inc.',shortName:'Apple',status:'active',primarySymbol:'AAPL',currency:'USD',precision:4,jurisdiction:'US',sector:'Information Technology',industry:'Technology Hardware',venueIds:['XNAS'],identifiers:[{type:'ticker',value:'AAPL',source:'NASDAQ'},{type:'cik',value:'0000320193',source:'SEC'}],contracts:[],symbols:[{symbol:'AAPL',venueId:'XNAS',validFrom:'1980-12-12',validTo:null}],relationships:[{relationshipId:'REL-AAPL-ISSUER',type:'issuer',targetCanonicalId:'QI-LEGAL-APPLE',validFrom:'1980-12-12',validTo:null,source:'Qelly fixture governance'}],issuerId:'QI-LEGAL-APPLE',calendarId:'CAL-XNAS',createdAt:at,updatedAt:at},
    { canonicalId:'QI-EQUITY-NVDA',assetClass:'equity',name:'NVIDIA Corporation',shortName:'NVIDIA',status:'active',primarySymbol:'NVDA',currency:'USD',precision:4,jurisdiction:'US',sector:'Information Technology',industry:'Semiconductors',venueIds:['XNAS'],identifiers:[{type:'ticker',value:'NVDA',source:'NASDAQ'},{type:'cik',value:'0001045810',source:'SEC'}],contracts:[],symbols:[{symbol:'NVDA',venueId:'XNAS',validFrom:'1999-01-22',validTo:null}],relationships:[{relationshipId:'REL-NVDA-ISSUER',type:'issuer',targetCanonicalId:'QI-LEGAL-NVIDIA',validFrom:'1999-01-22',validTo:null,source:'Qelly fixture governance'}],issuerId:'QI-LEGAL-NVIDIA',calendarId:'CAL-XNAS',createdAt:at,updatedAt:at},
    { canonicalId:'QI-FX-USDINR',assetClass:'fx',name:'US Dollar / Indian Rupee',shortName:'USD/INR',status:'active',primarySymbol:'USDINR',currency:'INR',precision:6,jurisdiction:'GLOBAL',sector:'Foreign Exchange',industry:'Currency Pair',venueIds:['QELLY-REFERENCE'],identifiers:[{type:'iso-pair',value:'USD/INR',source:'Qelly'}],contracts:[],symbols:[{symbol:'USDINR',venueId:'QELLY-REFERENCE',validFrom:'1993-03-01',validTo:null}],relationships:[{relationshipId:'REL-USDINR-BASE',type:'pair-base',targetCanonicalId:'QI-CURRENCY-USD',validFrom:'1993-03-01',validTo:null,source:'Qelly fixture governance'},{relationshipId:'REL-USDINR-QUOTE',type:'pair-quote',targetCanonicalId:'QI-CURRENCY-INR',validFrom:'1993-03-01',validTo:null,source:'Qelly fixture governance'}],issuerId:null,calendarId:'CAL-FX-24X5',createdAt:at,updatedAt:at},
    { canonicalId:'QI-FX-EURUSD',assetClass:'fx',name:'Euro / US Dollar',shortName:'EUR/USD',status:'active',primarySymbol:'EURUSD',currency:'USD',precision:6,jurisdiction:'GLOBAL',sector:'Foreign Exchange',industry:'Currency Pair',venueIds:['QELLY-REFERENCE'],identifiers:[{type:'iso-pair',value:'EUR/USD',source:'Qelly'}],contracts:[],symbols:[{symbol:'EURUSD',venueId:'QELLY-REFERENCE',validFrom:'1999-01-01',validTo:null}],relationships:[{relationshipId:'REL-EURUSD-BASE',type:'pair-base',targetCanonicalId:'QI-CURRENCY-EUR',validFrom:'1999-01-01',validTo:null,source:'Qelly fixture governance'},{relationshipId:'REL-EURUSD-QUOTE',type:'pair-quote',targetCanonicalId:'QI-CURRENCY-USD',validFrom:'1999-01-01',validTo:null,source:'Qelly fixture governance'}],issuerId:null,calendarId:'CAL-FX-24X5',createdAt:at,updatedAt:at},
    { canonicalId:'QI-COMMODITY-GOLD',assetClass:'commodity',name:'Gold Spot',shortName:'Gold',status:'active',primarySymbol:'XAUUSD',currency:'USD',precision:4,jurisdiction:'GLOBAL',sector:'Commodities',industry:'Precious Metals',venueIds:['QELLY-REFERENCE'],identifiers:[{type:'iso-commodity',value:'XAU',source:'ISO 4217'}],contracts:[],symbols:[{symbol:'XAUUSD',venueId:'QELLY-REFERENCE',validFrom:'1971-08-15',validTo:null}],relationships:[],issuerId:null,calendarId:'CAL-COMMODITY-24X5',createdAt:at,updatedAt:at},
    { canonicalId:'QI-INDEX-SPX',assetClass:'index',name:'S&P 500 Index',shortName:'S&P 500',status:'active',primarySymbol:'SPX',currency:'USD',precision:4,jurisdiction:'US',sector:'Broad Market',industry:'Large Cap Index',venueIds:['QELLY-REFERENCE'],identifiers:[{type:'ticker',value:'SPX',source:'Qelly'}],contracts:[],symbols:[{symbol:'SPX',venueId:'QELLY-REFERENCE',validFrom:'1957-03-04',validTo:null}],relationships:[],issuerId:'QI-LEGAL-SPDJI',calendarId:'CAL-XNYS',createdAt:at,updatedAt:at},
    { canonicalId:'QI-INDEX-NDX',assetClass:'index',name:'NASDAQ-100 Index',shortName:'NASDAQ-100',status:'active',primarySymbol:'NDX',currency:'USD',precision:4,jurisdiction:'US',sector:'Broad Market',industry:'Large Cap Growth Index',venueIds:['QELLY-REFERENCE'],identifiers:[{type:'ticker',value:'NDX',source:'Qelly'}],contracts:[],symbols:[{symbol:'NDX',venueId:'QELLY-REFERENCE',validFrom:'1985-01-31',validTo:null}],relationships:[],issuerId:'QI-LEGAL-NASDAQ',calendarId:'CAL-XNAS',createdAt:at,updatedAt:at},
    { canonicalId:'QI-FUND-QQQ',assetClass:'fund',name:'Invesco QQQ Trust',shortName:'QQQ',status:'active',primarySymbol:'QQQ',currency:'USD',precision:4,jurisdiction:'US',sector:'Fund',industry:'ETF',venueIds:['XNAS'],identifiers:[{type:'ticker',value:'QQQ',source:'NASDAQ'}],contracts:[],symbols:[{symbol:'QQQ',venueId:'XNAS',validFrom:'1999-03-10',validTo:null}],relationships:[{relationshipId:'REL-QQQ-NDX',type:'tracks-index',targetCanonicalId:'QI-INDEX-NDX',validFrom:'1999-03-10',validTo:null,source:'Qelly fixture governance'}],issuerId:'QI-LEGAL-INVESCO',calendarId:'CAL-XNAS',createdAt:at,updatedAt:at},
    { canonicalId:'QI-TOKENIZED-QQQB',assetClass:'tokenized-security',name:'Invesco QQQ Trust Tokenized bStock',shortName:'QQQB',status:'active',primarySymbol:'QQQB',currency:'USD',precision:8,jurisdiction:'MULTI',sector:'Tokenized Securities',industry:'Tokenized Fund Representation',venueIds:['QELLY-TOKENIZED'],identifiers:[{type:'symbol',value:'QQQB',source:'Qelly fixture'}],contracts:[{chainId:'solana-mainnet-fixture',address:'FIXTURE-NOT-A-REAL-CONTRACT',status:'simulated',source:'Qelly fixture'}],symbols:[{symbol:'QQQB',venueId:'QELLY-TOKENIZED',validFrom:'2025-01-01',validTo:null}],relationships:[{relationshipId:'REL-QQQB-QQQ',type:'tokenized',targetCanonicalId:'QI-FUND-QQQ',validFrom:'2025-01-01',validTo:null,source:'Qelly fixture governance'}],issuerId:'QI-LEGAL-FIXTURE-TOKENIZER',calendarId:'CAL-24X7',createdAt:at,updatedAt:at},
    { canonicalId:'QI-BOND-US10Y',assetClass:'fixed-income',name:'United States 10-Year Treasury Reference',shortName:'US 10Y',status:'active',primarySymbol:'US10Y',currency:'USD',precision:6,jurisdiction:'US',sector:'Sovereign Debt',industry:'Government Bond Reference',venueIds:['QELLY-REFERENCE'],identifiers:[{type:'qelly',value:'QI-BOND-US10Y',source:'Qelly'}],contracts:[],symbols:[{symbol:'US10Y',venueId:'QELLY-REFERENCE',validFrom:'1962-01-02',validTo:null}],relationships:[{relationshipId:'REL-US10Y-ISSUER',type:'issuer',targetCanonicalId:'QI-LEGAL-US-TREASURY',validFrom:'1962-01-02',validTo:null,source:'Qelly fixture governance'}],issuerId:'QI-LEGAL-US-TREASURY',calendarId:'CAL-US-GOV',createdAt:at,updatedAt:at},
    { canonicalId:'QI-EQUITY-META-LEGACY',assetClass:'equity',name:'Meta Platforms, Inc.',shortName:'Meta',status:'active',primarySymbol:'META',currency:'USD',precision:4,jurisdiction:'US',sector:'Communication Services',industry:'Interactive Media',venueIds:['XNAS'],identifiers:[{type:'cik',value:'0001326801',source:'SEC'}],contracts:[],symbols:[{symbol:'FB',venueId:'XNAS',validFrom:'2012-05-18',validTo:'2022-06-08'},{symbol:'META',venueId:'XNAS',validFrom:'2022-06-09',validTo:null}],relationships:[{relationshipId:'REL-META-ISSUER',type:'issuer',targetCanonicalId:'QI-LEGAL-META',validFrom:'2012-05-18',validTo:null,source:'Qelly fixture governance'}],issuerId:'QI-LEGAL-META',calendarId:'CAL-XNAS',createdAt:at,updatedAt:at}
  ];
  return {
    version:1,
    systemOfRecord:'local-atomic-json-foundation',
    productionReferenceData:false,
    revision:1,
    instruments,
    venues:[
      {venueId:'XNAS',name:'NASDAQ',mic:'XNAS',jurisdiction:'US',status:'reference-fixture'},
      {venueId:'XNYS',name:'New York Stock Exchange',mic:'XNYS',jurisdiction:'US',status:'reference-fixture'},
      {venueId:'QELLY-GLOBAL',name:'Qelly Global Digital Asset Reference',mic:null,jurisdiction:'GLOBAL',status:'simulated'},
      {venueId:'QELLY-REFERENCE',name:'Qelly Reference Composite',mic:null,jurisdiction:'GLOBAL',status:'simulated'},
      {venueId:'QELLY-TOKENIZED',name:'Qelly Tokenized Security Reference',mic:null,jurisdiction:'MULTI',status:'simulated'}
    ],
    currencies:[
      {code:'USD',name:'US Dollar',precision:2,kind:'fiat'},{code:'INR',name:'Indian Rupee',precision:2,kind:'fiat'},{code:'EUR',name:'Euro',precision:2,kind:'fiat'}
    ],
    calendars:[
      {calendarId:'CAL-24X7',timezone:'UTC',sessions:[{days:'MO-SU',open:'00:00',close:'24:00'}]},
      {calendarId:'CAL-FX-24X5',timezone:'UTC',sessions:[{days:'MO-FR',open:'00:00',close:'24:00'}]},
      {calendarId:'CAL-XNAS',timezone:'America/New_York',sessions:[{days:'MO-FR',open:'09:30',close:'16:00'}]},
      {calendarId:'CAL-XNYS',timezone:'America/New_York',sessions:[{days:'MO-FR',open:'09:30',close:'16:00'}]},
      {calendarId:'CAL-COMMODITY-24X5',timezone:'UTC',sessions:[{days:'MO-FR',open:'00:00',close:'24:00'}]},
      {calendarId:'CAL-US-GOV',timezone:'America/New_York',sessions:[{days:'MO-FR',open:'08:00',close:'17:00'}]}
    ],
    corporateActions:[],
    indexMembershipHistory:[{membershipId:'IDX-QQQ-NDX',indexCanonicalId:'QI-INDEX-NDX',constituentCanonicalId:'QI-FUND-QQQ',relationship:'tracks-not-constituent',validFrom:'1999-03-10',validTo:null,source:'Qelly fixture'}],
    changeHistory:[{changeId:'CHG-SEED',revision:1,changedAt:at,actorId:'qelly-release-builder',type:'seed.created',details:{instruments:instruments.length}}]
  };
}
