const SESSION_KEY='qelly.prompt2c.supabase.session.v1';
function requireHttps(value,name){const url=new URL(value);if(url.protocol!=='https:'||url.username||url.password)throw new Error(`${name} must be a safe HTTPS URL`);return url.toString().replace(/\/$/,'');}
function validateEmail(value){const email=String(value||'').trim().toLowerCase();if(email.length>254||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new Error('invalid_email');return email;}
function safeRedirect(value,allowlist=[]){const url=new URL(value);if(!allowlist.some((allowed)=>new URL(allowed).origin===url.origin))throw new Error('redirect_not_allowlisted');return url.toString();}
function parseResponse(response,payload){if(response.ok)return payload;const error=new Error(payload?.msg||payload?.message||payload?.error_description||payload?.error||`request_failed_${response.status}`);error.status=response.status;error.code=payload?.code||payload?.error_code||'provider_request_failed';throw error;}
export class MemorySessionStore{constructor(){this.value=null;}getItem(){return this.value;}setItem(_key,value){this.value=value;}removeItem(){this.value=null;}}
export class SupabasePublicBetaAdapter{
  constructor({url,anonKey,fetchImpl=globalThis.fetch,sessionStore=globalThis.localStorage,redirectAllowlist=[]}){if(!anonKey||anonKey.length<20)throw new Error('invalid_supabase_anon_key');this.url=requireHttps(url,'Supabase URL');this.anonKey=anonKey;this.fetchImpl=fetchImpl;this.sessionStore=sessionStore;this.redirectAllowlist=redirectAllowlist;}
  session(){try{const value=JSON.parse(this.sessionStore?.getItem(SESSION_KEY)||'null');return value?.access_token&&value?.refresh_token?value:null;}catch{return null;}}
  persistSession(value){if(value?.access_token&&value?.refresh_token){const safe={access_token:value.access_token,refresh_token:value.refresh_token,expires_at:value.expires_at||Math.floor(Date.now()/1000)+(value.expires_in||3600),token_type:value.token_type||'bearer',user:value.user?{id:value.user.id,email:value.user.email,email_confirmed_at:value.user.email_confirmed_at}:null};this.sessionStore?.setItem(SESSION_KEY,JSON.stringify(safe));return safe;}this.sessionStore?.removeItem(SESSION_KEY);return null;}
  async request(path,{method='GET',body=null,accessToken=null,headers={}}={}){const response=await this.fetchImpl(`${this.url}${path}`,{method,headers:{apikey:this.anonKey,'Content-Type':'application/json',...(accessToken?{Authorization:`Bearer ${accessToken}`}:{Authorization:`Bearer ${this.anonKey}`}),...headers},body:body==null?undefined:JSON.stringify(body)});let payload=null;try{payload=await response.json();}catch{}return parseResponse(response,payload);}
  async signUp({email,password,redirectTo}){const payload=await this.request('/auth/v1/signup',{method:'POST',body:{email:validateEmail(email),password,options:{email_redirect_to:safeRedirect(redirectTo,this.redirectAllowlist)}}});if(payload.session)this.persistSession(payload.session);return {user:payload.user||null,session:payload.session?this.session():null,verificationRequired:!payload.session};}
  async signIn({email,password}){const payload=await this.request('/auth/v1/token?grant_type=password',{method:'POST',body:{email:validateEmail(email),password}});return {session:this.persistSession(payload),user:payload.user||null};}
  async refresh(){const current=this.session();if(!current)throw new Error('session_unavailable');const payload=await this.request('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:{refresh_token:current.refresh_token}});return this.persistSession(payload);}
  async signOut({scope='local'}={}){const current=this.session();if(current&&scope!=='local')await this.request('/auth/v1/logout',{method:'POST',accessToken:current.access_token,body:{scope}});this.persistSession(null);return true;}
  async requestRecovery({email,redirectTo}){await this.request('/auth/v1/recover',{method:'POST',body:{email:validateEmail(email),redirect_to:safeRedirect(redirectTo,this.redirectAllowlist)}});return {accepted:true};}
  async updatePassword({accessToken,password}){await this.request('/auth/v1/user',{method:'PUT',accessToken,body:{password}});return {updated:true};}
  token(){const session=this.session();if(!session)throw new Error('session_unavailable');if(session.expires_at<=Math.floor(Date.now()/1000))throw new Error('session_expired');return session.access_token;}
  async listSavedCalculations({workspaceId,limit=100,offset=0}){const query=new URLSearchParams({select:'id,workspace_id,owner_id,title,formula_id,input_payload,result_payload,provenance,current_revision,created_at,updated_at,deleted_at',workspace_id:`eq.${workspaceId}`,deleted_at:'is.null',order:'updated_at.desc',limit:String(Math.min(Math.max(limit,1),500)),offset:String(Math.max(offset,0))});return this.request(`/rest/v1/qelly_saved_calculations?${query}`,{accessToken:this.token()});}
  async upsertSavedCalculation(record){return this.request('/rest/v1/qelly_saved_calculations?on_conflict=id',{method:'POST',accessToken:this.token(),headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:record});}
  async queueSyncOperation(operation){return this.request('/rest/v1/qelly_sync_operations?on_conflict=owner_id,client_operation_id',{method:'POST',accessToken:this.token(),headers:{Prefer:'resolution=ignore-duplicates,return=representation'},body:operation});}
  async revisions(calculationId){const query=new URLSearchParams({select:'id,calculation_id,revision_no,snapshot,created_at',calculation_id:`eq.${calculationId}`,order:'revision_no.desc'});return this.request(`/rest/v1/qelly_saved_calculation_revisions?${query}`,{accessToken:this.token()});}
  async exportUserData(){const token=this.token();const [profile,workspaces,calculations,revisions,pending]=await Promise.all([this.request('/rest/v1/qelly_profiles?select=*&user_id=eq.'+this.session().user.id,{accessToken:token}),this.request('/rest/v1/qelly_workspaces?select=*',{accessToken:token}),this.request('/rest/v1/qelly_saved_calculations?select=*',{accessToken:token}),this.request('/rest/v1/qelly_saved_calculation_revisions?select=*',{accessToken:token}),this.request('/rest/v1/qelly_sync_operations?select=*&status=in.(pending,conflict)',{accessToken:token})]);return {schemaVersion:1,exportedAt:new Date().toISOString(),profile,workspaces,calculations,revisions,pending};}
  async requestAccountDeletion(){const ownerId=this.session()?.user?.id;if(!ownerId)throw new Error('session_unavailable');return this.request('/rest/v1/qelly_account_deletion_requests?on_conflict=owner_id',{method:'POST',accessToken:this.token(),headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:{owner_id:ownerId,status:'requested',requested_at:new Date().toISOString()}});}
}
