import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm, readFile, access } from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import { fileURLToPath } from 'node:url';
import { AuditLedger } from '../src/security/audit-ledger.mjs';
import { OnboardingStore } from '../src/onboarding/onboarding-store.mjs';
import { NotificationScheduleStore } from '../src/automation/notification-schedule-store.mjs';
import { ImportService } from '../src/imports/import-service.mjs';
import { ResearchVersionStore } from '../src/research/research-version-store.mjs';
import { WorkspaceOperationsStore } from '../src/workspace/workspace-operations-store.mjs';
import { ScreenerService } from '../src/workspace/screener-service.mjs';
import { compileFormula } from '../src/workspace/formula-engine.mjs';
import { PortfolioService } from '../src/portfolio/portfolio-service.mjs';
import { MigrationPlanService } from '../src/platform/migration-plan-service.mjs';
import { SchemaRegistry } from '../src/validation/schema-validator.mjs';
import { startServer } from '../src/server/server.mjs';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const temp=prefix=>mkdtemp(path.join(os.tmpdir(),prefix));
const scope={userId:'user-hemang-local',tenantId:'org-qelly-labs',workspaceId:'ws-institutional-research'};
async function fixture(){const dir=await temp('qelly-part21-');const auditLedger=new AuditLedger(path.join(dir,'audit.ndjson'));return {dir,auditLedger,onboarding:new OnboardingStore({filePath:path.join(dir,'onboarding.json'),auditLedger}),schedules:new NotificationScheduleStore({filePath:path.join(dir,'schedules.json'),auditLedger}),imports:new ImportService({filePath:path.join(dir,'imports.json'),auditLedger}),versions:new ResearchVersionStore({filePath:path.join(dir,'versions.json'),auditLedger}),workspace:new WorkspaceOperationsStore({filePath:path.join(dir,'workspace.json'),auditLedger})};}

test('onboarding catalog exposes bounded local options and production gates',()=>{const store=new OnboardingStore({filePath:'/tmp/not-read.json'});const catalog=store.catalog();assert.ok(catalog.goals.includes('quant-research'));assert.equal(catalog.workspaceTemplates.length,4);assert.equal(catalog.productionIdentity,false);assert.equal(catalog.externalProviderConnections,false);});

test('onboarding profile is scoped, revisioned and completable',async()=>{const x=await fixture();try{const initial=await x.onboarding.get(scope);assert.equal(initial.revision,1);const updated=await x.onboarding.update(scope,{goals:['quant-research'],assetClasses:['equity','crypto'],regions:['india','global'],baseCurrency:'USD',experienceLevel:'institutional',workspaceTemplate:'quant-lab',providerInterests:['market-data'],digestCadence:'weekly'},'c1');assert.equal(updated.revision,2);assert.equal(updated.progressPct,100);const completed=await x.onboarding.complete(scope,'c2');assert.equal(completed.completed,true);assert.equal(completed.productionProvisioning,false);const other=await x.onboarding.get({...scope,workspaceId:'ws-provider-operations'});assert.equal(other.revision,0);const events=await x.auditLedger.list(20);assert.ok(events.some(item=>item.eventType==='onboarding.completed.v1'));}finally{await rm(x.dir,{recursive:true,force:true});}});

test('onboarding completion rejects materially incomplete profiles',async()=>{const x=await fixture();try{const other={...scope,workspaceId:'ws-provider-operations'};await assert.rejects(()=>x.onboarding.complete(other,'c1'),error=>error.code==='onboarding_incomplete');}finally{await rm(x.dir,{recursive:true,force:true});}});

test('notification schedules support CRUD and deterministic due evaluation',async()=>{const x=await fixture();try{const created=await x.schedules.create(scope,{name:'Research brief',kind:'research_brief',cadence:'daily',timezone:'Asia/Kolkata',hour:8,minute:0,weekdays:[],enabled:true,nextRunAt:'2026-07-25T02:30:00.000Z'},'c1');assert.equal(created.revision,1);const updated=await x.schedules.update(scope,created.scheduleId,{enabled:false},'c2');assert.equal(updated.enabled,false);await x.schedules.update(scope,created.scheduleId,{enabled:true},'c3');const run=await x.schedules.runDue(scope,{at:'2026-08-01T12:00:00.000Z'},'c4');assert.ok(run.deliveryCount>=3);assert.equal(run.externalDeliveryAttempted,false);assert.equal(run.backgroundWorker,false);await x.schedules.remove(scope,created.scheduleId,'c5');assert.ok(!(await x.schedules.list(scope)).items.some(item=>item.scheduleId===created.scheduleId));}finally{await rm(x.dir,{recursive:true,force:true});}});

test('notification schedule validation rejects unsupported kinds and invalid times',async()=>{const x=await fixture();try{await assert.rejects(()=>x.schedules.create(scope,{name:'Bad',kind:'trade_execution',cadence:'daily',hour:25,minute:0},'c1'),error=>error.code==='schedule_kind_invalid');}finally{await rm(x.dir,{recursive:true,force:true});}});

test('formula engine evaluates bounded arithmetic without dynamic code',()=>{const formula=compileFormula('change24h / max(volatility30d, 1)',{allowedFields:['change24h','volatility30d']});assert.equal(formula.evaluate({change24h:3,volatility30d:30}),0.1);assert.throws(()=>compileFormula('process.exit(1)',{allowedFields:['price']}),error=>error.code==='formula_parse_failed');assert.throws(()=>compileFormula('constructor', {allowedFields:['price']}),error=>error.code==='formula_parse_failed');});

test('formula screener computes fields, filters and sorts deterministically',()=>{const service=new ScreenerService();const catalog=service.formulaCatalog();assert.equal(catalog.dynamicCodeExecution,false);const result=service.runFormula({formulas:[{name:'mq',expression:'change24h / max(volatility30d, 1)'}],formulaFilters:[{formula:'mq',operator:'greater_than',value:0}],sort:'mq',direction:'desc',limit:10});assert.ok(result.items.length>=3);assert.ok(result.items.every(item=>item.formulas.mq>0));assert.equal(result.dynamicCodeExecution,false);});

test('portfolio attribution reconciles holding contributions and remains non-advisory',()=>{const service=new PortfolioService();const result=service.attribution({range:'1y'});const total=Number(result.byHolding.reduce((sum,item)=>sum+item.contributionPct,0).toFixed(2));assert.equal(total,result.totalContributionPct);assert.ok(result.byAssetClass.length>=4);assert.equal(result.liveTransactions,false);assert.equal(result.brokerReconciliation,false);assert.equal(result.investmentAdvice,false);});

test('import preview validates templates and preserves production mutation boundary',()=>{const service=new ImportService({filePath:'/tmp/not-read-import.json'});const valid=service.preview({kind:'watchlist',csv:'canonicalId,group,note\nQI-CRYPTO-BTC,Core,Review'});assert.equal(valid.canCommit,true);assert.equal(valid.directProductionMutation,false);const invalid=service.preview({kind:'portfolio',csv:'canonicalId,quantity,costBasis\nQI-CRYPTO-BTC,nope,90000'});assert.equal(invalid.canCommit,false);assert.equal(invalid.errors[0].field,'quantity');assert.throws(()=>service.preview({kind:'watchlist',csv:'symbol,note\nBTC,Review'}),error=>error.code==='import_columns_missing');});

test('import commit creates scoped audited staging batches only',async()=>{const x=await fixture();try{const record=await x.imports.commit(scope,{kind:'research',sourceName:'research.csv',csv:'type,referenceId,title,note\nnote,,Policy review,Track rates'},'c1');assert.equal(record.status,'staged_local');assert.equal(record.productionApplied,false);assert.equal((await x.imports.list(scope)).items.length,1);assert.equal((await x.imports.list({...scope,workspaceId:'ws-provider-operations'})).items.length,0);assert.equal((await x.imports.get(scope,record.importBatchId)).rows.length,1);const events=await x.auditLedger.list(10);assert.ok(events.some(item=>item.eventType==='import.batch.staged.v1'));}finally{await rm(x.dir,{recursive:true,force:true});}});

test('research versions capture, compare and restore workspace snapshots',async()=>{const x=await fixture();try{const listing=await x.workspace.listResearchWorkspaces(scope);const id=listing.items[0].researchWorkspaceId;const before=await x.workspace.getResearchWorkspace(scope,id);const v1=await x.versions.capture(scope,id,before,{message:'Before note'},'c1');await x.workspace.addResearchItem(scope,id,{type:'note',title:'New evidence',note:'Versioned note'},'c2');const after=await x.workspace.getResearchWorkspace(scope,id);const v2=await x.versions.capture(scope,id,after,{message:'After note'},'c3');const diff=await x.versions.compare(scope,id,v1.versionId,v2.versionId);assert.equal(diff.added.length,1);const snapshot=await x.versions.markRestored(scope,id,v1.versionId,'c4');const restored=await x.workspace.restoreResearchWorkspace(scope,id,snapshot,'c5');assert.equal(restored.items.length,before.items.length);assert.ok(restored.revision>after.revision);}finally{await rm(x.dir,{recursive:true,force:true});}});

test('research version lookup enforces workspace scope',async()=>{const x=await fixture();try{const id=(await x.workspace.listResearchWorkspaces(scope)).items[0].researchWorkspaceId;const version=await x.versions.capture(scope,id,await x.workspace.getResearchWorkspace(scope,id),{},'c1');await assert.rejects(()=>x.versions.get({...scope,workspaceId:'ws-provider-operations'},id,version.versionId),error=>error.code==='research_version_not_found');}finally{await rm(x.dir,{recursive:true,force:true});}});

test('database migration service is plan-only with explicit operational gates',()=>{const service=new MigrationPlanService();const plan=service.plan(),status=service.status();assert.equal(plan.phases.length,4);assert.equal(plan.productionExecution,false);assert.equal(status.databaseConnected,false);assert.equal(status.migrationsExecuted,false);assert.ok(status.gates.includes('restore rehearsal'));});

test('Part 21 schemas reject unknown fields and unsafe formula shapes',async()=>{const registry=await new SchemaRegistry({schemaDir:path.join(root,'packages/schemas')}).init();assert.doesNotThrow(()=>registry.validate('onboarding-profile-input',{goals:['market-research'],baseCurrency:'INR'}));assert.throws(()=>registry.validate('onboarding-profile-input',{goals:['market-research'],admin:true}),error=>error.code==='schema_validation_failed');assert.doesNotThrow(()=>registry.validate('formula-screener-request',{formulas:[{name:'score',expression:'price / 10'}]}));assert.throws(()=>registry.validate('formula-screener-request',{formulas:[{name:'1bad',expression:'price'}]}),error=>error.code==='schema_validation_failed');});

test('Part 21 contract and SQL migration contracts are packaged',async()=>{const contract=JSON.parse(await readFile(path.join(root,'packages/contracts/onboarding-automation-attribution.contract.json'),'utf8'));assert.equal(contract.version,'21.0.0');assert.equal(contract.capabilities.formulaScreeners.dynamicCodeExecution,false);assert.equal(contract.capabilities.databaseMigration.execution,false);for(const file of ['001_foundation.sql','002_workspace_state.sql'])await access(path.join(root,'packages/migrations',file));});

test('seven Part 21 modular route files are packaged',async()=>{for(const file of ['onboarding.mjs','notification-schedules.mjs','formula-screener.mjs','portfolio-attribution.mjs','import-center.mjs','research-history.mjs','migration-center.mjs'])await access(path.join(root,'apps/web/public/assets/routes',file));});

test('Part 21 server exposes all new API domains and current route inventory',async()=>{const dir=await temp('qelly-part21-api-');const started=await startServer({port:0,runtimePath:dir});const base=`http://${started.host}:${started.port}`;try{const config=await (await fetch(base+'/api/v1/config')).json();assert.equal(config.release,'27.0.0');assert.ok(config.routes.length>=60);assert.ok(config.apiRoutes.length>=130);assert.match(config.waveStatus.part21,/implemented guided onboarding/);const endpoints=['/api/v1/onboarding/catalog','/api/v1/onboarding/profile','/api/v1/notification-schedules','/api/v1/screeners/formulas/catalog','/api/v1/portfolio/attribution','/api/v1/imports/templates','/api/v1/platform/migrations/plan','/api/v1/contracts/onboarding-automation-attribution'];for(const endpoint of endpoints)assert.equal((await fetch(base+endpoint)).status,200);}finally{await new Promise(resolve=>started.server.close(resolve));await rm(dir,{recursive:true,force:true});}});

test('Part 21 server mutations enforce CSRF, schemas, idempotency and notification replay safety',async()=>{const dir=await temp('qelly-part21-mutations-');const started=await startServer({port:0,runtimePath:dir});const base=`http://${started.host}:${started.port}`;try{const config=await (await fetch(base+'/api/v1/config')).json();const headers={'Content-Type':'application/json','X-Qelly-CSRF':config.csrf.token};let response=await fetch(base+'/api/v1/onboarding/profile',{method:'PUT',headers:{...headers,'Idempotency-Key':'part21-onboard-1'},body:JSON.stringify({goals:['quant-research'],assetClasses:['equity'],regions:['india'],baseCurrency:'INR',experienceLevel:'advanced',workspaceTemplate:'quant-lab',providerInterests:['market-data'],digestCadence:'daily'})});assert.equal(response.status,200);response=await fetch(base+'/api/v1/onboarding/profile',{method:'PUT',headers:{...headers,'Idempotency-Key':'part21-invalid-onboard'},body:JSON.stringify({goals:['quant-research'],unknown:true})});assert.equal(response.status,400);const runHeaders={...headers,'Idempotency-Key':'part21-schedule-run'};const body=JSON.stringify({at:'2026-08-01T12:00:00.000Z'});const first=await (await fetch(base+'/api/v1/notification-schedules/run-due',{method:'POST',headers:runHeaders,body})).json();const second=await (await fetch(base+'/api/v1/notification-schedules/run-due',{method:'POST',headers:runHeaders,body})).json();assert.equal(first.idempotency.replayed,false);assert.equal(second.idempotency.replayed,true);const notifications=await (await fetch(base+'/api/v1/notifications')).json();assert.equal(notifications.items.filter(item=>item.source==='qelly-local-scheduler').length,first.deliveryCount);}finally{await new Promise(resolve=>started.server.close(resolve));await rm(dir,{recursive:true,force:true});}});
