import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm, readFile, access } from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import { fileURLToPath } from 'node:url';
import { WorkspaceOperationsStore } from '../src/workspace/workspace-operations-store.mjs';
import { ScreenerService } from '../src/workspace/screener-service.mjs';
import { PortfolioService } from '../src/portfolio/portfolio-service.mjs';
import { AuditLedger } from '../src/security/audit-ledger.mjs';
import { SchemaRegistry } from '../src/validation/schema-validator.mjs';
import { startServer } from '../src/server/server.mjs';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const temp=prefix=>mkdtemp(path.join(os.tmpdir(),prefix));
const scope={userId:'user-hemang-local',tenantId:'org-qelly-labs',workspaceId:'ws-institutional-research'};

async function storeFixture(){const dir=await temp('qelly-part20-store-');const auditLedger=new AuditLedger(path.join(dir,'audit.ndjson'));const store=new WorkspaceOperationsStore({filePath:path.join(dir,'workspace.json'),auditLedger});return {dir,auditLedger,store};}

test('workspace store seeds a scoped persistent watchlist',async()=>{const {dir,store}=await storeFixture();try{const lists=await store.listWatchlists(scope);assert.equal(lists.items.length,1);assert.equal(lists.items[0].itemCount,5);const detail=await store.getWatchlist(scope,lists.items[0].watchlistId);assert.equal(detail.items[0].quote.symbol,'BTC');assert.equal(detail.cloudSync,false);}finally{await rm(dir,{recursive:true,force:true});}});

test('watchlist CRUD and item mutations are atomic and audited',async()=>{const {dir,store,auditLedger}=await storeFixture();try{const created=await store.createWatchlist(scope,{name:'Macro review',description:'Rates and hedges'},'c1');const updated=await store.updateWatchlist(scope,created.watchlistId,{name:'Macro risk review'},'c2');assert.equal(updated.revision,2);const added=await store.addWatchlistItem(scope,created.watchlistId,{canonicalId:'QI-INDEX-SPX',group:'Benchmarks',note:'Risk proxy'},'c3');assert.equal(added.quote.symbol,'SPX');await store.removeWatchlistItem(scope,created.watchlistId,'QI-INDEX-SPX','c4');await store.deleteWatchlist(scope,created.watchlistId,'c5');const events=await auditLedger.list(20);for(const type of ['workspace.watchlist.created.v1','workspace.watchlist.updated.v1','workspace.watchlist.item-added.v1','workspace.watchlist.item-removed.v1','workspace.watchlist.deleted.v1'])assert.ok(events.some(item=>item.eventType===type));}finally{await rm(dir,{recursive:true,force:true});}});

test('watchlist rejects duplicate and unknown instruments',async()=>{const {dir,store}=await storeFixture();try{const list=(await store.listWatchlists(scope)).items[0];await assert.rejects(()=>store.addWatchlistItem(scope,list.watchlistId,{canonicalId:'QI-CRYPTO-BTC'},'c1'),error=>error.code==='watchlist_item_exists');await assert.rejects(()=>store.addWatchlistItem(scope,list.watchlistId,{canonicalId:'QI-MISSING'},'c2'),error=>error.code==='canonical_id_invalid');}finally{await rm(dir,{recursive:true,force:true});}});

test('workspace state is isolated across workspace boundaries',async()=>{const {dir,store}=await storeFixture();try{const other={...scope,workspaceId:'ws-provider-operations'};assert.equal((await store.listWatchlists(other)).items.length,0);assert.equal((await store.listResearchWorkspaces(other)).items.length,0);assert.equal((await store.listAlertRules(other)).items.length,0);}finally{await rm(dir,{recursive:true,force:true});}});

test('alert evaluation creates in-app notifications and de-duplicates the same observation',async()=>{const {dir,store}=await storeFixture();try{const first=await store.evaluateAlerts(scope,'c1');assert.equal(first.triggeredCount,2);assert.equal(first.externalDeliveryAttempted,false);const second=await store.evaluateAlerts(scope,'c2');assert.equal(second.triggeredCount,0);const notifications=await store.listNotifications(scope,{status:'unread'});assert.equal(notifications.unreadCount,4);assert.ok(notifications.items.some(item=>item.ruleId==='alert-btc-momentum'));}finally{await rm(dir,{recursive:true,force:true});}});

test('notification read state and read-all are persistent',async()=>{const {dir,store}=await storeFixture();try{const before=await store.listNotifications(scope);const record=await store.markNotificationRead(scope,before.items[0].notificationId,'c1');assert.ok(record.readAt);const all=await store.markAllNotificationsRead(scope,'c2');assert.ok(all.count>=1);assert.equal((await store.listNotifications(scope,{status:'unread'})).unreadCount,0);}finally{await rm(dir,{recursive:true,force:true});}});

test('alert-rule CRUD preserves delivery truth boundaries',async()=>{const {dir,store}=await storeFixture();try{const created=await store.createAlertRule(scope,{name:'Gold review',canonicalId:'QI-COMMODITY-GOLD',metric:'price',operator:'greater_than',threshold:3000,severity:'high',cooldownMinutes:60},'c1');const updated=await store.updateAlertRule(scope,created.ruleId,{enabled:false},'c2');assert.equal(updated.enabled,false);const listing=await store.listAlertRules(scope);assert.equal(listing.delivery.email,false);await store.deleteAlertRule(scope,created.ruleId,'c3');assert.ok(!(await store.listAlertRules(scope)).items.some(item=>item.ruleId===created.ruleId));}finally{await rm(dir,{recursive:true,force:true});}});

test('screener field catalog exposes typed local predicates',()=>{const service=new ScreenerService();const catalog=service.catalog();assert.ok(catalog.fields.some(item=>item.field==='volatility30d'));assert.equal(catalog.serverSideExecution,false);assert.equal(catalog.licensedData,false);});

test('screener runs multiple filters and preserves unavailable fields',()=>{const service=new ScreenerService();const result=service.run({filters:[{field:'change24h',operator:'greater_than',value:0},{field:'volatility30d',operator:'less_than',value:50}],sort:'marketCap',direction:'desc'});assert.ok(result.items.length>=3);assert.ok(result.items.every(item=>item.change24h>0&&item.volatility30d<50));assert.ok(result.items.some(item=>item.peRatio===null));assert.equal(result.investmentAdvice,false);});

test('saved screener definitions are scoped and deletable',async()=>{const {dir,store}=await storeFixture();try{const saved=await store.saveScreener(scope,{name:'Positive momentum',definition:{filters:[{field:'change24h',operator:'greater_than',value:0}]}},'c1');assert.equal((await store.listSavedScreeners(scope)).items.length,1);await store.deleteScreener(scope,saved.savedScreenerId,'c2');assert.equal((await store.listSavedScreeners(scope)).items.length,0);}finally{await rm(dir,{recursive:true,force:true});}});

test('portfolio overview reconciles holdings cash and total value',()=>{const service=new PortfolioService();const overview=service.overview();const holdings=service.holdings();const sum=holdings.items.reduce((total,item)=>total+item.marketValue,0)+holdings.cash.value;assert.ok(Math.abs(sum-overview.totalValue)<0.02);assert.equal(overview.tradable,false);assert.equal(overview.connectedAccounts,false);});

test('portfolio performance and risk remain deterministic non-advisory analytics',()=>{const service=new PortfolioService();const performance=service.performance({range:'3m'});const risk=service.risk();assert.equal(performance.points.length,90);assert.ok(performance.metrics.totalReturnPct>0);assert.equal(performance.investmentAdvice,false);assert.ok(risk.exposures.length>=4);assert.equal(risk.liveRiskEngine,false);assert.match(risk.methodology,/not a risk model/i);});

test('research workspace CRUD and mixed evidence items are audited',async()=>{const {dir,store,auditLedger}=await storeFixture();try{const created=await store.createResearchWorkspace(scope,{name:'Macro board',description:'Evidence board',tags:['macro','rates']},'c1');const item=await store.addResearchItem(scope,created.researchWorkspaceId,{type:'note',title:'Policy review',note:'Track rate expectations.',referenceId:null},'c2');assert.equal(item.type,'note');const updated=await store.updateResearchWorkspace(scope,created.researchWorkspaceId,{description:'Updated evidence board'},'c3');assert.equal(updated.revision,3);const detail=await store.getResearchWorkspace(scope,created.researchWorkspaceId);assert.equal(detail.items.length,1);await store.deleteResearchWorkspace(scope,created.researchWorkspaceId,'c4');const events=await auditLedger.list(20);assert.ok(events.some(entry=>entry.eventType==='workspace.research.item-added.v1'));}finally{await rm(dir,{recursive:true,force:true});}});

test('Part 20 request schemas enforce bounds and unknown-field rejection',async()=>{const registry=await new SchemaRegistry({schemaDir:path.join(root,'packages/schemas')}).init();assert.doesNotThrow(()=>registry.validate('watchlist-input',{name:'Macro list',description:'Review'}));assert.throws(()=>registry.validate('watchlist-input',{name:'X',unknown:true}),error=>error.code==='schema_validation_failed');assert.doesNotThrow(()=>registry.validate('alert-rule-input',{name:'BTC price',canonicalId:'QI-CRYPTO-BTC',metric:'price',operator:'greater_than',threshold:100000}));assert.throws(()=>registry.validate('screener-request',{filters:Array.from({length:13},()=>({field:'price',operator:'greater_than',value:1}))}),error=>error.code==='schema_validation_failed');});

test('Part 20 contract declares implemented workflows and production gates',async()=>{const contract=JSON.parse(await readFile(path.join(root,'packages/contracts/workspace-portfolio-research.contract.json'),'utf8'));assert.equal(contract.version,'20.0.0');assert.equal(contract.capabilities.watchlists.crud,true);assert.equal(contract.capabilities.alerts.email,false);assert.equal(contract.capabilities.portfolio.tradable,false);assert.ok(contract.productionGates.includes('broker-connectivity'));});

test('six Part 20 modular route files are packaged',async()=>{for(const name of ['workspace-watchlist','alert-center','notification-center','screener-lab','portfolio-analytics','research-workspace']){const source=await readFile(path.join(root,`apps/web/public/assets/routes/${name}.mjs`),'utf8');assert.match(source,/export async function render/);}});

test('GitHub repository, CI, container and security files are packaged',async()=>{for(const name of ['.github/workflows/ci.yml','.github/workflows/containers.yml','.github/workflows/release.yml','.github/dependabot.yml','Dockerfile','docker-compose.yml','SECURITY.md','CONTRIBUTING.md','docs/18_GITHUB_REPOSITORY_AND_DEPLOYMENT.md'])await access(path.join(root,name));const ci=await readFile(path.join(root,'.github/workflows/ci.yml'),'utf8');assert.match(ci,/npm test/);assert.match(ci,/release:check/);const docker=await readFile(path.join(root,'Dockerfile'),'utf8');assert.match(docker,/node:22-alpine/);assert.match(docker,/QELLY_DEVELOPMENT_IDENTITY_ENABLED=false/);});

test('core CI and security workflows cover the canonical production branch',async()=>{for(const name of ['ci.yml','security.yml','containers.yml','production-foundation-services.yml']){const source=await readFile(path.join(root,'.github/workflows',name),'utf8');assert.match(source,/release\/qelly-global-public-beta/,`${name} must validate the canonical production branch`);}});

test('container publication emits valid production and immutable SHA tags',async()=>{const source=await readFile(path.join(root,'.github/workflows/containers.yml'),'utf8');assert.match(source,/github\.ref_name == 'release\/qelly-global-public-beta' && 'production'/);assert.match(source,/sha-\$\{\{ github\.sha \}\}/);assert.doesNotMatch(source,/tags: ghcr\.io\/\$\{\{ github\.repository_owner \}\}\/\$\{\{ matrix\.image \}\}:\$\{\{ github\.ref_name \}\}/);});

test('Part 20 server exposes workspace portfolio and research APIs',async()=>{const dir=await temp('qelly-part20-api-');const started=await startServer({port:0,runtimePath:dir});const base=`http://${started.host}:${started.port}`;try{const config=await (await fetch(base+'/api/v1/config')).json();assert.equal(config.release,'27.0.0');assert.ok(config.routes.length>=60);assert.ok(config.apiRoutes.length>=109);const [watchlists,rules,catalog,portfolio,research,contract]=await Promise.all(['/api/v1/workspace/watchlists','/api/v1/alerts/rules','/api/v1/screeners/catalog','/api/v1/portfolio/overview','/api/v1/research/workspaces','/api/v1/contracts/workspace-portfolio-research'].map(value=>fetch(base+value)));for(const response of [watchlists,rules,catalog,portfolio,research,contract])assert.equal(response.status,200);assert.equal((await portfolio.json()).tradable,false);}finally{await new Promise(resolve=>started.server.close(resolve));await rm(dir,{recursive:true,force:true});}});

test('Part 20 watchlist API is validated idempotent mutable and persistent',async()=>{const dir=await temp('qelly-part20-watchlist-api-');const started=await startServer({port:0,runtimePath:dir});const base=`http://${started.host}:${started.port}`;try{const config=await (await fetch(base+'/api/v1/config')).json();const baseHeaders={'Content-Type':'application/json','X-Qelly-CSRF':config.csrf.token};const invalid=await fetch(base+'/api/v1/workspace/watchlists',{method:'POST',headers:{...baseHeaders,'Idempotency-Key':'part20-invalid-watchlist'},body:JSON.stringify({name:'X',unknown:true})});assert.equal(invalid.status,400);const payload={name:'API macro list',description:'API test'};const headers={...baseHeaders,'Idempotency-Key':'part20-watchlist-create'};const first=await (await fetch(base+'/api/v1/workspace/watchlists',{method:'POST',headers,body:JSON.stringify(payload)})).json();const replay=await (await fetch(base+'/api/v1/workspace/watchlists',{method:'POST',headers,body:JSON.stringify(payload)})).json();assert.equal(first.idempotency.replayed,false);assert.equal(replay.idempotency.replayed,true);const add=await fetch(base+`/api/v1/workspace/watchlists/${first.watchlistId}/items`,{method:'POST',headers:{...baseHeaders,'Idempotency-Key':'part20-watchlist-add'},body:JSON.stringify({canonicalId:'QI-INDEX-SPX',group:'Benchmarks',note:'Index proxy'})});assert.equal(add.status,200);const detail=await (await fetch(base+`/api/v1/workspace/watchlists/${first.watchlistId}`)).json();assert.equal(detail.items[0].quote.symbol,'SPX');const remove=await fetch(base+`/api/v1/workspace/watchlists/${first.watchlistId}/items/QI-INDEX-SPX`,{method:'DELETE',headers:{...baseHeaders,'Idempotency-Key':'part20-watchlist-remove'}});assert.equal(remove.status,200);}finally{await new Promise(resolve=>started.server.close(resolve));await rm(dir,{recursive:true,force:true});}});

test('Part 20 alert and notification APIs evaluate, deliver in-app and persist read state',async()=>{const dir=await temp('qelly-part20-alert-api-');const started=await startServer({port:0,runtimePath:dir});const base=`http://${started.host}:${started.port}`;try{const config=await (await fetch(base+'/api/v1/config')).json();const headers={'Content-Type':'application/json','X-Qelly-CSRF':config.csrf.token};const created=await fetch(base+'/api/v1/alerts/rules',{method:'POST',headers:{...headers,'Idempotency-Key':'part20-alert-create'},body:JSON.stringify({name:'AAPL API review',canonicalId:'QI-EQUITY-AAPL',metric:'price',operator:'greater_than',threshold:200,severity:'high',cooldownMinutes:60})});assert.equal(created.status,200);const evaluated=await (await fetch(base+'/api/v1/alerts/evaluate',{method:'POST',headers:{...headers,'Idempotency-Key':'part20-alert-evaluate'},body:'{}'})).json();assert.ok(evaluated.triggeredCount>=3);assert.equal(evaluated.externalDeliveryAttempted,false);let notifications=await (await fetch(base+'/api/v1/notifications?status=unread')).json();assert.ok(notifications.unreadCount>=5);const target=notifications.items[0];const read=await fetch(base+`/api/v1/notifications/${target.notificationId}/read`,{method:'PUT',headers,body:'{}'});assert.equal(read.status,200);notifications=await (await fetch(base+'/api/v1/notifications?status=read')).json();assert.ok(notifications.items.some(item=>item.notificationId===target.notificationId));}finally{await new Promise(resolve=>started.server.close(resolve));await rm(dir,{recursive:true,force:true});}});

test('Part 20 screener APIs run and save reusable definitions',async()=>{const dir=await temp('qelly-part20-screener-api-');const started=await startServer({port:0,runtimePath:dir});const base=`http://${started.host}:${started.port}`;try{const config=await (await fetch(base+'/api/v1/config')).json();const headers={'Content-Type':'application/json','X-Qelly-CSRF':config.csrf.token};const definition={filters:[{field:'assetClass',operator:'equals',value:'equity'},{field:'change24h',operator:'greater_than',value:0}],sort:'marketCap',direction:'desc',limit:20};const result=await (await fetch(base+'/api/v1/screeners/run',{method:'POST',headers,body:JSON.stringify(definition)})).json();assert.equal(result.items.length,1);assert.equal(result.items[0].symbol,'NVDA');const saved=await fetch(base+'/api/v1/screeners/saved',{method:'POST',headers:{...headers,'Idempotency-Key':'part20-screener-save'},body:JSON.stringify({name:'Positive equities',definition})});assert.equal(saved.status,200);assert.equal((await (await fetch(base+'/api/v1/screeners/saved')).json()).items.length,1);}finally{await new Promise(resolve=>started.server.close(resolve));await rm(dir,{recursive:true,force:true});}});

test('Part 20 research workspace API persists mixed evidence items',async()=>{const dir=await temp('qelly-part20-research-api-');const started=await startServer({port:0,runtimePath:dir});const base=`http://${started.host}:${started.port}`;try{const config=await (await fetch(base+'/api/v1/config')).json();const headers={'Content-Type':'application/json','X-Qelly-CSRF':config.csrf.token};const created=await (await fetch(base+'/api/v1/research/workspaces',{method:'POST',headers:{...headers,'Idempotency-Key':'part20-research-create'},body:JSON.stringify({name:'API research board',description:'Evidence',tags:['api']})})).json();const item=await fetch(base+`/api/v1/research/workspaces/${created.researchWorkspaceId}/items`,{method:'POST',headers:{...headers,'Idempotency-Key':'part20-research-item'},body:JSON.stringify({type:'asset',referenceId:'QI-EQUITY-AAPL',title:'Apple',note:'Review fundamentals.'})});assert.equal(item.status,200);const detail=await (await fetch(base+`/api/v1/research/workspaces/${created.researchWorkspaceId}`)).json();assert.equal(detail.items.length,1);assert.equal(detail.items[0].type,'asset');}finally{await new Promise(resolve=>started.server.close(resolve));await rm(dir,{recursive:true,force:true});}});
