import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {buildPublicGlobalCharts} from '../functions/_lib/public-global-charts.js';
const read=(path)=>readFile(new URL(`../${path}`,import.meta.url),'utf8');
const directory=[
  {id:'european-central-bank',name:'European Central Bank',category:'fx-macro',integration:'governed-reference',url:'https://ecb.example',note:'Governed.'},
  {id:'world-bank',name:'World Bank',category:'macro',integration:'reference-public',url:'https://worldbank.example',note:'Public.'},
  {id:'us-treasury',name:'US Treasury',category:'macro',integration:'delivery-review',url:'https://treasury.example',note:'Review.'},
  {id:'fred-federal-reserve',name:'FRED',category:'macro',integration:'key-required',url:null,note:'Key.'},
  {id:'econoday',name:'Econoday',category:'macro',integration:'external-research',url:'https://econoday.example',note:'Research.'},
  {id:'unrelated',name:'Unrelated',category:'crypto',integration:'reference-public',url:null,note:'Excluded.'}
];

test('Global Charts builds a relationship protocol without invented series or statistics',()=>{const result=buildPublicGlobalCharts(directory);assert.equal(result.version,'governed-global-relationship-v1');assert.equal(result.state,'relationship-planner-available');assert.equal(result.summary.total,5);assert.equal(result.summary.byStage['governed-reference'],1);assert.equal(result.summary.byStage['public-reference'],1);assert.equal(result.summary.byStage['delivery-review'],1);assert.equal(result.summary.byStage['configuration-required'],1);assert.equal(result.summary.byStage['external-research'],1);assert.equal(result.summary.correlationsCalculated,0);assert.equal(result.summary.forecastsProduced,0);assert.equal(result.seriesFamilies.length,8);assert.equal(result.protocol.length,6);assert.equal(result.transforms.length,5);assert.equal(result.sources.every((source)=>source.capabilities.correlationCalculated===false&&source.capabilities.forecasting===false&&source.capabilities.execution===false),true);assert.equal(result.boundaries.noSyntheticSeries,true);assert.equal(result.boundaries.noCausalityClaim,true);});

test('Global Charts fails closed without governed source paths',()=>{const result=buildPublicGlobalCharts([]);assert.equal(result.state,'unavailable');assert.equal(result.sources.length,0);assert.equal(result.summary.correlationsCalculated,0);});

test('public Global Charts API, browser evidence and lazy route are wired',async()=>{const [handler,policy,app,registry,finalizer,worker,openapi,evidence]=await Promise.all([read('functions/api/v1/[[path]].js'),read('src/server/api-access-policy.mjs'),read('apps/web/public/assets/app.js'),read('apps/web/public/assets/route-registry.mjs'),read('scripts/finalize-governed-discovery.mjs'),read('apps/web/public/qelly-service-worker.js'),read('packages/openapi/qelly.openapi.json'),read('scripts/release-a5-evidence-server.mjs')]);assert.match(handler,/path==='discovery\/global-charts'&&readMethod\(method\)/);assert.match(handler,/buildPublicGlobalCharts/);assert.match(policy,/'\/api\/v1\/discovery\/global-charts'/);assert.match(app,/renderGlobalChartsWorkspace=lazyRoute\('\.\/routes\/global-charts\.mjs','renderGlobalChartsWorkspace'\)/);assert.match(app,/case 'global-charts': await renderGlobalChartsWorkspace/);assert.match(registry,/route:'global-charts'.*public:true/);assert.doesNotMatch(finalizer,/unavailable\('global-charts'\)/);assert.match(worker,/global-charts-v2\.css/);assert.match(worker,/global-charts\.mjs/);assert.match(evidence,/url\.pathname==='\/api\/v1\/discovery\/global-charts'[\s\S]*buildPublicGlobalCharts\(providerDirectory\(\)\)/);assert.deepEqual(Object.keys(JSON.parse(openapi).paths['/api/v1/discovery/global-charts'].get.responses).sort(),['200','429']);});

test('Global Charts UI has a distinct interactive relationship job and responsive states',async()=>{const [source,css]=await Promise.all([read('apps/web/public/assets/routes/global-charts.mjs'),read('apps/web/public/assets/routes/global-charts-v2.css')]);for(const phrase of ['relationship-blueprint-v1','Design the relationship before drawing the line','Build a falsifiable chart brief','Eight families, eight different questions','Co-movement stays separate from cause','No series, correlation, forecast or chart value was substituted'])assert.match(source,new RegExp(phrase));assert.match(source,/data-global-gate/);assert.match(source,/data-global-stage/);assert.match(css,/@container\(max-width:1180px\)/);assert.match(css,/@container\(max-width:620px\)/);assert.doesNotMatch(css,/visibility\s*:\s*hidden/);});
