import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {buildPublicDexDiscovery} from '../functions/_lib/public-dex.js';
const read=(path)=>readFile(new URL(`../${path}`,import.meta.url),'utf8');
const directory=[
  {id:'defillama',name:'DefiLlama',category:'public-api-candidate',integration:'terms-review',url:'https://defillama.com/docs/api',note:'Terms review.',source:'directory'},
  {id:'dexpaprika',name:'DexPaprika',category:'public-api-candidate',integration:'terms-review',url:'https://docs.dexpaprika.com',note:'Terms review.',source:'directory'},
  {id:'covalent',name:'Covalent',category:'on-chain',integration:'key-required',url:null,note:'Key required.',source:'directory'},
  {id:'chainalysis',name:'Chainalysis',category:'on-chain',integration:'paid-or-contract',url:null,note:'Contract required.',source:'directory'},
  {id:'dune-analytics',name:'Dune Analytics',category:'on-chain',integration:'external-research',url:'https://dune.com',note:'External research.',source:'directory'},
  {id:'stock-data',name:'Stock data',category:'stocks',integration:'terms-review',url:null,note:'Excluded.',source:'directory'}
];

test('DEX discovery builds an evidence-readiness directory without market claims',()=>{const result=buildPublicDexDiscovery(directory);assert.equal(result.version,'governed-dex-research-v1');assert.equal(result.state,'research-directory-available');assert.equal(result.summary.total,5);assert.equal(result.summary.byStage['rights-review'],2);assert.equal(result.summary.byStage['configuration-required'],1);assert.equal(result.summary.byStage['contract-required'],1);assert.equal(result.summary.byStage['external-research'],1);assert.equal(result.summary.displayEnabled,0);assert.equal(result.sources.every((source)=>source.capabilities.walletConnection===false&&source.capabilities.execution===false),true);assert.equal(result.workflow.length,6);assert.ok(result.evidenceFields.length>=12);assert.equal(result.boundaries.noTvlClaim,true);assert.equal(result.boundaries.noAprClaim,true);assert.equal(result.boundaries.fabricatedFallback,false);});

test('DEX discovery remains explicitly unavailable when no governed sources exist',()=>{const result=buildPublicDexDiscovery([]);assert.equal(result.state,'unavailable');assert.equal(result.sources.length,0);assert.equal(result.summary.executionEnabled,0);});

test('public DEX API and production route are wired and cached offline',async()=>{const [handler,policy,app,registry,finalizer,worker,openapi]=await Promise.all([read('functions/api/v1/[[path]].js'),read('src/server/api-access-policy.mjs'),read('apps/web/public/assets/app.js'),read('apps/web/public/assets/route-registry.mjs'),read('scripts/finalize-governed-discovery.mjs'),read('apps/web/public/qelly-service-worker.js'),read('packages/openapi/qelly.openapi.json')]);assert.match(handler,/path==='discovery\/dex'&&readMethod\(method\)/);assert.match(handler,/buildPublicDexDiscovery/);assert.match(policy,/'\/api\/v1\/discovery\/dex'/);assert.match(app,/renderDexWorkspace=lazyRoute\('\.\/routes\/dex-discovery\.mjs','renderDexDiscovery'\)/);assert.match(app,/case 'dex-discovery': await renderDexWorkspace/);assert.match(registry,/route:'dex-discovery'.*public:true/);assert.doesNotMatch(finalizer,/unavailable\('dex-discovery'\)/);assert.match(worker,/dex-discovery-v2\.css/);assert.match(worker,/dex-discovery\.mjs/);assert.deepEqual(Object.keys(JSON.parse(openapi).paths['/api/v1/discovery/dex'].get.responses).sort(),['200','429']);});

test('DEX UI has a distinct on-chain planning job and responsive fail-closed states',async()=>{const [source,css]=await Promise.all([read('apps/web/public/assets/routes/dex-discovery.mjs'),read('apps/web/public/assets/routes/dex-discovery-v2.css')]);for(const phrase of ['on-chain-evidence-planner-v1','Interrogate the pool before you trust the yield','Build a research case—not a wallet session','Provider readiness—not protocol ranking','No wallet · no transaction · no fabricated metrics','No TVL, volume, APR, liquidity or safety value was substituted'])assert.match(source,new RegExp(phrase));assert.match(source,/data-dex-evidence/);assert.match(source,/data-dex-stage/);assert.match(css,/@container \(max-width:1180px\)/);assert.match(css,/@container \(max-width:620px\)/);assert.doesNotMatch(css,/visibility\s*:\s*hidden/);});
