import test from 'node:test';
import assert from 'node:assert/strict';
import {buildPublicConverter} from '../functions/_lib/public-converter.js';
import {converterReferenceDate} from '../apps/web/public/assets/routes/converter.mjs';
const provider={truthState:'cached_provider',observationTime:'2026-10-05T16:00:00.000Z',observedAt:'2026-10-05T16:00:00.000Z',ingestionTime:'2026-10-05T15:00:00.000Z',data:{date:'2026-10-05',base:'EUR',rates:{USD:1.12,INR:107.89}}};
test('Converter carries the ECB reference date while discarding legacy derived clocks',()=>{const result=buildPublicConverter(provider);assert.equal(result.state,'reference-workbench-available');assert.equal(result.observation.observedAt,null);assert.equal(result.observation.observedDate,'2026-10-05');assert.equal(result.observation.observationTimePrecision,'date');assert.equal(result.observation.ingestedAt,provider.ingestionTime);assert.deepEqual(result.currencies.map(c=>[c.code,c.ratePerEur]),[['EUR',1],['INR',107.89],['USD',1.12]]);assert.equal(result.boundaries.execution,false);});
test('Converter never derives a reference date from an old clock or invalid calendar date',()=>{for(const value of [undefined,'2026-02-30','2026-13-05','2026-10-05T16:00:00Z']){const result=buildPublicConverter({...provider,data:{...provider.data,date:value}});assert.equal(result.observation.observedDate,null);assert.equal(result.observation.observedAt,null);assert.equal(result.observation.observationTimePrecision,'unavailable');}});
test('Unavailable Converter source exposes neither a date nor an observation clock',()=>{const result=buildPublicConverter({...provider,data:null,observationDate:'2026-10-05'});assert.equal(result.state,'unavailable');assert.equal(result.observation.observedAt,null);assert.equal(result.observation.observedDate,null);assert.deepEqual(result.currencies,[]);});
test('Converter date presentation preserves date-only values and rejects malformed or injected values',()=>{assert.equal(converterReferenceDate('2026-10-05'),'2026-10-05');assert.equal(converterReferenceDate('2024-02-29'),'2024-02-29');for(const value of [null,undefined,'2026-02-29','2026-10-05T16:00:00Z','<img src=x onerror=alert(1)>'])assert.equal(converterReferenceDate(value),'Not supplied');});
