import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import http from 'node:http';
import {mkdtemp,rm,readFile} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {SqliteProductionRepository} from '../src/production/sqlite-production-repository.mjs';
import {PostgresProductionRepository} from '../src/production/postgres-production-repository.mjs';
import {AesGcmSecretProtector} from '../src/production/secret-protector.mjs';
import {MfaService,totpCode} from '../src/production/mfa-service.mjs';
import {PasskeyService,base64url} from '../src/production/passkey-service.mjs';
import {S3CompatibleObjectStorage} from '../src/production/object-storage.mjs';
import {DeliveryService,SignedWebhookAdapter} from '../src/production/delivery-service.mjs';
import {OutboundNetworkPolicy} from '../src/production/network-policy.mjs';
import {startServer} from '../src/server/server.mjs';

const temp=()=>mkdtemp(path.join(os.tmpdir(),'qelly-a3-'));
async function principal(repo,email='a3@example.com'){const r=await repo.createRegistration({email,passwordHash:'x',displayName:'A3 User',organizationName:'A3 Org',organizationSlug:`a3-${crypto.randomUUID().slice(0,8)}`,workspaceName:'Main',workspaceSlug:'main'});return {userId:r.userId,primaryEmail:email,displayName:'A3 User',organizationId:r.organizationId,workspaceId:r.workspaceId};}
const b64=(value)=>Buffer.from(value).toString('base64url');
function cborHead(major,n){if(n<24)return Buffer.from([(major<<5)|n]);if(n<256)return Buffer.from([(major<<5)|24,n]);if(n<65536){const b=Buffer.alloc(3);b[0]=(major<<5)|25;b.writeUInt16BE(n,1);return b;}throw new Error('test encoder length too large');}
function cbor(value){if(Buffer.isBuffer(value))return Buffer.concat([cborHead(2,value.length),value]);if(typeof value==='string'){const b=Buffer.from(value);return Buffer.concat([cborHead(3,b.length),b]);}if(typeof value==='number'){return value>=0?cborHead(0,value):cborHead(1,-1-value);}if(value instanceof Map){const items=[];for(const [k,v] of value){items.push(cbor(k),cbor(v));}return Buffer.concat([cborHead(5,value.size),...items]);}throw new Error('unsupported test cbor');}
function clientData(type,challenge,origin){return b64(JSON.stringify({type,challenge,origin,crossOrigin:false}));}
function registrationCredential({challenge,origin,rpId,credentialId,publicJwk}){const x=Buffer.from(publicJwk.x,'base64url'),y=Buffer.from(publicJwk.y,'base64url');const cose=new Map([[1,2],[3,-7],[-1,1],[-2,x],[-3,y]]);const auth=Buffer.concat([crypto.createHash('sha256').update(rpId).digest(),Buffer.from([0x41]),Buffer.alloc(4),Buffer.alloc(16),Buffer.from([credentialId.length>>8,credentialId.length&255]),credentialId,cbor(cose)]);const att=cbor(new Map([['fmt','none'],['authData',auth],['attStmt',new Map()]]));return {id:b64(credentialId),rawId:b64(credentialId),type:'public-key',response:{clientDataJSON:clientData('webauthn.create',challenge,origin),attestationObject:b64(att),transports:['internal']}};}
function authenticationCredential({challenge,origin,rpId,credentialId,privateKey,count=1}){const auth=Buffer.alloc(37);crypto.createHash('sha256').update(rpId).digest().copy(auth,0);auth[32]=0x01;auth.writeUInt32BE(count,33);const cd=clientData('webauthn.get',challenge,origin);const signed=Buffer.concat([auth,crypto.createHash('sha256').update(Buffer.from(cd,'base64url')).digest()]);return {id:b64(credentialId),rawId:b64(credentialId),type:'public-key',response:{clientDataJSON:cd,authenticatorData:b64(auth),signature:b64(crypto.sign('sha256',signed,privateKey)),userHandle:null}};}

async function listen(handler){const server=http.createServer(handler);await new Promise(r=>server.listen(0,'127.0.0.1',r));return {server,url:`http://127.0.0.1:${server.address().port}`};}

test('A3 encrypts MFA secrets and consumes recovery codes exactly once',async()=>{const repo=new SqliteProductionRepository();const user=await principal(repo);const protector=new AesGcmSecretProtector({key:'test-key'.repeat(8)});const svc=new MfaService({repository:repo,secretProtector:protector});const enrollment=await svc.begin(user,'c1');const stored=await repo.getMfaFactor(user.userId);assert.match(stored.secret,/^qelly:v1:/);assert.notEqual(stored.secret,enrollment.secret);const activated=await svc.confirm(user,totpCode(enrollment.secret),'c2');const first=await svc.consumeRecoveryCode(user,activated.recoveryCodes[0],'c3');assert.equal(first.verified,true);await assert.rejects(()=>svc.consumeRecoveryCode(user,activated.recoveryCodes[0],'c4'),e=>e.code==='recovery_code_invalid');repo.close();});

test('A3 performs a full local ES256 passkey registration and authentication ceremony',async()=>{const repo=new SqliteProductionRepository();const user=await principal(repo);const service=new PasskeyService({repository:repo,rpId:'localhost',allowedOrigins:['http://localhost:4480']});const keys=crypto.generateKeyPairSync('ec',{namedCurve:'prime256v1'}),jwk=keys.publicKey.export({format:'jwk'}),credentialId=crypto.randomBytes(32);const options=await service.beginRegistration(user,{origin:'http://localhost:4480',label:'Test device'});const registered=await service.verifyRegistration(user,{challengeId:options.challengeId,credential:registrationCredential({challenge:options.publicKey.challenge,origin:'http://localhost:4480',rpId:'localhost',credentialId,publicJwk:jwk})},'reg');assert.equal(registered.label,'Test device');const auth=await service.beginAuthentication({email:user.primaryEmail,origin:'http://localhost:4480'});const verified=await service.verifyAuthentication({challengeId:auth.challengeId,credential:authenticationCredential({challenge:auth.publicKey.challenge,origin:'http://localhost:4480',rpId:'localhost',credentialId,privateKey:keys.privateKey,count:1})},'auth');assert.equal(verified.userId,user.userId);assert.equal((await repo.getPasskey(base64url(credentialId))).sign_count,1);repo.close();});

test('A3 passkey ceremonies reject mismatched origins',async()=>{const repo=new SqliteProductionRepository();const user=await principal(repo);const service=new PasskeyService({repository:repo,rpId:'localhost',allowedOrigins:['http://localhost:4480']});const keys=crypto.generateKeyPairSync('ec',{namedCurve:'prime256v1'}),jwk=keys.publicKey.export({format:'jwk'}),credentialId=crypto.randomBytes(16);const options=await service.beginRegistration(user,{origin:'http://localhost:4480'});await assert.rejects(()=>service.verifyRegistration(user,{challengeId:options.challengeId,credential:registrationCredential({challenge:options.publicKey.challenge,origin:'http://evil.test',rpId:'localhost',credentialId,publicJwk:jwk})},'bad'),e=>e.code==='passkey_origin_invalid');repo.close();});

test('A3 S3-compatible adapter emits SigV4 authorization and preserves content hash',async()=>{let received=null;const listener=await listen(async(req,res)=>{const chunks=[];for await(const c of req)chunks.push(c);received={method:req.method,url:req.url,headers:req.headers,body:Buffer.concat(chunks)};res.writeHead(200);res.end('ok');});try{const store=new S3CompatibleObjectStorage({endpoint:listener.url,bucket:'qelly-test',region:'us-east-1',accessKeyId:'AKIDEXAMPLE',secretAccessKey:'secret-example',pathStyle:true});const result=await store.put({tenantId:'org',workspaceId:'ws',fileName:'data.csv',mimeType:'text/csv',content:Buffer.from('a,b\n1,2')});assert.equal(result.provider,'s3-compatible-sigv4');assert.match(received.headers.authorization,/AWS4-HMAC-SHA256 Credential=AKIDEXAMPLE/);assert.equal(received.headers['x-amz-content-sha256'],result.sha256);assert.match(received.url,/qelly-test\/org\/ws/);}finally{await new Promise(r=>listener.server.close(r));}});

test('A3 signed webhook adapter transmits HMAC-verifiable payloads',async()=>{const secret='webhook-secret-0123456789abcdef';let observed=null;const listener=await listen(async(req,res)=>{const chunks=[];for await(const c of req)chunks.push(c);const body=Buffer.concat(chunks).toString();observed={body,signature:req.headers['x-qelly-signature'],timestamp:req.headers['x-qelly-timestamp']};res.writeHead(204);res.end();});const repo=new SqliteProductionRepository();const user=await principal(repo);try{const adapter=new SignedWebhookAdapter({signingSecret:secret,networkPolicy:new OutboundNetworkPolicy({allowHttp:true,allowPrivate:true})});const service=new DeliveryService({repository:repo,mode:'external',webhookAdapter:adapter});const result=await service.deliver({channel:'webhook',userId:user.userId,tenantId:user.organizationId,workspaceId:user.workspaceId,destination:listener.url,title:'Hello',body:'World',sourceJobId:'job-a3'});const expected=crypto.createHmac('sha256',secret).update(`${observed.timestamp}.${observed.body}`).digest('hex');assert.equal(observed.signature,`sha256=${expected}`);assert.equal(result.status,'delivered');}finally{repo.close();await new Promise(r=>listener.server.close(r));}});

test('A3 PostgreSQL repository contains A2 and A3 production parity methods',()=>{for(const name of ['upsertMfaFactor','consumeMfaRecoveryCode','createSecureImport','listSecureImports','createDeliveryAttempt','listDeliveryAttempts','createAuthChallenge','consumeAuthChallenge','createPasskey','listPasskeys','updatePasskeyCounter','revokePasskey'])assert.equal(typeof PostgresProductionRepository.prototype[name],'function');});

test('A3 migration uses repository-compatible prefixed PostgreSQL tables',async()=>{const sql=await readFile(new URL('../packages/migrations/102_release_a3_passkeys_storage_delivery.sql',import.meta.url),'utf8');for(const table of ['qelly_mfa_factors','qelly_secure_imports','qelly_delivery_attempts','qelly_passkey_credentials','qelly_auth_challenges'])assert.match(sql,new RegExp(`CREATE TABLE IF NOT EXISTS ${table}`));});

test('A3 server exposes recovery, storage and delivery operations APIs',async()=>{const dir=await temp();const started=await startServer({port:0,runtimePath:dir});const base=`http://${started.host}:${started.port}`;try{const config=await (await fetch(base+'/api/v1/config')).json();assert.equal(config.release,'27.0.0');assert.ok(config.routes.length>=60);assert.ok(config.apiRoutes.length>=175);assert.ok(config.apiRoutes.includes('/api/v1/public/markets/overview'));for(const endpoint of ['/api/v1/auth/passkeys','/api/v1/storage/status','/api/v1/delivery/providers'])assert.equal((await fetch(base+endpoint)).status,200);}finally{await new Promise(r=>started.server.close(r));started.runtime.productionRepository?.close?.();await rm(dir,{recursive:true,force:true});}});

test('A3 production mode requires explicit object-storage and delivery decisions',async()=>{const dir=await temp();await assert.rejects(()=>startServer({port:0,runtimePath:dir,environment:{...process.env,NODE_ENV:'production',QELLY_PRODUCTION_FOUNDATION_ENABLED:'true',QELLY_PRODUCTION_IDENTITY_ENABLED:'true',QELLY_DEVELOPMENT_IDENTITY_ENABLED:'false',QELLY_DATABASE_MODE:'sqlite',QELLY_ALLOW_SQLITE_IN_PRODUCTION:'true',QELLY_JOB_QUEUE_MODE:'database',QELLY_ALLOW_DATABASE_QUEUE_IN_PRODUCTION:'true',QELLY_SESSION_SECRET:'x'.repeat(40),QELLY_SECRET_PROTECTION_KEY:'y'.repeat(40)}}),e=>['s3_configuration_missing','production_object_storage_required'].includes(e.code));await rm(dir,{recursive:true,force:true});});

test('A3 frontend registers passkey, recovery and delivery route modules',async()=>{const [registry,app,login]=await Promise.all(['../apps/web/public/assets/route-registry.mjs','../apps/web/public/assets/app.js','../apps/web/public/assets/routes/auth-login.mjs'].map(x=>readFile(new URL(x,import.meta.url),'utf8')));for(const route of ['passkey-center','account-recovery','delivery-operations'])assert.match(registry,new RegExp(route));assert.match(app,/renderPasskeyCenter/);assert.match(login,/navigator\.credentials\.get/);});
