import test, { after, before } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm, readFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { startServer } from '../src/server/server.mjs';
let server,base,runtimeDir,csrf;
before(async()=>{runtimeDir=await mkdtemp(path.join(os.tmpdir(),'qelly-part18-server-'));const started=await startServer({port:0,runtimePath:runtimeDir});server=started.server;base=`http://${started.host}:${started.port}`;csrf=(await (await fetch(base+'/api/v1/config')).json()).csrf.token;});
after(async()=>{await new Promise(resolve=>server.close(resolve));await rm(runtimeDir,{recursive:true,force:true});});
const request=(pathname,options={})=>fetch(base+pathname,options);
const get=(pathname,headers={})=>request(pathname,{headers});
const mutate=(pathname,{method='POST',body={},headers={}}={})=>request(pathname,{method,headers:{'Content-Type':'application/json','X-Qelly-CSRF':csrf,...headers},body:JSON.stringify(body)});

test('health exposes release safety locks and honest boundary',async()=>{const r=await get('/api/health');assert.equal(r.status,200);const b=await r.json();assert.equal(b.release,'27.0.0');assert.equal(b.safety.liveTrading,false);assert.equal(b.safety.privateKeys,false);assert.match(b.truthBoundary,/security and persistence foundation/i);assert.match(b.truthBoundary,/public read-only market adapters/i);});
test('health includes hardened browser headers and correlation ID',async()=>{const r=await get('/api/health',{'X-Correlation-Id':'test-correlation'});assert.match(r.headers.get('content-security-policy'),/frame-ancestors 'none'/);assert.equal(r.headers.get('x-frame-options'),'DENY');assert.equal(r.headers.get('x-content-type-options'),'nosniff');assert.equal(r.headers.get('x-correlation-id'),'test-correlation');});
test('readiness separates local-ready from production-disabled dependencies',async()=>{const b=await (await get('/api/ready')).json();assert.equal(b.dependencies.productionIdentity,'disabled');assert.equal(b.dependencies.localIdentityRuntime,'ready');assert.equal(b.dependencies.localProviderRuntime,'ready');assert.match(b.dependencies.persistentInstrumentMaster,/ready-local/);});
test('config exposes thirty-six routes six themes and Wave 2/3/4/5/6/7 truth',async()=>{const b=await (await get('/api/v1/config')).json();assert.ok(b.routes.length>=60);assert.equal(b.themes.length,6);assert.match(b.waveStatus.wave2,/implemented local/);assert.match(b.waveStatus.wave3,/implemented deterministic/);assert.match(b.waveStatus.wave4,/implemented persistent/);assert.match(b.waveStatus.wave5,/implemented deterministic/);assert.equal(b.liveTrading,false);assert.equal(b.csrf.token,csrf);assert.equal(b.csrf.mode,'random-session-bound-local-token');assert.notEqual(csrf,'qelly-local-foundation-v1');});
test('missing CSRF proof blocks unsafe requests',async()=>{const r=await request('/api/v1/access/evaluate',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});assert.equal(r.status,403);assert.equal((await r.json()).error.code,'csrf_invalid');});
test('local session context exposes tenant workspace role device and truth',async()=>{const b=await (await get('/api/v1/session/context')).json();assert.equal(b.mode,'local-security-foundation');assert.equal(b.productionIdentityEnabled,false);assert.equal(b.user.displayName,'Hemang Sah');assert.equal(b.organization.organizationId,'org-qelly-labs');assert.ok(b.membership.roles.includes('organization-admin'));assert.match(b.authenticationTruth,/No production authentication/);});
test('unknown local session is rejected',async()=>{const r=await get('/api/v1/session/context',{'X-Qelly-Session-Id':'missing'});assert.equal(r.status,401);assert.equal((await r.json()).error.code,'session_not_found');});
test('workspace session device consent and privacy inventories are available',async()=>{const [w,s,d,c,p]=await Promise.all(['/api/v1/workspaces','/api/v1/sessions','/api/v1/devices','/api/v1/privacy/consents','/api/v1/privacy/data-inventory'].map(pathname=>get(pathname)));assert.equal((await w.json()).items.length,2);assert.equal((await s.json()).items.length,2);assert.equal((await d.json()).items.length,2);assert.ok((await c.json()).items.length>=2);const privacy=await p.json();assert.equal(privacy.mode,'local-fixture-only');assert.ok(privacy.excludes.includes('private keys'));});
test('tenant boundary decisions deny cross-tenant access',async()=>{const r=await mutate('/api/v1/access/evaluate',{body:{action:'instrument:read',resource:{tenantId:'org-other'}}});assert.equal(r.status,200);const b=await r.json();assert.equal(b.allowed,false);assert.ok(b.reasons.includes('tenant-boundary-mismatch'));});
test('governance action is denied before simulated step-up',async()=>{const b=await (await mutate('/api/v1/access/evaluate',{body:{action:'instrument:govern'}})).json();assert.equal(b.allowed,false);assert.ok(b.reasons.includes('step-up-required'));});
test('simulated step-up elevates local assurance with expiry and audit',async()=>{const r=await mutate('/api/v1/auth/step-up/simulate');assert.equal(r.status,200);const b=await r.json();assert.equal(b.session.assurance,'high');assert.ok(Date.parse(b.session.stepUpExpiresAt)>Date.now());});
test('governance action is allowed after simulated step-up',async()=>{const b=await (await mutate('/api/v1/access/evaluate',{body:{action:'instrument:govern'}})).json();assert.equal(b.allowed,true);});
test('workspace switch persists in local identity state',async()=>{const r=await mutate('/api/v1/workspaces/ws-provider-operations/switch');assert.equal(r.status,200);assert.equal((await r.json()).workspaceId,'ws-provider-operations');const context=await (await get('/api/v1/session/context')).json();assert.equal(context.workspace.workspaceId,'ws-provider-operations');});
test('optional consent can be updated and required consent cannot be denied',async()=>{const optional=await mutate('/api/v1/privacy/consents/privacy-safe-product-analytics',{method:'PUT',body:{status:'granted'}});assert.equal(optional.status,200);assert.equal((await optional.json()).status,'granted');const required=await mutate('/api/v1/privacy/consents/essential-local-runtime',{method:'PUT',body:{status:'denied'}});assert.equal(required.status,409);assert.equal((await required.json()).error.code,'required_consent');});
test('market overview retains deterministic source truth and null values',async()=>{const b=await (await get('/api/v1/market/overview')).json();assert.equal(b.mode,'deterministic-fixture');assert.match(b.truthBoundary,/No live provider call/);const fx=b.rows.find(row=>row.symbol==='USDINR');assert.equal(fx.marketCap,null);assert.equal(fx.volume24h,null);});
test('rankings filtering and federated universal search preserve canonical IDs',async()=>{const ranking=await (await get('/api/v1/rankings?assetClass=crypto')).json();assert.equal(ranking.total,2);const search=await (await get('/api/v1/search?q=apple')).json();assert.equal(search.items[0].entity.canonicalId,'QI-EQUITY-AAPL');assert.equal(search.mode,'federated-local-search-foundation');});
test('asset dossier and watchlist preserve Part 14 surface behavior',async()=>{const dossier=await (await get('/api/v1/assets/BTC')).json();assert.equal(dossier.instrument.canonicalId,'QI-CRYPTO-BTC');assert.equal(dossier.chart.series.length,64);const list=await (await get('/api/v1/watchlist')).json();assert.equal(list.mode,'local-fixture');assert.ok(list.items.every(item=>item.group));});
test('provider registry has three enabled fixture adapters and disabled external references',async()=>{const b=await (await get('/api/v1/providers/runtime')).json();assert.equal(b.externalCallsPerformed,false);assert.equal(b.productionCredentialsConfigured,false);assert.equal(b.credentialValuesExposed,false);assert.equal(b.items.filter(x=>x.status==='enabled').length,3);assert.ok(b.items.some(x=>x.providerId==='licensed-equities'&&x.status==='disabled'&&x.secretMaterialExposed===false));});
test('automatic provider execution returns entitlement quality and source metadata',async()=>{const r=await mutate('/api/v1/providers/execute',{body:{capability:'quote',request:{canonicalId:'QI-CRYPTO-BTC'}}});assert.equal(r.status,200);const b=await r.json();assert.equal(b.runtime.providerId,'qelly-fixture-primary');assert.equal(b.runtime.selectionRole,'primary');assert.equal(b.entitlement.allowed,true);assert.equal(b.data.entitlementClass,'development-fixture');assert.equal(b.runtime.quality.valid,true);});
test('automatic provider execution fails over from primary to secondary',async()=>{const r=await mutate('/api/v1/providers/execute',{body:{capability:'quote',request:{canonicalId:'QI-CRYPTO-BTC'},scenario:'qelly-fixture-primary:error'}});assert.equal(r.status,200);const b=await r.json();assert.equal(b.runtime.providerId,'qelly-fixture-secondary');assert.equal(b.runtime.selectionRole,'secondary');});
test('provider cache returns hit on repeated deterministic request',async()=>{const payload={capability:'quote',request:{canonicalId:'QI-CRYPTO-ETH'}};const first=await (await mutate('/api/v1/providers/execute',{body:payload})).json();const second=await (await mutate('/api/v1/providers/execute',{body:payload})).json();assert.equal(first.runtime.cache,'miss');assert.equal(second.runtime.cache,'hit');});
test('provider runtime rejects write-like capabilities and redistribution',async()=>{const write=await mutate('/api/v1/providers/execute',{body:{capability:'order',request:{}}});assert.equal(write.status,400);assert.equal((await write.json()).error.code,'capability_not_allowed');const redistribute=await mutate('/api/v1/providers/execute',{body:{capability:'quote',request:{canonicalId:'QI-CRYPTO-BTC'},use:'redistribution'}});assert.equal(redistribute.status,403);assert.equal((await redistribute.json()).error.code,'entitlement_denied');});
test('entitlement endpoint denies external redistribution explicitly',async()=>{const b=await (await mutate('/api/v1/entitlements/evaluate',{body:{providerId:'qelly-fixture-primary',capability:'quote',use:'external-export',entitlementClass:'development-fixture'}})).json();assert.equal(b.allowed,false);assert.ok(b.reasons.includes('redistribution-not-entitled'));});
test('instrument summary search detail relationships and resolution work',async()=>{const summary=await (await get('/api/v1/instruments/summary')).json();assert.ok(summary.instruments>=13);assert.equal(summary.systemOfRecord,'local-atomic-json-foundation');const search=await (await get('/api/v1/instruments/search?q=gold')).json();assert.equal(search.items[0].canonicalId,'QI-COMMODITY-GOLD');const detail=await (await get('/api/v1/instruments/QI-TOKENIZED-QQQB')).json();assert.equal(detail.contracts[0].status,'simulated');const rel=await (await get('/api/v1/instruments/QI-TOKENIZED-QQQB/relationships')).json();assert.ok(rel.outgoing.some(x=>x.type==='tokenized'));const resolved=await (await mutate('/api/v1/instruments/resolve',{body:{symbol:'QQQB'}})).json();assert.equal(resolved.resolved.canonicalId,'QI-TOKENIZED-QQQB');});
test('governed symbol mutation is idempotent and persisted atomically',async()=>{const payload={newSymbol:'META15',venueId:'XNAS',validFrom:'2026-07-24'};const headers={'Idempotency-Key':'symbol-meta-part15'};const first=await mutate('/api/v1/instruments/QI-EQUITY-META-LEGACY/symbol-history',{body:payload,headers});assert.equal(first.status,200);const one=await first.json();assert.equal(one.newSymbol,'META15');assert.equal(one.idempotency.replayed,false);const second=await mutate('/api/v1/instruments/QI-EQUITY-META-LEGACY/symbol-history',{body:payload,headers});const two=await second.json();assert.equal(two.idempotency.replayed,true);const detail=await (await get('/api/v1/instruments/QI-EQUITY-META-LEGACY')).json();assert.equal(detail.primarySymbol,'META15');const persisted=JSON.parse(await readFile(path.join(runtimeDir,'instrument-master.json'),'utf8'));assert.equal(persisted.instruments.find(x=>x.canonicalId==='QI-EQUITY-META-LEGACY').primarySymbol,'META15');});
test('idempotency key conflicts on changed payload',async()=>{const r=await mutate('/api/v1/instruments/QI-EQUITY-META-LEGACY/symbol-history',{body:{newSymbol:'META16',venueId:'XNAS',validFrom:'2026-07-25'},headers:{'Idempotency-Key':'symbol-meta-part15'}});assert.equal(r.status,409);assert.equal((await r.json()).error.code,'idempotency_conflict');});
test('preferences require CSRF and persist validated design settings',async()=>{const payload={version:1,theme:'midnight-research',density:'terminal',motion:'reduced',fontScale:110,radiusPx:12,customAccent:'#6E1833',route:'identity-access',panels:[]};const r=await mutate('/api/v1/preferences/layout',{method:'PUT',body:payload});assert.equal(r.status,200);const saved=await r.json();assert.equal(saved.theme,'midnight-research');assert.equal(saved.density,'terminal');assert.deepEqual(await (await get('/api/v1/preferences/layout')).json(),saved);});
test('preferences reject malformed custom accent',async()=>{const r=await mutate('/api/v1/preferences/layout',{method:'PUT',body:{theme:'burgundy-command',customAccent:'red'}});assert.equal(r.status,400);assert.equal((await r.json()).error.code,'request_schema_invalid');});
test('simulated SSE emits provider lineage entitlement and event quality',async()=>{const r=await get('/api/v1/stream/quotes');assert.match(r.headers.get('content-type'),/text\/event-stream/);const text=await r.text();const frame=JSON.parse(text.split('\n').find(line=>line.startsWith('data: ')).slice(6));assert.equal(frame.freshnessClass,'simulated');assert.equal(frame.payload.length,3);assert.ok(frame.payload.every(item=>item.providerId&&item.entitlementClass));assert.equal(frame.quality.valid,true);});
test('audit ledger records mutations and verifies hash-chain integrity',async()=>{const list=await (await get('/api/v1/audit?limit=100')).json();assert.ok(list.items.some(x=>x.eventType==='stepup.simulated.completed.v1'));assert.ok(list.items.some(x=>x.eventType==='symbol.changed.v1'));const verify=await (await get('/api/v1/audit/verify')).json();assert.equal(verify.valid,true);assert.ok(verify.records>=4);});
test('static application and modular packages are served',async()=>{const html=await get('/');assert.equal(html.status,200);const body=await html.text();assert.match(body,/Qelly Intelligence · Verifiable Market Intelligence/);assert.doesNotMatch(body,/Release A5/);const module=await get('/packages/data-grid/data-grid.mjs');assert.equal(module.status,200);assert.match(await module.text(),/class QellyDataGrid/);});
test('contracts expose local implementation and production gates',async()=>{const identity=await (await get('/api/v1/contracts/identity-security')).json();assert.equal(identity.localIdentityRuntimeImplemented,true);assert.equal(identity.productionIdentityImplemented,false);const provider=await (await get('/api/v1/contracts/provider-runtime')).json();assert.equal(provider.localProviderRuntimeImplemented,true);assert.equal(provider.productionProvidersEnabled,false);});
test('unknown APIs use standard errors and dangerous routes do not exist',async()=>{const unknown=await get('/api/v1/unknown');assert.equal(unknown.status,404);const body=await unknown.json();assert.equal(body.error.code,'route_not_found');assert.ok(body.correlationId);for(const pathname of ['/api/v1/orders','/api/v1/transfers','/api/v1/withdrawals','/api/v1/private-keys'])assert.equal((await get(pathname)).status,404);});

test('Wave 4 readiness exposes persistent history stream journal and local observability',async()=>{const b=await (await get('/api/ready')).json();assert.match(b.dependencies.persistentTimeSeries,/ready-local/);assert.match(b.dependencies.streamJournal,/ready-local/);assert.match(b.dependencies.observability,/ready-local/);assert.equal(b.dependencies.externalTelemetry,'disabled');});
test('time-series summary and normalized query expose decimal strings and lineage',async()=>{const summary=await (await get('/api/v1/timeseries/summary')).json();assert.equal(summary.instruments,8);assert.equal(summary.points,2880);const b=await (await get('/api/v1/timeseries/QI-CRYPTO-BTC?interval=4h&limit=12')).json();assert.equal(b.points.length,12);assert.equal(b.interval,'4h');assert.equal(typeof b.points[0].close,'string');assert.equal(b.metadata.methodologyVersion,'qelly-timeseries-normalization-1.0.0');assert.equal(b.metadata.entitlementClass,'development-fixture');});
test('time-series query supports cursor pagination and rejects bad interval',async()=>{const first=await (await get('/api/v1/timeseries/QI-EQUITY-AAPL?interval=1h&limit=5')).json();assert.ok(first.page.nextCursor);const second=await (await get(`/api/v1/timeseries/QI-EQUITY-AAPL?interval=1h&limit=5&cursor=${encodeURIComponent(first.page.nextCursor)}`)).json();assert.equal(second.points[0].sequence,6);const invalid=await get('/api/v1/timeseries/QI-EQUITY-AAPL?interval=2m');assert.equal(invalid.status,400);assert.equal((await invalid.json()).error.code,'interval_not_supported');});
test('governed time-series append requires step-up idempotency and persists',async()=>{await mutate('/api/v1/auth/step-up/simulate');const before=await (await get('/api/v1/timeseries/QI-CRYPTO-ETH?interval=1h&limit=500')).json();const latest=before.points.at(-1);const at=new Date(Date.parse(latest.at)+3600000).toISOString();const body={at,open:latest.close,high:String(Number(latest.close)*1.01),low:String(Number(latest.close)*.99),close:String(Number(latest.close)*1.002),volume:'32100'};const headers={'Idempotency-Key':'timeseries-append-part16'};const first=await mutate('/api/v1/timeseries/QI-CRYPTO-ETH/append',{body,headers});assert.equal(first.status,200);const one=await first.json();assert.equal(one.point.sequence,361);assert.equal(one.idempotency.replayed,false);const two=await (await mutate('/api/v1/timeseries/QI-CRYPTO-ETH/append',{body,headers})).json();assert.equal(two.idempotency.replayed,true);const persisted=JSON.parse(await readFile(path.join(runtimeDir,'timeseries-store.json'),'utf8'));assert.equal(persisted.series['QI-CRYPTO-ETH'].points.at(-1).sequence,361);});
test('stream catalog and replay expose bounded retention resume tokens and no production broker',async()=>{const catalog=await (await get('/api/v1/streams/catalog')).json();assert.equal(catalog.items.length,4);assert.equal(catalog.productionBrokerConfigured,false);assert.ok(catalog.items.every(item=>item.entitlementAction));const replay=await (await get('/api/v1/streams/replay?channel=quotes&afterSequence=0')).json();assert.equal(replay.channel,'quotes');assert.equal(typeof replay.gap,'boolean');assert.ok(replay.nextResumeToken);});
test('resumable SSE emits snapshot deltas heartbeats and monotonic sequences',async()=>{const r=await get('/api/v1/stream/quotes?frames=4&intervalMs=10');assert.match(r.headers.get('content-type'),/text\/event-stream/);const text=await r.text();const frames=text.split('\n').filter(line=>line.startsWith('data: ')).map(line=>JSON.parse(line.slice(6)));const sequenced=frames.filter(frame=>Number.isInteger(frame.sequence));assert.equal(sequenced.length,4);assert.deepEqual(sequenced.map(frame=>frame.sequence),[...sequenced.map(frame=>frame.sequence)].sort((a,b)=>a-b));assert.ok(sequenced.every(frame=>frame.resumeToken&&frame.quality));assert.ok(frames.some(frame=>frame.eventType==='stream.heartbeat.v1'));});
test('observability endpoints expose local metrics traces logs dependencies and candidate SLOs',async()=>{await get('/api/v1/market/overview');const [overview,metrics,traces,logs]=await Promise.all(['/api/v1/observability/overview','/api/v1/observability/metrics','/api/v1/observability/traces','/api/v1/observability/logs'].map(pathname=>get(pathname)));for(const response of [overview,metrics,traces,logs])assert.equal(response.status,200);const o=await overview.json();assert.equal(o.release,'27.0.0');assert.equal(o.externalTelemetryExport,false);assert.ok(o.dependencies.some(item=>item.id==='time-series'&&item.status==='healthy'));assert.ok(o.slos.every(item=>item.window==='candidate-only'));const m=await metrics.json();assert.ok(m.http.requests>0);assert.ok(m.providers.length>=3);assert.ok((await traces.json()).items.length>0);assert.ok((await logs.json()).items.some(item=>item.event==='runtime.started'));});
test('Wave 4 contracts are served and keep production infrastructure explicitly deferred',async()=>{const ts=await (await get('/api/v1/contracts/timeseries-streaming')).json();assert.equal(ts.status,'implemented-local-foundation');assert.equal(ts.streaming.gapDetection,true);assert.ok(ts.productionDeferred.includes('partitioned message broker'));const obs=await (await get('/api/v1/contracts/observability')).json();assert.equal(obs.privacy.externalExport,false);assert.ok(obs.productionDeferred.includes('OpenTelemetry collector'));});

test('Wave 5 discovery overview rankings and federated search expose public fixture evidence',async()=>{const overview=await (await get('/api/v1/discovery/overview')).json();assert.equal(overview.mode,'deterministic-public-discovery-foundation');assert.ok(overview.movers.length>=5);const ranking=await (await get('/api/v1/discovery/rankings?assetClass=equity&sort=marketCap&limit=2')).json();assert.equal(ranking.items.length,2);assert.ok(ranking.items.every(item=>item.assetClass==='equity'));const search=await (await get('/api/v1/search?q=gold&types=asset,category')).json();assert.ok(search.items.some(item=>item.entity.canonicalId==='QI-COMMODITY-GOLD'));assert.ok(search.facets.types.length>=1);const suggestions=await (await get('/api/v1/search/suggestions?q=apple')).json();assert.equal(suggestions.items[0].resultId,'QI-EQUITY-AAPL');});

test('Wave 5 category venue DEX chart and prediction endpoints expose deep-link data',async()=>{const [category,venue,pair,charts,predictions]=await Promise.all(['/api/v1/discovery/categories/smart-contract-platforms','/api/v1/discovery/venues/venue-binance-fixture','/api/v1/discovery/dex/dex-eth-usdc','/api/v1/discovery/global-charts','/api/v1/discovery/prediction-markets?category=Macro'].map(pathname=>get(pathname)));for(const response of [category,venue,pair,charts,predictions])assert.equal(response.status,200);assert.ok((await category.json()).constituents.length>=2);assert.equal((await venue.json()).venueId,'venue-binance-fixture');assert.equal((await pair.json()).chart.length,72);assert.equal((await charts.json()).items.length,5);assert.equal((await predictions.json()).tradable,false);});

test('Wave 5 converter is transparent and remains non-executable',async()=>{const response=await mutate('/api/v1/discovery/converter',{body:{amount:2,from:'BTC',to:'ETH',feeBps:25,slippageBps:10}});assert.equal(response.status,200);const body=await response.json();assert.equal(body.tradable,false);assert.ok(Number(body.to.netAmount)<Number(body.to.grossAmount));assert.ok(body.qualityFlags.includes('not-executable'));const invalid=await mutate('/api/v1/discovery/converter',{body:{amount:-1,from:'BTC',to:'ETH'}});assert.equal(invalid.status,400);assert.equal((await invalid.json()).error.code,'amount_invalid');});

test('Wave 5 news research methodologies coverage and status expose citations and disabled production dependencies',async()=>{const [news,research,article,methods,method,coverage,status]=await Promise.all(['/api/v1/discovery/news?topic=crypto','/api/v1/discovery/research?q=provider','/api/v1/discovery/research/research-provider-truth','/api/v1/discovery/methodologies','/api/v1/discovery/methodologies/freshness','/api/v1/discovery/coverage','/api/v1/discovery/status'].map(pathname=>get(pathname)));for(const response of [news,research,article,methods,method,coverage,status])assert.equal(response.status,200);assert.ok((await news.json()).items.length>=1);assert.equal((await research.json()).items[0].body,undefined);assert.ok((await article.json()).citations.length>=1);assert.ok((await methods.json()).items.length>=5);assert.equal((await method.json()).status,'implemented-local');assert.equal((await coverage.json()).summary.externalProvidersEnabled,0);assert.equal((await status.json()).safety.liveTrading,false);});

test('Wave 5 saved searches screens and compare tray are governed idempotent persistent and audited',async()=>{const searchHeaders={'Idempotency-Key':'wave5-saved-search'};const searchPayload={name:'Crypto discovery',query:'crypto',filters:{assetClass:'crypto'}};const first=await mutate('/api/v1/discovery/saved/searches',{body:searchPayload,headers:searchHeaders});assert.equal(first.status,200);assert.equal((await first.json()).idempotency.replayed,false);const replay=await mutate('/api/v1/discovery/saved/searches',{body:searchPayload,headers:searchHeaders});assert.equal((await replay.json()).idempotency.replayed,true);const screen=await mutate('/api/v1/discovery/saved/screens',{body:{name:'Equity leaders',definition:{assetClass:'equity',sort:'marketCap'}},headers:{'Idempotency-Key':'wave5-saved-screen'}});assert.equal(screen.status,200);const tray=await mutate('/api/v1/discovery/saved/compare-tray',{method:'PUT',body:{canonicalIds:['QI-CRYPTO-BTC','QI-CRYPTO-ETH','QI-CRYPTO-BTC']},headers:{'Idempotency-Key':'wave5-compare'}});assert.equal((await tray.json()).canonicalIds.length,2);const saved=await (await get('/api/v1/discovery/saved')).json();assert.equal(saved.savedSearches.length,1);assert.equal(saved.savedScreens.length,1);assert.equal(saved.compareTray.length,1);const persisted=JSON.parse(await readFile(path.join(runtimeDir,'saved-discovery.json'),'utf8'));assert.equal(persisted.savedSearches.length,1);const audit=await (await get('/api/v1/audit?limit=200')).json();assert.ok(audit.items.some(item=>item.eventType==='discovery.saved-search.created.v1'));});

test('Wave 5 public discovery contract is served and production providers remain deferred',async()=>{const contract=await (await get('/api/v1/contracts/public-discovery-search')).json();assert.equal(contract.status,'implemented-local-foundation');assert.equal(contract.productionGates.externalProvidersEnabled,false);assert.equal(contract.productionGates.liveTradingEnabled,false);assert.ok(contract.productionDeferred.includes('licensed exchange and market data'));});
