import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const read=(file)=>readFile(path.join(root,file),'utf8');

test('UI review remains PR-only and cannot deploy',async()=>{const workflow=await read('.github/workflows/ui-review.yml');assert.match(workflow,/pull_request:/);assert.match(workflow,/workflow_dispatch:/);assert.doesNotMatch(workflow,/
\s+push:/);assert.match(workflow,/agent\/ui-rescue-asset-rankings/);assert.match(workflow,/npm ci --ignore-scripts/);assert.match(workflow,/playwright install --with-deps chromium firefox webkit/);assert.match(workflow,/name: qelly-ui-rescue-review/);assert.doesNotMatch(workflow,/deploy-pages|pages: write|id-token: write/);});

test('premium artifact captures required modes interactions personas and browsers',async()=>{const [premium,evidence,clean,base,completion,orchestrator]=await Promise.all([read('scripts/ui-review-premium.mjs'),read('scripts/ui-review-premium-evidence.mjs'),read('scripts/ui-review-persona-clean.mjs'),read('scripts/ui-review.mjs'),read('scripts/ui-review-complete.mjs'),read('scripts/ui-review-orchestrator.mjs')]);const combined=[premium,evidence,clean,base,completion,orchestrator].join('\n');for(const viewport of ['desktop-1440','desktop-1728','tablet-1024','tablet-768','mobile-390','mobile-430'])assert.match(premium,new RegExp(viewport));for(const mode of ['discovery-mode','terminal-mode','research-mode'])assert.match(premium,new RegExp(mode));for(const artifact of ['expanded-navigation-premium.png','command-palette-premium.png','explain-drawer-premium.png','filters.png','column-manager.png','chart-tooltip.png','candlesticks.png','table-region-premium.png','light-mode-premium.png','reduced-motion-premium.png','old-vs-new-desktop.png','old-vs-new-mobile.png','MOTION_QA.md','ACCESSIBILITY_QA.md','PERFORMANCE_QA.md','CONSOLE_ERRORS.json','INTERACTIONS.json','KNOWN_DIFFERENCES.json','ARTIFACT_MANIFEST.json','VALIDATION_SUMMARY.json'])assert.match(premium,new RegExp(artifact.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));for(const slug of ['scalper-velocity','investor-compound','aggressive-alpha','quant-operator','research-oracle','signal-access']){assert.match(evidence,new RegExp(`['"]${slug}['"]`));assert.match(clean,new RegExp(`['"]${slug}['"]`));}assert.match(clean,/clean-persona-captures/);for(const browser of ['chromium','firefox','webkit'])assert.match(premium,new RegExp(browser));assert.match(combined,/old-vs-new-desktop\.png/);});

test('font comparison is rendered before final selection',async()=>{const [workflow,board]=await Promise.all([read('.github/workflows/font-comparison.yml'),read('scripts/font-comparison-board-local.mjs')]);assert.match(workflow,/npm ci --ignore-scripts/);assert.doesNotMatch(workflow,/deploy-pages|pages: write|id-token: write/);for(const candidate of ['Geist Sans Variable','Manrope Variable','Plus Jakarta Sans Variable'])assert.match(board,new RegExp(candidate));assert.match(board,/font-candidate-board-before-selection\.png/);assert.match(board,/font-final-selection-board\.png/);assert.match(board,/sequence:\['candidate-board-before-selection','final-selection-after-comparison'\]/);assert.match(board,/selected:\{ui:'Geist Sans Variable',mono:'Geist Mono Variable',license:'OFL-1\.1'\}/);});

test('font surface pass is authoritative and complete',async()=>{const [pass,stable,orchestrator]=await Promise.all([read('scripts/ui-review-font-surface.mjs'),read('scripts/ui-review-font-surface-stable.mjs'),read('scripts/ui-review-orchestrator.mjs')]);for(const viewport of ['desktop-1728','desktop-1440','desktop-1280','tablet-1024','tablet-768','mobile-430','mobile-390','mobile-360'])assert.match(pass,new RegExp(viewport));for(const artifact of ['typography-closeup.png','command-palette-font-surface.png','metric-rail.png','table-font-surface.png','mobile-asset-row.png','chart-font-surface.png','navigation-font-surface.png','filters-bottom-sheet-ready.png','columns-tonal-menu.png','explain-tonal-drawer.png','light-porcelain-font-surface.png','typography-before-after.png','command-palette-before-after.png','metric-before-after.png','chart-frame-before-after.png','CURRENT_TYPOGRAPHY_COMPUTED.json','SURFACE_REDUCTION.json','FONT_SURFACE_VALIDATION.json'])assert.match(pass,new RegExp(artifact.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.match(pass,/\[\['desktop',viewports\['desktop-1440'\]\],\['mobile',viewports\['mobile-390'\]\]\]/);assert.match(pass,/`font-surface-before-after-\$\{name\}\.png`/);for(const gate of ['localGeist','fontShiftZero','weightDiscipline','radiusDiversity','nativeSelectsGone','borderReduction','mobilePulseRail','paletteHierarchy','reducedMotion','consoleClean'])assert.match(pass,new RegExp(gate));assert.match(pass,/reduction>=\.35/);assert.match(stable,/\[data-mi-filter-close\]'\)\.last\(\)\.click/);assert.match(stable,/\[data-mi-filter-sheet\]'\)\.waitFor\(\{state:'hidden'\}\)/);assert.match(stable,/\[data-mi-column-menu\]:not\(\[hidden\]\)/);assert.doesNotMatch(stable,/waitForTimeout|setTimeout/);assert.match(orchestrator,/scripts\/ui-review-font-surface-stable\.mjs/);assert.match(orchestrator,/scripts\/font-comparison-board-local\.mjs/);assert.match(orchestrator,/authoritative\.some\(\(result\)=>result\.code!==0\)/);assert.match(orchestrator,/legacy-ui-review-nonzero-reconciled/);});

test('premium evidence preserves honest Figma boundary',async()=>{const evidence=await read('scripts/ui-review-premium-evidence.mjs');for(const phrase of ['all-six-personas','configured-query-builder','premium-shell-manual-contract','titleNotTruncated','tableInFirstScreen','previewMentions<=3','forbiddenGlyphs.length===0'])assert.match(evidence,new RegExp(phrase.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.match(evidence,/not an export from a hosted Figma file/i);assert.match(evidence,/Run `figma\/code\.js` inside Figma/);});

test('font surface CSS defines selected fonts semantic roles and modern geometry',async()=>{const [assembly,css,build,audit]=await Promise.all([read('apps/web/public/assets/qelly-premium-reset.css'),read('apps/web/public/assets/premium-font-surface.css'),read('scripts/build-frontend.mjs'),read('design/research/CURRENT_TYPOGRAPHY_AUDIT.md')]);assert.match(assembly,/premium-font-surface\.css/);for(const token of ['--q-radius-4','--q-radius-8','--q-radius-12','--q-radius-16','--q-radius-20','--q-radius-24','--q-radius-pill','--q-surface-canvas','--q-surface-floating','--q-border-subtle','--q-shadow-float'])assert.match(css,new RegExp(token));for(const rule of ['font-optical-sizing:auto','font-synthesis:none','tabular-nums lining-nums','appearance:none','scroll-snap-type:x mandatory','q-command-group','q-command-item-copy'])assert.match(css,new RegExp(rule.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.match(build,/geist-variable\.woff2/);assert.match(build,/geist-mono-variable\.woff2/);assert.match(audit,/Geist Sans Variable/);assert.match(audit,/Geist Mono Variable/);});

test('structural prototype remains review-only and is not final target',async()=>{const [referenceReadme,build]=await Promise.all([read('design/reference/README.md'),read('scripts/build-frontend.mjs')]);assert.match(referenceReadme,/structural prototype/i);assert.match(referenceReadme,/not the final visual target/i);assert.match(referenceReadme,/must not appear in `dist\/frontend`/);assert.doesNotMatch(build,/design\/reference|QELLY_EXPECTED_FULL_UI_WORKING/);});
