import { marketRows } from '../server/fixtures.mjs';
const positions=[
 {canonicalId:'QI-EQUITY-AAPL',quantity:120,costBasis:182.40},
 {canonicalId:'QI-EQUITY-NVDA',quantity:180,costBasis:121.75},
 {canonicalId:'QI-CRYPTO-BTC',quantity:0.32,costBasis:84200},
 {canonicalId:'QI-FUND-QQQ',quantity:90,costBasis:498.20},
 {canonicalId:'QI-COMMODITY-GOLD',quantity:8,costBasis:2740}
];
const cash=18500;
function quote(id){return marketRows.find(row=>row.id===id);}
function holdings(){const raw=positions.map(position=>{const row=quote(position.canonicalId);const marketValue=position.quantity*row.price;const cost=position.quantity*position.costBasis;return {...position,symbol:row.symbol,name:row.name,assetClass:row.assetClass,price:row.price,currency:row.currency,change24h:row.change24h,marketValue:Number(marketValue.toFixed(2)),costValue:Number(cost.toFixed(2)),unrealizedPnl:Number((marketValue-cost).toFixed(2)),unrealizedPnlPct:Number((((marketValue/cost)-1)*100).toFixed(2)),source:row.source,freshnessClass:row.freshnessClass};});const invested=raw.reduce((sum,item)=>sum+item.marketValue,0);const total=invested+cash;return raw.map(item=>({...item,weightPct:Number((item.marketValue/total*100).toFixed(2))}));}
export class PortfolioService {
  overview(){const items=holdings();const investedValue=items.reduce((sum,item)=>sum+item.marketValue,0);const costValue=items.reduce((sum,item)=>sum+item.costValue,0);const totalValue=investedValue+cash;const dayPnl=items.reduce((sum,item)=>sum+(item.marketValue*item.change24h/100),0);return {portfolioId:'portfolio-local-research',name:'Research Model Portfolio',baseCurrency:'USD',totalValue:Number(totalValue.toFixed(2)),investedValue:Number(investedValue.toFixed(2)),cashValue:cash,unrealizedPnl:Number((investedValue-costValue).toFixed(2)),unrealizedPnlPct:Number(((investedValue/costValue-1)*100).toFixed(2)),dayPnl:Number(dayPnl.toFixed(2)),dayPnlPct:Number((dayPnl/totalValue*100).toFixed(2)),holdingCount:items.length,asOf:'2026-07-24T08:30:00.000Z',mode:'deterministic-local-analytics',connectedAccounts:false,tradable:false,investmentAdvice:false};}
  holdings(){return {items:holdings(),cash:{currency:'USD',value:cash},connectedAccounts:false,brokerReconciliation:false};}
  performance(scopeOrOptions={},options={}){const {range='1y'}=scopeOrOptions?.range?scopeOrOptions:options;const length={ '1m':30,'3m':90,'6m':180,'1y':260 }[range]??260;const base=this.overview().totalValue*0.79;const points=Array.from({length},(_,index)=>{const trend=index/Math.max(1,length-1);const cycle=Math.sin(index/11)*0.025+Math.cos(index/27)*0.018;const value=base*(1+trend*0.265+cycle);const benchmark=base*(1+trend*0.18+Math.sin(index/16)*0.012);return {at:new Date(Date.UTC(2026,6,24-length+index)).toISOString().slice(0,10),portfolio:Number(value.toFixed(2)),benchmark:Number(benchmark.toFixed(2))};});return {range,points,metrics:{totalReturnPct:Number(((points.at(-1).portfolio/points[0].portfolio-1)*100).toFixed(2)),benchmarkReturnPct:Number(((points.at(-1).benchmark/points[0].benchmark-1)*100).toFixed(2)),annualizedVolatilityPct:21.7,maxDrawdownPct:-9.4,sharpeRatio:1.18},benchmark:'Qelly blended cross-asset fixture',livePerformance:false,investmentAdvice:false};}
  attribution(scopeOrOptions={},options={}){const {range='1y'}=scopeOrOptions?.range?scopeOrOptions:options;const items=holdings();const total=items.reduce((sum,item)=>sum+item.marketValue,0)+cash;const rangeMultiplier={'1m':0.18,'3m':0.42,'6m':0.68,'1y':1}[range]??1;const contributions=items.map((item,index)=>{const returnPct=Number(((item.unrealizedPnlPct*0.64+item.change24h*(4+index))*rangeMultiplier).toFixed(2));const contributionPct=Number((item.weightPct/100*returnPct).toFixed(2));return {canonicalId:item.canonicalId,symbol:item.symbol,name:item.name,assetClass:item.assetClass,weightPct:item.weightPct,returnPct,contributionPct,allocationEffectPct:Number((contributionPct*0.28).toFixed(2)),selectionEffectPct:Number((contributionPct*0.72).toFixed(2))};});const byAssetClass=Object.values(contributions.reduce((map,item)=>{const row=map[item.assetClass]??{assetClass:item.assetClass,weightPct:0,contributionPct:0,allocationEffectPct:0,selectionEffectPct:0};row.weightPct+=item.weightPct;row.contributionPct+=item.contributionPct;row.allocationEffectPct+=item.allocationEffectPct;row.selectionEffectPct+=item.selectionEffectPct;map[item.assetClass]=row;return map;},{})).map(item=>Object.fromEntries(Object.entries(item).map(([key,value])=>[key,typeof value==='number'?Number(value.toFixed(2)):value])));const totalContribution=Number(contributions.reduce((sum,item)=>sum+item.contributionPct,0).toFixed(2));return {portfolioId:'portfolio-local-research',range,totalValue:Number(total.toFixed(2)),totalContributionPct:totalContribution,benchmarkContributionPct:Number((totalContribution*0.72).toFixed(2)),activeContributionPct:Number((totalContribution*0.28).toFixed(2)),byHolding:contributions.sort((a,b)=>b.contributionPct-a.contributionPct),byAssetClass:byAssetClass.sort((a,b)=>b.contributionPct-a.contributionPct),methodology:'Deterministic Brinson-style local attribution approximation for interface and API validation only.',liveTransactions:false,brokerReconciliation:false,investmentAdvice:false,asOf:'2026-07-24T09:30:00.000Z'};}
  risk(){const items=holdings();const classMap={};for(const item of items)classMap[item.assetClass]=(classMap[item.assetClass]??0)+item.weightPct;const top=[...items].sort((a,b)=>b.weightPct-a.weightPct)[0];return {portfolioId:'portfolio-local-research',exposures:Object.entries(classMap).map(([assetClass,weightPct])=>({assetClass,weightPct:Number(weightPct.toFixed(2))})),concentration:{largestPosition:{canonicalId:top.canonicalId,symbol:top.symbol,weightPct:top.weightPct},topThreeWeightPct:Number([...items].sort((a,b)=>b.weightPct-a.weightPct).slice(0,3).reduce((sum,item)=>sum+item.weightPct,0).toFixed(2)),herfindahlIndex:Number(items.reduce((sum,item)=>sum+(item.weightPct/100)**2,0).toFixed(4))},riskMetrics:{annualizedVolatilityPct:21.7,valueAtRisk95OneDayPct:-2.23,expectedShortfall95Pct:-3.12,betaToBenchmark:1.08,maxDrawdownPct:-9.4},stressScenarios:[{name:'Risk-off shock',estimatedImpactPct:-12.8},{name:'Equity growth correction',estimatedImpactPct:-8.7},{name:'Crypto drawdown',estimatedImpactPct:-6.2},{name:'USD strengthening',estimatedImpactPct:-1.4}],methodology:'Deterministic local scenario analytics; not a risk model for capital decisions.',liveRiskEngine:false,investmentAdvice:false};}
}
