import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
const API_REVISION="qelly-workspace-search-2026-08-08-v2";
const headers={"content-type":"application/json; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff"};
const response=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers});
const fail=(status:number,code:string,message:string)=>response({status:"error",code,message,apiRevision:API_REVISION},status);
const cleanQuery=(v:unknown)=>String(v??"").trim().replace(/[%_(),]/g," ").replace(/\s+/g," ").slice(0,160);
Deno.serve(async(req:Request)=>{try{if(req.method!=="POST")return fail(405,"method_not_allowed","Use POST");const auth=req.headers.get("authorization");if(!auth)return fail(401,"authorization_required","Authorization header is required");const url=Deno.env.get("SUPABASE_URL"),anon=Deno.env.get("SUPABASE_ANON_KEY");if(!url||!anon)return fail(503,"runtime_configuration_missing","Supabase runtime configuration is unavailable");const client=createClient(url,anon,{global:{headers:{Authorization:auth}},auth:{persistSession:false,autoRefreshToken:false}});const {data:userData,error:userError}=await client.auth.getUser();if(userError||!userData?.user)return fail(401,"invalid_identity","Authenticated Qelly identity is required");let body:any;try{body=await req.json();}catch{return fail(400,"invalid_json","Request body must be valid JSON");}const q=cleanQuery(body?.q),workspaceId=body?.workspaceId;if(q.length<2)return fail(400,"query_too_short","Search query must contain at least two characters");if(typeof workspaceId!=="string")return fail(400,"workspace_required","workspaceId is required");const p=`%${q}%`,perSource=Math.min(20,Math.max(1,Math.trunc(Number(body?.perSource??8))));const queries=[
 client.from("qelly_research_projects").select("id,title,status,updated_at").eq("workspace_id",workspaceId).is("deleted_at",null).ilike("title",p).limit(perSource),
 client.from("qelly_research_evidence").select("id,project_id,title,evidence_role,freshness,created_at").eq("workspace_id",workspaceId).ilike("title",p).limit(perSource),
 client.from("qelly_decisions").select("id,title,status,audit_id,updated_at").eq("workspace_id",workspaceId).is("deleted_at",null).ilike("title",p).limit(perSource),
 client.from("qelly_verify_assessments").select("id,title,source_name,engine_version,methodology_version,report_hash,updated_at").eq("workspace_id",workspaceId).is("deleted_at",null).or(`title.ilike.${p},source_name.ilike.${p}`).limit(perSource),
 client.from("qelly_watchlists").select("id,name,description,updated_at").eq("workspace_id",workspaceId).is("deleted_at",null).ilike("name",p).limit(perSource),
 client.from("qelly_saved_views").select("id,name,route_id,view_type,updated_at").eq("workspace_id",workspaceId).is("deleted_at",null).ilike("name",p).limit(perSource),
 client.from("qelly_portfolios").select("id,name,base_currency,source_kind,updated_at").eq("workspace_id",workspaceId).is("deleted_at",null).ilike("name",p).limit(perSource),
 client.from("qelly_instruments").select("id,canonical_key,symbol,display_name,asset_class,venue,currency").eq("active",true).or(`symbol.ilike.${p},display_name.ilike.${p},canonical_key.ilike.${p}`).limit(perSource)
 ];const results=await Promise.all(queries);for(const result of results)if(result.error)return fail(400,"search_failed","Workspace search failed safely");const [research,evidence,decisions,verifyAssessments,watchlists,views,portfolios,instruments]=results.map(x=>x.data??[]);const groups=[
 {kind:"research",items:research.map((x:any)=>({id:x.id,label:x.title,secondary:x.status,route:"research-workspace",updatedAt:x.updated_at}))},
 {kind:"evidence",items:evidence.map((x:any)=>({id:x.id,label:x.title,secondary:`${x.evidence_role} · ${x.freshness}`,route:"research-workspace",parentId:x.project_id,updatedAt:x.created_at}))},
 {kind:"decision",items:decisions.map((x:any)=>({id:x.id,label:x.title,secondary:x.status,route:"decision-provenance",auditId:x.audit_id,updatedAt:x.updated_at}))},
 {kind:"qelly_verify",items:verifyAssessments.map((x:any)=>({id:x.id,label:x.title,secondary:`${x.source_name} · ${x.engine_version}`,route:"qelly-verify",reportHash:x.report_hash,updatedAt:x.updated_at}))},
 {kind:"watchlist",items:watchlists.map((x:any)=>({id:x.id,label:x.name,secondary:x.description??"Watchlist",route:"watchlist",updatedAt:x.updated_at}))},
 {kind:"saved_view",items:views.map((x:any)=>({id:x.id,label:x.name,secondary:`${x.view_type} · ${x.route_id}`,route:x.route_id,updatedAt:x.updated_at}))},
 {kind:"portfolio",items:portfolios.map((x:any)=>({id:x.id,label:x.name,secondary:`${x.source_kind} · ${x.base_currency}`,route:"portfolio-analytics",updatedAt:x.updated_at}))},
 {kind:"instrument",items:instruments.map((x:any)=>({id:x.id,label:x.symbol,secondary:[x.display_name,x.asset_class,x.venue,x.currency].filter(Boolean).join(" · "),route:"asset-intelligence",canonicalKey:x.canonical_key}))}
 ].filter(g=>g.items.length);return response({status:"success",query:q,workspaceId,groups,total:groups.reduce((s,g)=>s+g.items.length,0),truthBoundary:"Search returns only records visible under the authenticated user's RLS scope plus active canonical instruments. Qelly Verify search exposes saved derived evidence metadata only; no raw trade rows, market values or AI relevance scores are synthesized.",apiRevision:API_REVISION});}catch(error){return fail(500,"search_runtime_error",error instanceof Error?error.message:"Search failed safely");}});
