const functions={
  abs:values=>Math.abs(values[0]),
  min:values=>Math.min(...values),
  max:values=>Math.max(...values),
  coalesce:values=>values.find(value=>value!==null&&value!==undefined&&Number.isFinite(value))??0,
  pct:values=>values[1]===0?null:(values[0]/values[1])*100
};
function tokenize(expression){const tokens=[];let i=0;while(i<expression.length){const char=expression[i];if(/\s/.test(char)){i+=1;continue;}if(/[0-9.]/.test(char)){let value='';while(i<expression.length&&/[0-9.]/.test(expression[i]))value+=expression[i++];const number=Number(value);if(!Number.isFinite(number))throw new Error('Invalid number');tokens.push({type:'number',value:number});continue;}if(/[A-Za-z_]/.test(char)){let value='';while(i<expression.length&&/[A-Za-z0-9_]/.test(expression[i]))value+=expression[i++];tokens.push({type:'identifier',value});continue;}if('+-*/(),'.includes(char)){tokens.push({type:char,value:char});i+=1;continue;}throw new Error(`Unsupported token ${char}`);}tokens.push({type:'eof'});return tokens;}
export function compileFormula(expression,{allowedFields=[]}={}){const source=String(expression??'').trim();if(!source||source.length>240)throw Object.assign(new Error('Formula must contain 1 to 240 characters'),{status:400,code:'formula_invalid'});let tokens;try{tokens=tokenize(source);}catch(error){throw Object.assign(new Error(`Formula parse failed: ${error.message}`),{status:400,code:'formula_parse_failed'});}let cursor=0;const peek=()=>tokens[cursor];const take=type=>{const token=peek();if(token.type!==type)throw new Error(`Expected ${type}`);cursor+=1;return token;};
  const primary=()=>{const token=peek();if(token.type==='number'){cursor+=1;return ()=>token.value;}if(token.type==='identifier'){cursor+=1;const name=token.value;if(peek().type==='('){cursor+=1;const args=[];if(peek().type!==')'){while(true){args.push(expressionNode());if(peek().type!==',')break;cursor+=1;}}take(')');if(!functions[name])throw new Error(`Function ${name} is not allowed`);return row=>functions[name](args.map(fn=>fn(row)));}if(!allowedFields.includes(name))throw new Error(`Field ${name} is not allowed`);return row=>{const value=row[name];return value==null?null:Number(value);};}if(token.type==='('){cursor+=1;const node=expressionNode();take(')');return node;}if(token.type==='-'){cursor+=1;const node=primary();return row=>{const value=node(row);return value==null?null:-value;};}throw new Error('Unexpected formula token');};
  const term=()=>{let left=primary();while(['*','/'].includes(peek().type)){const op=peek().type;cursor+=1;const right=primary();const previous=left;left=row=>{const a=previous(row),b=right(row);if(a==null||b==null)return null;if(op==='/'&&b===0)return null;return op==='*'?a*b:a/b;};}return left;};
  const expressionNode=()=>{let left=term();while(['+','-'].includes(peek().type)){const op=peek().type;cursor+=1;const right=term();const previous=left;left=row=>{const a=previous(row),b=right(row);if(a==null||b==null)return null;return op==='+'?a+b:a-b;};}return left;};
  let evaluator;try{evaluator=expressionNode();take('eof');}catch(error){throw Object.assign(new Error(`Formula parse failed: ${error.message}`),{status:400,code:'formula_parse_failed'});}return {expression:source,evaluate:row=>{const value=evaluator(row);return value==null||!Number.isFinite(value)?null:Number(value.toFixed(6));}};
}
