import {HttpError,UUID,cleanText,clearSessionCookies,fetcher,jsonBody,publicRuntimeConfig,requireCsrf,responseJson,restRequest,stableUuid} from './runtime.js';

const localToCloud=(item,context)=>{if(!UUID.test(String(item.id||'')))throw new HttpError(400,'saved_id_invalid','Only UUID saved records can be synchronized');const result=item.result&&typeof item.result==='object'?item.result:{};return {id:item.id,workspace_id:context.workspace.workspaceId,owner_id:context.user.userId,title:cleanText(item.name||result.formulaId||result.indicatorId||'Calculation',160),formula_id:cleanText(result.formulaId||result.indicatorId||'calculation',160),input_payload:result.inputs&&typeof result.inputs==='object'?result.inputs:{},result_payload:result,provenance:{truthState:'DETERMINISTIC LOCAL',notes:cleanText(item.notes,2000),tags:Array.isArray(item.tags)?item.tags.slice(0,20).map(tag=>cleanText(tag,40)):[],favorite:Boolean(item.favorite),localVersion:Number(item.version)||1,formulaVersion:item.formulaVersion||null,indicatorVersion:item.indicatorVersion||null,indiaRuleVersion:item.indiaRuleVersion||null,effectiveDate:item.effectiveDate||null,localUpdatedAt:item.updatedAt||new Date().toISOString()},client_updated_at:item.updatedAt||new Date().toISOString(),deleted_at:item.deletedAt||null};};
const cloudToLocal=(record,revisions=[])=>({id:record.id,name:record.title,result:record.result_payload||{},notes:record.provenance?.notes||'',tags:record.provenance?.tags||[],favorite:Boolean(record.provenance?.favorite),savedAt:record.created_at,updatedAt:record.updated_at,schemaVersion:2,version:record.current_revision,formulaVersion:record.provenance?.formulaVersion||null,indicatorVersion:record.provenance?.indicatorVersion||null,indiaRuleVersion:record.provenance?.indiaRuleVersion||null,effectiveDate:record.provenance?.effectiveDate||null,truthState:'CLOUD RLS',baseCloudRevision:record.current_revision,revisions:revisions.map(value=>({revisionId:value.id,version:value.revision_no,createdAt:value.created_at,restoredFrom:null,name:value.snapshot?.title||record.title,result:value.snapshot?.result||{},notes:value.snapshot?.provenance?.notes||'',tags:value.snapshot?.provenance?.tags||[],favorite:Boolean(value.snapshot?.provenance?.favorite),formulaVersion:value.snapshot?.provenance?.formulaVersion||null,indicatorVersion:value.snapshot?.provenance?.indicatorVersion||null,indiaRuleVersion:value.snapshot?.provenance?.indiaRuleVersion||null,effectiveDate:value.snapshot?.provenance?.effectiveDate||null}))});
const cloudStatus=async(env,session,context)=>{const [calculations,pending]=await Promise.all([restRequest(env,session.accessToken,`qelly_saved_calculations?select=id&workspace_id=eq.${context.workspace.workspaceId}&deleted_at=is.null`),restRequest(env,session.accessToken,'qelly_sync_operations?select=id&status=in.(pending,conflict)')]);return {available:true,optIn:Boolean(context.profile?.cloud_sync_opt_in),cloudRecordCount:calculations?.length||0,pendingOperationCount:pending?.length||0,workspaceId:context.workspace.workspaceId,userId:context.user.userId};};

export async function handleData(context,path,segments,method,session,qelly){
  const {request,env}=context;
  if(path==='cloud/status'&&method==='GET')return responseJson(request,env,await cloudStatus(env,session,qelly));
  if(path==='cloud/opt-in'&&method==='POST'){await requireCsrf(request);const body=await jsonBody(request),enabled=Boolean(body.enabled);await restRequest(env,session.accessToken,`qelly_profiles?user_id=eq.${session.user.id}`,{method:'PATCH',body:{cloud_sync_opt_in:enabled},prefer:'return=representation'});return responseJson(request,env,{enabled});}
  if(path==='sync/push'&&method==='POST'){
    await requireCsrf(request);const body=await jsonBody(request),key=request.headers.get('idempotency-key');if(!key||key.length<8||key.length>128)throw new HttpError(400,'idempotency_key_required','A valid Idempotency-Key header is required');const status=await cloudStatus(env,session,qelly);if(!status.optIn)throw new HttpError(409,'cloud_opt_in_required','Cloud synchronization requires explicit opt-in');const results=[];
    for(const item of (Array.isArray(body.items)?body.items:[]).slice(0,250)){
      const record=localToCloud(item,qelly),existing=await restRequest(env,session.accessToken,`qelly_saved_calculations?select=id,current_revision,updated_at&id=eq.${record.id}&limit=1`),baseRevision=body.baseRevisions?.[record.id]??item.baseCloudRevision??null;
      if(existing?.length&&Number(baseRevision)!==Number(existing[0].current_revision)){results.push({id:record.id,status:'conflict',cloudRevision:existing[0].current_revision,cloudUpdatedAt:existing[0].updated_at});continue;}
      const operationId=await stableUuid(`${key}:${record.id}`);
      await restRequest(env,session.accessToken,'qelly_sync_operations?on_conflict=owner_id,client_operation_id',{method:'POST',body:{owner_id:session.user.id,client_operation_id:operationId,calculation_id:record.id,operation_type:existing?.length?'update':'create',base_revision:baseRevision,payload:{title:record.title,clientUpdatedAt:record.client_updated_at},status:'pending'},prefer:'resolution=ignore-duplicates,return=representation'});
      const stored=await restRequest(env,session.accessToken,'qelly_saved_calculations?on_conflict=id',{method:'POST',body:record,prefer:'resolution=merge-duplicates,return=representation'});
      await restRequest(env,session.accessToken,`qelly_sync_operations?owner_id=eq.${session.user.id}&client_operation_id=eq.${operationId}`,{method:'PATCH',body:{status:'applied',applied_at:new Date().toISOString()},prefer:'return=minimal'});
      results.push({id:record.id,status:'applied',cloudRevision:stored?.[0]?.current_revision||existing?.[0]?.current_revision||1});
    }
    return responseJson(request,env,{results,applied:results.filter(v=>v.status==='applied').length,conflicts:results.filter(v=>v.status==='conflict').length});
  }
  if(path==='sync/pull'&&method==='GET'){
    const records=await restRequest(env,session.accessToken,`qelly_saved_calculations?select=*&workspace_id=eq.${qelly.workspace.workspaceId}&order=updated_at.desc`),revisionRows=await restRequest(env,session.accessToken,'qelly_saved_calculation_revisions?select=*&order=revision_no.asc'),byCalculation=new Map();for(const row of revisionRows||[]){if(!byCalculation.has(row.calculation_id))byCalculation.set(row.calculation_id,[]);byCalculation.get(row.calculation_id).push(row);}
    return responseJson(request,env,{items:(records||[]).filter(r=>!r.deleted_at).map(r=>cloudToLocal(r,byCalculation.get(r.id)||[])),deleted:(records||[]).filter(r=>r.deleted_at).map(r=>({id:r.id,deletedAt:r.deleted_at})),pulledAt:new Date().toISOString()});
  }
  if(path==='saved-calculations'&&method==='GET')return responseJson(request,env,{items:await restRequest(env,session.accessToken,`qelly_saved_calculations?select=*&workspace_id=eq.${qelly.workspace.workspaceId}&order=updated_at.desc`)});
  if(path==='saved-calculations'&&method==='POST'){await requireCsrf(request);const body=await jsonBody(request),record=localToCloud({...body,id:body.id||crypto.randomUUID()},qelly),stored=await restRequest(env,session.accessToken,'qelly_saved_calculations',{method:'POST',body:record,prefer:'return=representation'});return responseJson(request,env,{item:stored?.[0]||null},201);}
  if(segments[0]==='saved-calculations'&&UUID.test(segments[1]||'')){
    const id=segments[1],suffix=segments.slice(2).join('/');
    if(!suffix&&method==='GET'){const rows=await restRequest(env,session.accessToken,`qelly_saved_calculations?select=*&id=eq.${id}&limit=1`);if(!rows?.length)throw new HttpError(404,'saved_not_found','Saved calculation was not found');return responseJson(request,env,{item:rows[0]});}
    if(!suffix&&method==='PATCH'){await requireCsrf(request);const body=await jsonBody(request),allowed={};for(const key of ['result_payload','input_payload','provenance','client_updated_at'])if(body[key]!==undefined)allowed[key]=body[key];if(body.title!==undefined)allowed.title=cleanText(body.title,160);const rows=await restRequest(env,session.accessToken,`qelly_saved_calculations?id=eq.${id}`,{method:'PATCH',body:allowed,prefer:'return=representation'});return responseJson(request,env,{item:rows?.[0]||null});}
    if(!suffix&&method==='DELETE'){await requireCsrf(request);await restRequest(env,session.accessToken,`qelly_saved_calculations?id=eq.${id}`,{method:'PATCH',body:{deleted_at:new Date().toISOString()},prefer:'return=minimal'});return responseJson(request,env,{deleted:true,id});}
    if(suffix==='restore'&&method==='POST'){await requireCsrf(request);const rows=await restRequest(env,session.accessToken,`qelly_saved_calculations?id=eq.${id}`,{method:'PATCH',body:{deleted_at:null},prefer:'return=representation'});return responseJson(request,env,{item:rows?.[0]||null});}
    if(suffix==='revisions'&&method==='GET')return responseJson(request,env,{items:await restRequest(env,session.accessToken,`qelly_saved_calculation_revisions?select=*&calculation_id=eq.${id}&order=revision_no.desc`)});
    if(suffix==='revisions/restore'&&method==='POST'){await requireCsrf(request);const body=await jsonBody(request),revision=Number(body.revision);if(!Number.isInteger(revision)||revision<1)throw new HttpError(400,'revision_invalid','Revision number is invalid');const rows=await restRequest(env,session.accessToken,`qelly_saved_calculation_revisions?select=*&calculation_id=eq.${id}&revision_no=eq.${revision}&limit=1`);if(!rows?.length)throw new HttpError(404,'revision_not_found','Revision was not found');const snapshot=rows[0].snapshot||{},stored=await restRequest(env,session.accessToken,`qelly_saved_calculations?id=eq.${id}`,{method:'PATCH',body:{title:snapshot.title,result_payload:snapshot.result||{},input_payload:snapshot.input||{},provenance:snapshot.provenance||{},deleted_at:snapshot.deletedAt||null},prefer:'return=representation'});return responseJson(request,env,{item:stored?.[0]||null,restoredRevision:revision});}
  }
  if(path==='account/export'&&method==='GET'){const [profile,workspaces,calculations,revisions,pending]=await Promise.all([restRequest(env,session.accessToken,`qelly_profiles?select=*&user_id=eq.${session.user.id}`),restRequest(env,session.accessToken,'qelly_workspaces?select=*'),restRequest(env,session.accessToken,'qelly_saved_calculations?select=*'),restRequest(env,session.accessToken,'qelly_saved_calculation_revisions?select=*'),restRequest(env,session.accessToken,'qelly_sync_operations?select=*&status=in.(pending,conflict)')]);return responseJson(request,env,{schemaVersion:1,exportedAt:new Date().toISOString(),profile,workspaces,calculations,revisions,pending});}
  if(path==='account/delete'&&method==='POST'){await requireCsrf(request);await restRequest(env,session.accessToken,'qelly_account_deletion_requests?on_conflict=owner_id',{method:'POST',body:{owner_id:session.user.id,status:'requested',requested_at:new Date().toISOString()},prefer:'resolution=merge-duplicates,return=representation'});let identityDeleted=false;if(env.QELLY_SUPABASE_SERVICE_ROLE_KEY){const config=publicRuntimeConfig(env,request.url),response=await fetcher(env)(`${config.supabaseUrl}/auth/v1/admin/users/${session.user.id}`,{method:'DELETE',headers:{apikey:env.QELLY_SUPABASE_SERVICE_ROLE_KEY,Authorization:`Bearer ${env.QELLY_SUPABASE_SERVICE_ROLE_KEY}`}});identityDeleted=response.ok;}return responseJson(request,env,{requested:true,identityDeleted,status:identityDeleted?'completed':'requested'},202,{cookies:clearSessionCookies()});}
  return null;
}
export const __dataTest=Object.freeze({localToCloud,cloudToLocal,cloudStatus});
