import {HttpError,fetcher} from './runtime.js';
const SAFE_SYMBOL=/^[A-Z0-9-]{3,30}$/;
const GRANULARITY=new Map([['1m',60],['5m',300],['15m',900],['1h',3600],['4h',21600],['1d',86400]]);
const number=(value,name)=>{const n=Number(value);if(!Number.isFinite(n))throw new HttpError(503,'provider_schema_invalid',`Provider returned invalid ${name}`);return n;};
const fetchJson=async(env,url,{headers={},timeoutMs=6000}={})=>{const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),timeoutMs);try{const response=await fetcher(env)(url,{headers:{Accept:'application/json',...headers},signal:controller.signal});if(!response.ok)throw new HttpError(response.status===429?429:503,`provider_http_${response.status}`,`Provider request failed (${response.status})`,{retryable:true});if(!(response.headers.get('content-type')||'').includes('json'))throw new HttpError(503,'provider_content_type_invalid','Provider content type is invalid');const text=await response.text();if(text.length>2_000_000)throw new HttpError(503,'provider_response_too_large','Provider response is too large');return JSON.parse(text);}finally{clearTimeout(timeout);}};
const fetchText=async(env,url)=>{const response=await fetcher(env)(url,{headers:{Accept:'application/xml,text/xml'}});if(!response.ok)throw new HttpError(503,`provider_http_${response.status}`,`Provider request failed (${response.status})`,{retryable:true});const text=await response.text();if(text.length>2_000_000)throw new HttpError(503,'provider_response_too_large','Provider response is too large');return text;};
const live=async(env,provider,capability,source,params={})=>{
  const ingestionTime=new Date().toISOString();
  if(provider==='binance'){
    const symbol=String(source||'BTCUSDT').toUpperCase().replaceAll('-','');if(!SAFE_SYMBOL.test(symbol))throw new HttpError(400,'invalid_provider_symbol','Invalid Binance symbol');
    if(capability==='quote'){const d=await fetchJson(env,`https://api.binance.com/api/v3/ticker/24hr?symbol=${encodeURIComponent(symbol)}`);return {provider:'binance-spot-public',sourceIdentifier:symbol,truthState:'live_provider',observationTime:new Date(number(d.closeTime,'close time')).toISOString(),ingestionTime,freshness:'near-real-time',quality:'official-public-endpoint',confidence:.98,attribution:'Binance Spot public market data',license:'Binance API terms apply; public market data only',data:{symbol,price:number(d.lastPrice,'price'),open:number(d.openPrice,'open'),high:number(d.highPrice,'high'),low:number(d.lowPrice,'low'),volume:number(d.volume,'volume'),quoteVolume:number(d.quoteVolume,'quote volume')}};}
    const interval=String(params.interval||'1h');if(!GRANULARITY.has(interval)&&!['30m'].includes(interval))throw new HttpError(400,'invalid_provider_interval','Invalid Binance interval');const limit=Math.min(Math.max(Number(params.limit)||168,1),1000),rows=await fetchJson(env,`https://api.binance.com/api/v3/klines?symbol=${encodeURIComponent(symbol)}&interval=${interval}&limit=${limit}`),candles=rows.map(r=>({time:new Date(number(r[0],'open time')).toISOString(),open:number(r[1],'open'),high:number(r[2],'high'),low:number(r[3],'low'),close:number(r[4],'close'),volume:number(r[5],'volume')}));return {provider:'binance-spot-public',sourceIdentifier:symbol,truthState:'live_provider',observationTime:candles.at(-1)?.time||ingestionTime,ingestionTime,freshness:'near-real-time',quality:'official-public-endpoint',confidence:.98,attribution:'Binance Spot public market data',license:'Binance API terms apply; public market data only',data:{symbol,interval,candles}};
  }
  if(provider==='coinbase'){
    const product=String(source||'BTC-USD').toUpperCase();if(!SAFE_SYMBOL.test(product))throw new HttpError(400,'invalid_provider_symbol','Invalid Coinbase product');const headers={'User-Agent':'Qelly-Public-Beta/1.0'};
    if(capability==='quote'){const d=await fetchJson(env,`https://api.exchange.coinbase.com/products/${encodeURIComponent(product)}/ticker`,{headers});return {provider:'coinbase-exchange-public',sourceIdentifier:product,truthState:'live_provider',observationTime:new Date(d.time).toISOString(),ingestionTime,freshness:'near-real-time',quality:'official-public-endpoint',confidence:.98,attribution:'Coinbase Exchange public market data',license:'Coinbase Exchange Market Data Terms of Use apply',data:{product,price:number(d.price,'price'),bid:number(d.bid,'bid'),ask:number(d.ask,'ask'),volume:number(d.volume,'volume')}};}
    const interval=String(params.interval||'1h');if(!GRANULARITY.has(interval))throw new HttpError(400,'invalid_provider_interval','Invalid Coinbase interval');const granularity=GRANULARITY.get(interval),limit=Math.min(Math.max(Number(params.limit)||168,1),300),end=new Date(params.end||Date.now()),start=new Date(params.start||end.getTime()-granularity*1000*limit),query=new URLSearchParams({granularity:String(granularity),start:start.toISOString(),end:end.toISOString()}),rows=await fetchJson(env,`https://api.exchange.coinbase.com/products/${encodeURIComponent(product)}/candles?${query}`,{headers}),candles=rows.map(r=>({time:new Date(number(r[0],'time')*1000).toISOString(),low:number(r[1],'low'),high:number(r[2],'high'),open:number(r[3],'open'),close:number(r[4],'close'),volume:number(r[5],'volume')})).sort((a,b)=>a.time.localeCompare(b.time));return {provider:'coinbase-exchange-public',sourceIdentifier:product,truthState:'live_provider',observationTime:candles.at(-1)?.time||ingestionTime,ingestionTime,freshness:'near-real-time',quality:'official-public-endpoint-may-have-gaps',confidence:.96,attribution:'Coinbase Exchange public market data',license:'Coinbase Exchange Market Data Terms of Use apply',data:{product,interval,candles}};
  }
  if(provider==='ecb'){
    const xml=await fetchText(env,'https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml'),date=xml.match(/time=['"](\d{4}-\d{2}-\d{2})['"]/)?.[1];if(!date)throw new HttpError(503,'provider_schema_invalid','ECB observation date is missing');const rates={EUR:1};for(const m of xml.matchAll(/currency=['"]([A-Z]{3})['"]\s+rate=['"]([0-9.]+)['"]/g))rates[m[1]]=number(m[2],m[1]);if(Object.keys(rates).length<5)throw new HttpError(503,'provider_schema_invalid','ECB rate set is incomplete');return {provider:'ecb-reference-rates',sourceIdentifier:'EUR',truthState:'delayed_provider',observationTime:`${date}T16:00:00.000Z`,ingestionTime,freshness:'daily-working-day-reference',quality:'official-central-bank-reference',confidence:.99,attribution:'European Central Bank euro foreign exchange reference rates',license:'Published for information purposes; transaction use is discouraged by the ECB',data:{base:'EUR',date,rates}};
  }
  throw new HttpError(404,'provider_not_found','Provider is not supported');
};
const cacheRequest=(provider,capability,source,params)=>new Request(`https://qelly-provider-cache.invalid/${provider}/${capability}/${encodeURIComponent(source||'default')}?${new URLSearchParams(params)}`);
export async function providerResult(context,provider,capability,source,params={}){
  const ttl=provider==='ecb'?3600:10,stale=provider==='ecb'?172800:120,key=cacheRequest(provider,capability,source,params),cache=globalThis.caches?.default,cachedResponse=cache?await cache.match(key):null,cached=cachedResponse?await cachedResponse.json().catch(()=>null):null,now=Date.now();
  if(cached&&new Date(cached.freshUntil).getTime()>now)return {...cached.payload,truthState:'cached_provider',cache:{hit:true,stale:false,cachedAt:cached.cachedAt}};
  try{const payload=await live(context.env,provider,capability,source,params),envelope={payload,cachedAt:new Date().toISOString(),freshUntil:new Date(now+ttl*1000).toISOString(),staleUntil:new Date(now+stale*1000).toISOString()};if(cache){const put=cache.put(key,new Response(JSON.stringify(envelope),{headers:{'Content-Type':'application/json','Cache-Control':`public, max-age=${stale}`}}));context.waitUntil?.(put);}return {...payload,cache:{hit:false,stale:false}};}
  catch(error){if(cached&&new Date(cached.staleUntil).getTime()>now)return {...cached.payload,truthState:'stale_provider',freshness:'stale',quality:'degraded',confidence:Math.min(Number(cached.payload.confidence)||.7,.7),fallbackReason:'provider_request_failed_using_stale_cache',cache:{hit:true,stale:true,cachedAt:cached.cachedAt}};return {provider,sourceIdentifier:source,truthState:'unavailable',observationTime:null,ingestionTime:new Date().toISOString(),freshness:'unavailable',quality:'unavailable',confidence:0,attribution:null,license:null,fallbackReason:error?.code||'provider_request_failed',cache:{hit:false,stale:false},data:null};}
}
export const providerCatalog=()=>[{id:'binance',capabilities:['quote','candles'],termsState:'approved_public_read_only'},{id:'coinbase',capabilities:['quote','candles'],termsState:'approved_public_read_only'},{id:'ecb',capabilities:['fx-reference-rates'],termsState:'approved_public_read_only'}];
