export const ACCESS_COOKIE='qelly_sb_access';
export const REFRESH_COOKIE='qelly_sb_refresh';
export const CSRF_COOKIE='qelly_csrf';
export const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const EMAIL=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;
export const SECURITY_HEADERS=Object.freeze({
  'Content-Security-Policy':"default-src 'self'; base-uri 'none'; object-src 'none'; frame-ancestors 'none'; form-action 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; font-src 'self'; img-src 'self' data: blob:; connect-src 'self'; worker-src 'self' blob:; manifest-src 'self'; upgrade-insecure-requests",
  'Referrer-Policy':'strict-origin-when-cross-origin','Permissions-Policy':'camera=(), microphone=(), geolocation=(), payment=(), usb=(), browsing-topics=()',
  'X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Cross-Origin-Opener-Policy':'same-origin','Cross-Origin-Resource-Policy':'same-origin',
  'Strict-Transport-Security':'max-age=31536000; includeSubDomains; preload'
});
export class HttpError extends Error{constructor(status,code,message,{details=null,retryable=false}={}){super(message);this.status=status;this.code=code;this.details=details;this.retryable=retryable;}}
export const bool=(value,fallback=false)=>value==null||value===''?fallback:/^(1|true|yes|on)$/i.test(String(value));
export const cleanText=(value,max=160)=>String(value??'').trim().slice(0,max);
export const safeEmail=(value)=>{const email=String(value||'').trim().toLowerCase();if(email.length>254||!EMAIL.test(email))throw new HttpError(400,'invalid_email','Enter a valid email address');return email;};
export const strongPassword=(value)=>{const password=String(value||'');if(password.length<12||password.length>256||!/[a-z]/.test(password)||!/[A-Z]/.test(password)||!/[0-9]/.test(password)||!/[\W_]/.test(password))throw new HttpError(400,'weak_password','Password must contain 12+ characters with upper, lower, number and symbol');return password;};
export const fetcher=(env)=>typeof env.__fetch==='function'?env.__fetch:globalThis.fetch;
const safeUrl=(value,name)=>{let url;try{url=new URL(String(value||''));}catch{throw new HttpError(503,'runtime_configuration_invalid',`${name} is not configured`);}if(url.protocol!=='https:'||url.username||url.password)throw new HttpError(503,'runtime_configuration_invalid',`${name} must be a safe HTTPS URL`);return url.toString().replace(/\/$/,'');};
export function publicRuntimeConfig(env,requestUrl='https://qelly.invalid/'){
  const publicSiteUrl=safeUrl(env.QELLY_PUBLIC_SITE_URL||new URL(requestUrl).origin,'QELLY_PUBLIC_SITE_URL');
  const supabaseUrl=safeUrl(env.QELLY_PUBLIC_SUPABASE_URL,'QELLY_PUBLIC_SUPABASE_URL');
  const supabasePublishableKey=String(env.QELLY_PUBLIC_SUPABASE_PUBLISHABLE_KEY||env.QELLY_PUBLIC_SUPABASE_ANON_KEY||'');
  if(supabasePublishableKey.length<20)throw new HttpError(503,'runtime_configuration_invalid','Supabase publishable key is not configured');
  return Object.freeze({schemaVersion:1,environment:String(env.QELLY_DEPLOYMENT_ENVIRONMENT||'cloudflare-pages-production'),releaseSha:String(env.QELLY_PUBLIC_RELEASE_SHA||env.CF_PAGES_COMMIT_SHA||'unresolved'),publicSiteUrl,supabaseUrl,supabasePublishableKey,productMode:'QELLY GLOBAL PUBLIC BETA',supportUrl:`${publicSiteUrl}/support.html`,legal:Object.freeze({beta:`${publicSiteUrl}/legal/beta.html`,risk:`${publicSiteUrl}/legal/risk.html`,privacy:`${publicSiteUrl}/legal/privacy.html`,terms:`${publicSiteUrl}/legal/terms.html`}),capabilities:Object.freeze({authentication:bool(env.QELLY_ENABLE_AUTH,true),cloudSync:bool(env.QELLY_ENABLE_CLOUD_SYNC,true),liveProviders:bool(env.QELLY_ENABLE_LIVE_PROVIDERS,true),protectedWrites:bool(env.QELLY_ENABLE_FEEDBACK_WRITES,true),deterministicLocal:true}),buildTimestamp:String(env.QELLY_BUILD_TIMESTAMP||new Date().toISOString())});
}
export const correlationId=(request)=>cleanText(request.headers.get('x-correlation-id')||crypto.randomUUID(),128);
export const parseCookies=(request)=>Object.fromEntries(String(request.headers.get('cookie')||'').split(';').map(v=>v.trim()).filter(Boolean).map(part=>{const i=part.indexOf('=');return i<0?[part,'']:[part.slice(0,i),decodeURIComponent(part.slice(i+1))];}));
export const cookie=(name,value,{httpOnly=true,maxAge=3600,sameSite='Lax'}={})=>`${name}=${encodeURIComponent(value)}; Path=/; Max-Age=${Math.max(0,Math.floor(maxAge))}; Secure; SameSite=${sameSite}${httpOnly?'; HttpOnly':''}`;
export const clearCookie=(name,{httpOnly=true}={})=>cookie(name,'',{httpOnly,maxAge:0});
export const clearSessionCookies=()=>[clearCookie(ACCESS_COOKIE),clearCookie(REFRESH_COOKIE),clearCookie(CSRF_COOKIE,{httpOnly:false})];
export const tokenCookies=(session)=>{const expires=Math.max(60,Number(session.expires_in)||3600);return [cookie(ACCESS_COOKIE,session.access_token,{maxAge:expires}),cookie(REFRESH_COOKIE,session.refresh_token,{maxAge:60*60*24*30})];};
export const randomToken=()=>{const bytes=new Uint8Array(32);crypto.getRandomValues(bytes);return Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('');};
const allowedOrigins=(request,env)=>{const set=new Set([new URL(request.url).origin]);for(const value of [env.QELLY_PUBLIC_SITE_URL,...String(env.QELLY_ALLOWED_ORIGINS||'').split(',')]){try{const url=new URL(String(value||'').trim());if(url.protocol==='https:'&&!url.username&&!url.password)set.add(url.origin);}catch{}}return set;};
export const corsHeaders=(request,env)=>{const origin=request.headers.get('origin');if(!origin)return {};if(!allowedOrigins(request,env).has(origin))throw new HttpError(403,'cors_origin_forbidden','Cross-origin request origin is not allowlisted');return {'Access-Control-Allow-Origin':origin,'Access-Control-Allow-Credentials':'true','Vary':'Origin'};};
export const requireOrigin=(request,env)=>{if(['GET','HEAD','OPTIONS'].includes(request.method))return;const origin=request.headers.get('origin');if(origin&&!allowedOrigins(request,env).has(origin))throw new HttpError(403,'csrf_origin_forbidden','Cross-origin state change blocked');};
const timingSafeEqual=async(a,b)=>{const [ah,bh]=await Promise.all([crypto.subtle.digest('SHA-256',new TextEncoder().encode(String(a))),crypto.subtle.digest('SHA-256',new TextEncoder().encode(String(b)))]),av=new Uint8Array(ah),bv=new Uint8Array(bh);let diff=av.length^bv.length;for(let i=0;i<Math.min(av.length,bv.length);i++)diff|=av[i]^bv[i];return diff===0;};
export const requireCsrf=async(request)=>{const c=parseCookies(request),h=request.headers.get('x-qelly-csrf');if(!c[CSRF_COOKIE]||!h||!(await timingSafeEqual(c[CSRF_COOKIE],h)))throw new HttpError(403,'csrf_invalid','Missing or invalid CSRF proof');};
export const jsonBody=async(request,limit=1_000_000)=>{const text=await request.text();if(new TextEncoder().encode(text).byteLength>limit)throw new HttpError(413,'request_too_large','Request body is too large');if(!text)return {};try{return JSON.parse(text);}catch{throw new HttpError(400,'malformed_json','Malformed JSON body');}};
export const responseJson=(request,env,body,status=200,{cookies=[],cache='no-store'}={})=>{const headers=new Headers({...SECURITY_HEADERS,...corsHeaders(request,env),'Content-Type':'application/json; charset=utf-8','Cache-Control':cache,'X-Correlation-Id':correlationId(request)});for(const value of cookies)headers.append('Set-Cookie',value);return new Response(JSON.stringify(body),{status,headers});};
export const errorResponse=(request,env,error)=>{const e=error instanceof HttpError?error:new HttpError(500,'internal_error','The request could not be completed'),headers=new Headers({...SECURITY_HEADERS,'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Correlation-Id':correlationId(request)}),origin=request.headers.get('origin');try{if(origin&&allowedOrigins(request,env).has(origin)){headers.set('Access-Control-Allow-Origin',origin);headers.set('Access-Control-Allow-Credentials','true');headers.set('Vary','Origin');}}catch{}return new Response(JSON.stringify({error:{code:e.code,message:e.message,details:e.details,retryable:e.retryable},correlationId:correlationId(request),timestamp:new Date().toISOString()}),{status:e.status||500,headers});};
export const supabaseRequest=async(env,path,{method='GET',body,token,headers={}}={})=>{const config=publicRuntimeConfig(env),key=config.supabasePublishableKey,response=await fetcher(env)(`${config.supabaseUrl}${path}`,{method,headers:{apikey:key,Authorization:`Bearer ${token||key}`,Accept:'application/json','Content-Type':'application/json',...headers},body:body===undefined?undefined:JSON.stringify(body)}),text=await response.text();let payload=null;if(text){try{payload=JSON.parse(text);}catch{payload={message:text.slice(0,500)};}}if(!response.ok)throw new HttpError(response.status===401?401:response.status===403?403:response.status===429?429:response.status>=500?503:400,payload?.code||payload?.error_code||'supabase_request_failed',payload?.msg||payload?.message||payload?.error_description||payload?.error||`Supabase request failed (${response.status})`,{retryable:response.status===429||response.status>=500});return payload;};
export const restRequest=(env,token,path,{method='GET',body,prefer}={})=>supabaseRequest(env,`/rest/v1/${path}`,{method,body,token,headers:prefer?{Prefer:prefer}:{}});
const BufferLike=(value)=>{const normalized=String(value).replace(/-/g,'+').replace(/_/g,'/').padEnd(Math.ceil(String(value).length/4)*4,'=');return atob(normalized);};
const decodeJwt=(token)=>{const parts=String(token||'').split('.');if(parts.length!==3)throw new HttpError(401,'authentication_required','Authentication is required');try{return JSON.parse(BufferLike(parts[1]));}catch{throw new HttpError(401,'jwt_invalid','Session token is malformed');}};
export const validateJwtClaims=(token,env)=>{const claims=decodeJwt(token),config=publicRuntimeConfig(env),aud=Array.isArray(claims.aud)?claims.aud:[claims.aud];if(claims.iss!==`${config.supabaseUrl}/auth/v1`)throw new HttpError(401,'jwt_issuer_invalid','Session issuer is invalid');if(!aud.includes('authenticated'))throw new HttpError(401,'jwt_audience_invalid','Session audience is invalid');if(Number(claims.exp)<=Math.floor(Date.now()/1000)-30)throw new HttpError(401,'session_expired','Session has expired');if(!UUID.test(String(claims.sub||'')))throw new HttpError(401,'jwt_subject_invalid','Session subject is invalid');return claims;};
export const verifyAccess=async(env,accessToken)=>{const claims=validateJwtClaims(accessToken,env),user=await supabaseRequest(env,'/auth/v1/user',{token:accessToken});if(user?.id!==claims.sub)throw new HttpError(401,'jwt_subject_mismatch','Session identity could not be verified');return {user,claims};};
export const refreshSession=async(env,refreshToken)=>{if(!refreshToken)throw new HttpError(401,'session_unavailable','No refresh session is available');const session=await supabaseRequest(env,'/auth/v1/token?grant_type=refresh_token',{method:'POST',body:{refresh_token:refreshToken}});if(!session?.access_token||!session?.refresh_token)throw new HttpError(401,'refresh_failed','Session refresh failed');await verifyAccess(env,session.access_token);return session;};
export const resolveSession=async(request,env,{required=false}={})=>{const c=parseCookies(request);let accessToken=c[ACCESS_COOKIE],refreshToken=c[REFRESH_COOKIE];try{if(accessToken){const v=await verifyAccess(env,accessToken);return {...v,accessToken,refreshToken,cookies:[]};}}catch(e){if(!(e instanceof HttpError)||e.status!==401)throw e;}if(refreshToken){const rotated=await refreshSession(env,refreshToken),v=await verifyAccess(env,rotated.access_token);return {...v,accessToken:rotated.access_token,refreshToken:rotated.refresh_token,cookies:tokenCookies(rotated)};}if(required)throw new HttpError(401,'authentication_required','Authentication is required');return null;};
export const bootstrapContext=async(env,session)=>{const id=session.user.id;let profiles=await restRequest(env,session.accessToken,`qelly_profiles?select=*&user_id=eq.${id}&limit=1`);if(!profiles?.length)profiles=await restRequest(env,session.accessToken,'qelly_profiles',{method:'POST',body:{user_id:id,display_name:cleanText(session.user.user_metadata?.display_name||session.user.email?.split('@')[0]||'Qelly User',80)},prefer:'return=representation'});let workspaces=await restRequest(env,session.accessToken,`qelly_workspaces?select=*&owner_id=eq.${id}&order=created_at.asc&limit=1`);if(!workspaces?.length)workspaces=await restRequest(env,session.accessToken,'qelly_workspaces',{method:'POST',body:{owner_id:id,name:cleanText(session.user.user_metadata?.workspace_name||session.user.user_metadata?.organization_name||'My Qelly Workspace',100)},prefer:'return=representation'});const profile=profiles[0],workspace=workspaces[0];return {mode:'supabase-auth-cloudflare-facade',user:{userId:id,email:session.user.email,displayName:profile?.display_name||null,emailConfirmedAt:session.user.email_confirmed_at||null},organization:{organizationId:workspace.id,name:workspace.name},workspace:{workspaceId:workspace.id,name:workspace.name},profile,session:{authenticationMethod:'supabase-email-password',assurance:'email',expiresAt:new Date(Number(session.claims.exp)*1000).toISOString()}};};
export const enforceRateLimit=async(env,key)=>{if(env.QELLY_RATE_LIMITER?.limit){const result=await env.QELLY_RATE_LIMITER.limit({key});if(!result.success)throw new HttpError(429,'rate_limited','Request rate limit exceeded',{retryable:true});}};
export const hashKey=async(value)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(String(value)))).slice(0,16),b=>b.toString(16).padStart(2,'0')).join('');
export const stableUuid=async(value)=>{const b=new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(String(value))));b[6]=(b[6]&15)|80;b[8]=(b[8]&63)|128;const h=Array.from(b.slice(0,16),v=>v.toString(16).padStart(2,'0')).join('');return `${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20)}`;};
