const SECURITY_HEADERS=Object.freeze({'Content-Security-Policy':"default-src 'none'; frame-ancestors 'none'; base-uri 'none'; form-action 'none'",'Strict-Transport-Security':'max-age=31536000; includeSubDomains; preload','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'no-referrer','Permissions-Policy':'camera=(), microphone=(), geolocation=(), payment=(), usb=(), browsing-topics=()','Cache-Control':'no-store'});
const CATEGORIES=new Set(['bug','accessibility','data-quality','privacy','support','feature']);
const SYNC_TYPES=new Set(['create','update','rename','duplicate','delete','restore','import']);
const buckets=new Map();
function json(body,status=200,extra={}){return new Response(JSON.stringify(body),{status,headers:{...SECURITY_HEADERS,'Content-Type':'application/json; charset=utf-8',...extra}});}
function cors(request,env){const origin=request.headers.get('Origin')||'';const allowed=String(env.QELLY_ALLOWED_ORIGINS||'').split(',').map((v)=>v.trim()).filter(Boolean);return allowed.includes(origin)?{'Access-Control-Allow-Origin':origin,'Access-Control-Allow-Credentials':'false','Vary':'Origin'}:{};}
function rateLimit(key,limit=5,now=Date.now()){if(!buckets.has(key)&&buckets.size>5000)buckets.delete(buckets.keys().next().value);const current=(buckets.get(key)||[]).filter((ts)=>ts>now-60_000);if(current.length>=limit)return false;current.push(now);buckets.set(key,current);return true;}
function cloudConfigured(env){return Boolean(env.QELLY_PUBLIC_SUPABASE_URL&&env.QELLY_PUBLIC_SUPABASE_ANON_KEY);}
function safeSupabaseUrl(env,path){if(!cloudConfigured(env))throw Object.assign(new Error('external_authorization_required'),{status:503});const base=new URL(env.QELLY_PUBLIC_SUPABASE_URL);if(base.protocol!=='https:'||base.username||base.password)throw Object.assign(new Error('invalid_cloud_configuration'),{status:503});return new URL(path,`${base.toString().replace(/\/$/,'')}/`).toString();}
function bearer(request){const value=request.headers.get('Authorization')||'';if(!/^Bearer [A-Za-z0-9._~-]+$/.test(value))throw Object.assign(new Error('authentication_required'),{status:401});return value.slice(7);}
async function providerJson(response){let payload=null;try{payload=await response.json();}catch{}if(!response.ok)throw Object.assign(new Error(payload?.message||payload?.error_description||payload?.error||`cloud_request_${response.status}`),{status:response.status===401?401:response.status===403?403:503,providerStatus:response.status});return payload;}
async function verifyUser(request,env){const token=bearer(request);const response=await fetch(safeSupabaseUrl(env,'auth/v1/user'),{headers:{apikey:env.QELLY_PUBLIC_SUPABASE_ANON_KEY,Authorization:`Bearer ${token}`,Accept:'application/json'}});const user=await providerJson(response);if(!user?.id)throw Object.assign(new Error('authentication_required'),{status:401});return {token,user};}
async function rlsRequest(env,token,path,{method='GET',body,prefer}={}){const response=await fetch(safeSupabaseUrl(env,path),{method,headers:{apikey:env.QELLY_PUBLIC_SUPABASE_ANON_KEY,Authorization:`Bearer ${token}`,'Content-Type':'application/json',Accept:'application/json',...(prefer?{Prefer:prefer}:{})},body:body===undefined?undefined:JSON.stringify(body)});return providerJson(response);}
async function verifyTurnstile(token,request,env){if(!env.QELLY_TURNSTILE_SECRET_KEY)return {success:false,code:'external_authorization_required'};const body=new URLSearchParams({secret:env.QELLY_TURNSTILE_SECRET_KEY,response:token||'',remoteip:request.headers.get('CF-Connecting-IP')||''});const response=await fetch('https://challenges.cloudflare.com/turnstile/v0/siteverify',{method:'POST',body});if(!response.ok)return {success:false,code:'turnstile_upstream_error'};const payload=await response.json();if(!payload.success)return {success:false,code:'turnstile_rejected'};if(env.QELLY_PUBLIC_HOSTNAME&&payload.hostname!==env.QELLY_PUBLIC_HOSTNAME)return {success:false,code:'turnstile_hostname_mismatch'};return {success:true};}
function validateFeedback(value){if(!value||typeof value!=='object')throw new Error('invalid_body');const category=String(value.category||'');const message=String(value.message||'').trim();const pagePath=String(value.pagePath||'').slice(0,500);if(!CATEGORIES.has(category)||message.length<10||message.length>4000)throw new Error('invalid_feedback');if(/(?:BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY|seed phrase|recovery phrase|authorization:\s*bearer)/i.test(message))throw new Error('sensitive_content_rejected');return {category,message,page_path:pagePath||null};}
function validateSync(value,userId,idempotencyKey){if(!value||typeof value!=='object'||!SYNC_TYPES.has(value.type))throw new Error('invalid_sync_operation');if(value.ownerId!==userId)throw Object.assign(new Error('tenant_isolation_violation'),{status:403});if(!/^[0-9a-f-]{36}$/i.test(String(value.clientOperationId||'')))throw new Error('invalid_client_operation_id');if(String(idempotencyKey||'').length<8||String(idempotencyKey).length>128)throw new Error('idempotency_key_required');if(value.payload==null||typeof value.payload!=='object'||Array.isArray(value.payload))throw new Error('invalid_sync_payload');const serialized=JSON.stringify(value.payload);if(serialized.length>250_000)throw Object.assign(new Error('sync_payload_too_large'),{status:413});return {owner_id:userId,client_operation_id:value.clientOperationId,calculation_id:value.calculationId||null,operation_type:value.type,base_revision:value.baseRevision??null,payload:value.payload,status:'pending'};}
async function storeFeedback(record,env){if(!env.QELLY_FEEDBACK_REST_URL||!env.QELLY_SUPABASE_SERVICE_ROLE_KEY)return {stored:false,code:'external_authorization_required'};const response=await fetch(env.QELLY_FEEDBACK_REST_URL,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${env.QELLY_SUPABASE_SERVICE_ROLE_KEY}`,'apikey':env.QELLY_SUPABASE_SERVICE_ROLE_KEY,'Prefer':'return=minimal'},body:JSON.stringify(record)});return response.ok?{stored:true}:{stored:false,code:'feedback_storage_unavailable'};}
function cloudError(error,corsHeaders,correlationId){const status=Number(error?.status)||400;return json({error:error?.message||'request_failed',correlationId},status,{...corsHeaders,'X-Correlation-Id':correlationId});}
export default{async fetch(request,env){
  const url=new URL(request.url),requestCors=cors(request,env),correlationId=crypto.randomUUID();
  if(request.method==='OPTIONS'){
    if(!Object.keys(requestCors).length)return json({error:'cors_origin_forbidden'},403);
    return new Response(null,{status:204,headers:{...SECURITY_HEADERS,...requestCors,'Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'Authorization,Content-Type,Idempotency-Key,X-Qelly-Turnstile,X-Correlation-Id','Access-Control-Max-Age':'600'}});
  }
  if(request.headers.get('Origin')&&!Object.keys(requestCors).length)return json({error:'cors_origin_forbidden',correlationId},403,{'X-Correlation-Id':correlationId});
  if(request.method==='GET'&&url.pathname==='/api/health')return json({status:'ok',mode:'QELLY GLOBAL PUBLIC BETA',releaseSha:env.QELLY_RELEASE_SHA||'unresolved',deterministicLocal:true,authentication:cloudConfigured(env),cloudSync:cloudConfigured(env),protectedWrites:Boolean(env.QELLY_TURNSTILE_SECRET_KEY&&env.QELLY_FEEDBACK_REST_URL),trading:false,custody:false,privateKeys:false,seedPhrases:false},200,{'X-Correlation-Id':correlationId});
  if(request.method==='GET'&&url.pathname==='/api/v1/public-beta/status')return json({truthState:'beta',deployment:'cloudflare-worker',releaseSha:env.QELLY_RELEASE_SHA||'unresolved',services:{supabase:cloudConfigured(env)?'configured_unverified':'external_authorization_required',turnstile:env.QELLY_TURNSTILE_SECRET_KEY?'configured_unverified':'external_authorization_required'},fallback:'https://hemangsah.github.io/qelly-intelligence/'},200,{...requestCors,'X-Correlation-Id':correlationId});
  if(request.method==='POST'&&url.pathname==='/api/v1/feedback'){
    const key=request.headers.get('CF-Connecting-IP')||'unknown';if(!rateLimit(`feedback:${key}`))return json({error:'rate_limited'},429,{...requestCors,'Retry-After':'60','X-Correlation-Id':correlationId});
    let body;try{body=await request.json();}catch{return json({error:'malformed_json'},400,{...requestCors,'X-Correlation-Id':correlationId});}
    let record;try{record=validateFeedback(body);}catch(error){return json({error:error.message},400,{...requestCors,'X-Correlation-Id':correlationId});}
    const challenge=await verifyTurnstile(request.headers.get('X-Qelly-Turnstile'),request,env);if(!challenge.success)return json({error:challenge.code},challenge.code==='external_authorization_required'?503:403,{...requestCors,'X-Correlation-Id':correlationId});
    const result=await storeFeedback(record,env);return result.stored?json({accepted:true},202,{...requestCors,'X-Correlation-Id':correlationId}):json({error:result.code},503,{...requestCors,'X-Correlation-Id':correlationId});
  }
  if(request.method==='POST'&&url.pathname==='/api/v1/account/export'){
    try{const {token,user}=await verifyUser(request,env);if(!rateLimit(`export:${user.id}`,2))return json({error:'rate_limited'},429,{...requestCors,'Retry-After':'60','X-Correlation-Id':correlationId});const [profile,workspaces,calculations,revisions,pending]=await Promise.all([rlsRequest(env,token,`rest/v1/qelly_profiles?select=*&user_id=eq.${encodeURIComponent(user.id)}`),rlsRequest(env,token,'rest/v1/qelly_workspaces?select=*'),rlsRequest(env,token,'rest/v1/qelly_saved_calculations?select=*'),rlsRequest(env,token,'rest/v1/qelly_saved_calculation_revisions?select=*'),rlsRequest(env,token,'rest/v1/qelly_sync_operations?select=*&status=in.(pending,conflict)')]);return json({schemaVersion:1,exportedAt:new Date().toISOString(),ownerId:user.id,profile,workspaces,calculations,revisions,pending},200,{...requestCors,'Content-Disposition':`attachment; filename="qelly-account-export-${new Date().toISOString().slice(0,10)}.json"`,'X-Correlation-Id':correlationId});}catch(error){return cloudError(error,requestCors,correlationId);}
  }
  if(request.method==='POST'&&url.pathname==='/api/v1/account/deletion'){
    try{const {token,user}=await verifyUser(request,env);if(!rateLimit(`deletion:${user.id}`,2))return json({error:'rate_limited'},429,{...requestCors,'Retry-After':'60','X-Correlation-Id':correlationId});const rows=await rlsRequest(env,token,'rest/v1/qelly_account_deletion_requests?on_conflict=owner_id',{method:'POST',prefer:'resolution=merge-duplicates,return=representation',body:{owner_id:user.id,status:'requested',requested_at:new Date().toISOString()}});return json({accepted:true,request:rows?.[0]||null},202,{...requestCors,'X-Correlation-Id':correlationId});}catch(error){return cloudError(error,requestCors,correlationId);}
  }
  if(request.method==='POST'&&url.pathname==='/api/v1/sync/operations'){
    try{const {token,user}=await verifyUser(request,env);if(!rateLimit(`sync:${user.id}`,60))return json({error:'rate_limited'},429,{...requestCors,'Retry-After':'60','X-Correlation-Id':correlationId});let body;try{body=await request.json();}catch{throw Object.assign(new Error('malformed_json'),{status:400});}const record=validateSync(body,user.id,request.headers.get('Idempotency-Key'));const rows=await rlsRequest(env,token,'rest/v1/qelly_sync_operations?on_conflict=owner_id,client_operation_id',{method:'POST',prefer:'resolution=ignore-duplicates,return=representation',body:record});return json({accepted:true,replayed:!rows?.length,operation:rows?.[0]||null},202,{...requestCors,'X-Correlation-Id':correlationId});}catch(error){return cloudError(error,requestCors,correlationId);}
  }
  return json({error:'not_found'},404,{...requestCors,'X-Correlation-Id':correlationId});
}};
