import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const API_REVISION="qelly-revision-restore-2026-08-08-v3";
const headers={"content-type":"application/json; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff"};
const response=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers});
const fail=(status:number,code:string,message:string,details:unknown=null)=>response({status:"error",code,message,details,apiRevision:API_REVISION},status);

type Config={parentTable:string;revisionTable:string;parentKey:string;workspaceOnRevision:boolean;revisionField?:string;map:(s:any)=>Record<string,unknown>};
const CONFIG:Record<string,Config>={
 saved_calculation:{parentTable:"qelly_saved_calculations",revisionTable:"qelly_saved_calculation_revisions",parentKey:"calculation_id",workspaceOnRevision:false,map:s=>({title:s.title,formula_id:s.formulaId,input_payload:s.input??{},result_payload:s.result??{},provenance:s.provenance??{},deleted_at:s.deletedAt??null})},
 research:{parentTable:"qelly_research_projects",revisionTable:"qelly_research_project_revisions",parentKey:"project_id",workspaceOnRevision:true,map:s=>({title:s.title,status:s.status,hypothesis:s.hypothesis??null,confidence:s.confidence??null,invalidation_conditions:s.invalidationConditions??[],metadata:s.metadata??{},deleted_at:s.deletedAt??null})},
 decision:{parentTable:"qelly_decisions",revisionTable:"qelly_decision_revisions",parentKey:"decision_id",workspaceOnRevision:true,map:s=>({title:s.title,status:s.status,objective:s.objective??null,alternatives:s.alternatives??[],evidence_summary:s.evidenceSummary??{},assumptions:s.assumptions??[],probabilities:s.probabilities??{},risks:s.risks??[],scenarios:s.scenarios??[],counter_evidence:s.counterEvidence??[],rationale:s.rationale??null,review_conditions:s.reviewConditions??[],outcome:s.outcome??{},learning:s.learning??{},confidence:s.confidence??null,deleted_at:s.deletedAt??null})},
 verify:{parentTable:"qelly_verify_assessments",revisionTable:"qelly_verify_assessment_revisions",parentKey:"assessment_id",workspaceOnRevision:true,revisionField:"revision",map:s=>({title:s.title,source_name:s.source_name,source_fingerprint:s.source_fingerprint,source_normalized_bytes:s.source_normalized_bytes??null,source_revision:s.source_revision,methodology_version:s.methodology_version,engine_version:s.engine_version,report_schema:s.report_schema,truth_state:s.truth_state,report_payload:s.report_payload??{},report_hash:s.report_hash,deleted_at:s.deleted_at??null})},
 dashboard:{parentTable:"qelly_dashboard_layouts",revisionTable:"qelly_dashboard_layout_revisions",parentKey:"layout_id",workspaceOnRevision:true,map:s=>({name:s.name,route_scope:s.routeScope,persona:s.persona??null,density:s.density,layout_definition:s.layout??{},shared:Boolean(s.shared),deleted_at:s.deletedAt??null})},
 theme:{parentTable:"qelly_theme_presets",revisionTable:"qelly_theme_preset_revisions",parentKey:"preset_id",workspaceOnRevision:true,map:s=>({name:s.name,scope:s.scope,theme_family:s.themeFamily,appearance_mode:s.appearanceMode,persona:s.persona,mindset:s.mindset??null,alpha_level:s.alphaLevel??null,alpha_pack:s.alphaPack??null,accent_hex:s.accentHex??null,density:s.density,motion:s.motion,surface_depth:s.surfaceDepth,corner_style:s.cornerStyle,contrast_mode:s.contrastMode,chart_palette:s.chartPalette,table_emphasis:s.tableEmphasis,config:s.config??{},validation:s.validation??{},deleted_at:s.deletedAt??null})}
};
function cleanPatch(patch:Record<string,unknown>){const out:Record<string,unknown>={};for(const [k,v] of Object.entries(patch))if(v!==undefined)out[k]=v;return out;}
Deno.serve(async(req:Request)=>{try{
 if(req.method!=="POST")return fail(405,"method_not_allowed","Use POST");const auth=req.headers.get("authorization");if(!auth)return fail(401,"authorization_required","Authorization header is required");const url=Deno.env.get("SUPABASE_URL"),anon=Deno.env.get("SUPABASE_ANON_KEY");if(!url||!anon)return fail(503,"runtime_configuration_missing","Supabase runtime configuration is unavailable");const client=createClient(url,anon,{global:{headers:{Authorization:auth}},auth:{persistSession:false,autoRefreshToken:false}});const {data:userData,error:userError}=await client.auth.getUser();if(userError||!userData?.user)return fail(401,"invalid_identity","Authenticated Qelly identity is required");let body:any;try{body=await req.json();}catch{return fail(400,"invalid_json","Request body must be valid JSON");}
 const kind=String(body?.kind??""),config=CONFIG[kind];if(!config)return fail(400,"unsupported_revision_kind","kind must be saved_calculation, research, decision, verify, dashboard or theme");const workspaceId=body?.workspaceId,parentId=body?.id;if(typeof workspaceId!=="string"||typeof parentId!=="string")return fail(400,"scope_required","workspaceId and id are required");
 const {data:parent,error:parentError}=await client.from(config.parentTable).select("*").eq("workspace_id",workspaceId).eq("id",parentId).single();if(parentError||!parent)return fail(404,"parent_not_found","The requested record is not visible in this workspace");
 const revisionField=config.revisionField??"revision_no";let revisionQuery=client.from(config.revisionTable).select("*").eq(config.parentKey,parentId);if(config.workspaceOnRevision)revisionQuery=revisionQuery.eq("workspace_id",workspaceId);if(typeof body?.revisionId==="string")revisionQuery=revisionQuery.eq("id",body.revisionId);else if(Number.isInteger(Number(body?.revisionNo))&&Number(body.revisionNo)>0)revisionQuery=revisionQuery.eq(revisionField,Number(body.revisionNo));else return fail(400,"revision_required","revisionId or positive revisionNo is required");const {data:revision,error:revisionError}=await revisionQuery.single();if(revisionError||!revision)return fail(404,"revision_not_found","The requested revision is not visible in this workspace");
 const snapshot=revision.snapshot;if(!snapshot||typeof snapshot!=="object"||Array.isArray(snapshot))return fail(409,"revision_snapshot_invalid","Stored revision snapshot is invalid");const patch=cleanPatch(config.map(snapshot));const {data:restored,error:updateError}=await client.from(config.parentTable).update(patch).eq("id",parentId).select("*").single();if(updateError)return fail(400,"restore_failed","Revision restore was rejected safely",{code:updateError.code});
 return response({status:"success",kind,id:parentId,restoredFrom:{revisionId:revision.id,revisionNo:revision[revisionField]},item:restored,newRevision:restored?.current_revision??null,truthBoundary:"Restore creates a new current revision through Qelly's existing revision triggers; it does not erase historical revisions or bypass workspace permissions. Qelly Verify restore operates only on derived evidence reports and hashes, never raw trade rows.",apiRevision:API_REVISION});
 }catch(_error){return fail(500,"revision_restore_error","Revision restore failed safely");}});
