const PAGE_NAMES=[
  '01 Cover','02 Research','03 Brand','04 Color','05 Typography','06 Grid','07 Motion','08 Icons','09 Navigation','10 Components','11 Tables','12 Charts','13 Heatmaps','14 Provenance','15 Personas','16 Public Home','17 Market Overview','18 Asset Rankings','19 Asset Detail','20 Derivatives','21 Options','22 Order Flow','23 Exchanges','24 Research','25 Portfolio','26 Quant Workbench','27 Operations','28 Trust','29 Mobile','30 States','31 Handoff'
];
const COLORS={canvas:'#070507',surface1:'#0D0A0C',surface2:'#121014',surface3:'#171319',raised:'#1C171B',text:'#F5F1F3',secondary:'#B8AEB3',muted:'#80767B',hairline:'#312B2E',burgundy:'#5B0828',active:'#8E1D4B',positive:'#48C99A',negative:'#FF727D',warning:'#E0B460',info:'#6FB8C8',evidence:'#9B83D7'};
const MASTER_SCREENS=[
  ['16 Public Home','Public Home','desktop',1440,1000,'Editorial'],['29 Mobile','Public Home','mobile',390,844,'Editorial'],
  ['17 Market Overview','Market Overview','desktop',1440,1000,'Discovery'],['29 Mobile','Market Overview','mobile',390,844,'Discovery'],
  ['18 Asset Rankings','Asset Rankings','desktop',1440,1000,'Discovery'],['29 Mobile','Asset Rankings','mobile',390,844,'Discovery'],
  ['19 Asset Detail','BTC Asset Page','desktop',1440,1000,'Research'],['29 Mobile','BTC Asset Page','mobile',390,844,'Research'],
  ['20 Derivatives','Derivatives Overview','desktop',1440,1000,'Terminal'],['29 Mobile','Derivatives Overview','mobile',390,844,'Terminal'],
  ['20 Derivatives','Funding Monitor','desktop',1440,1000,'Terminal'],['29 Mobile','Funding Monitor','mobile',390,844,'Terminal'],
  ['20 Derivatives','Liquidation Monitor','desktop',1440,1000,'Terminal'],['29 Mobile','Liquidation Monitor','mobile',390,844,'Terminal'],
  ['13 Heatmaps','Liquidation Heatmap','desktop',1440,1000,'Terminal'],['29 Mobile','Liquidation Heatmap','mobile',390,844,'Terminal'],
  ['21 Options','Options Intelligence','desktop',1440,1000,'Terminal'],['29 Mobile','Options Intelligence','mobile',390,844,'Terminal'],
  ['24 Research','Research Workspace','desktop',1440,1000,'Research'],['29 Mobile','Research Workspace','mobile',390,844,'Research'],
  ['25 Portfolio','Portfolio Intelligence','desktop',1440,1000,'Research'],['29 Mobile','Portfolio Intelligence','mobile',390,844,'Research'],
  ['14 Provenance','Decision Provenance','desktop',1440,1000,'Research'],['29 Mobile','Decision Provenance','mobile',390,844,'Research']
];
const rgb=(hex)=>({r:parseInt(hex.slice(1,3),16)/255,g:parseInt(hex.slice(3,5),16)/255,b:parseInt(hex.slice(5,7),16)/255});
const solid=(hex,opacity=1)=>[{type:'SOLID',color:rgb(hex),opacity}];
async function loadFonts(){await Promise.all(['Regular','Medium','Bold'].map((style)=>figma.loadFontAsync({family:'Inter',style})));}
function text(value,size=14,style='Regular',color=COLORS.text){const node=figma.createText();node.fontName={family:'Inter',style};node.fontSize=size;node.characters=value;node.fills=solid(color);node.textAutoResize='HEIGHT';return node;}
function frame(name,{layout='VERTICAL',gap=12,padding=16,fill=COLORS.surface1,radius=12}={}){const node=figma.createFrame();node.name=name;node.layoutMode=layout;node.primaryAxisSizingMode='AUTO';node.counterAxisSizingMode='AUTO';node.itemSpacing=gap;node.paddingTop=padding;node.paddingRight=padding;node.paddingBottom=padding;node.paddingLeft=padding;node.fills=solid(fill);node.cornerRadius=radius;return node;}
function divider(){const node=figma.createRectangle();node.name='Hairline divider';node.resize(100,1);node.layoutAlign='STRETCH';node.fills=solid(COLORS.hairline);return node;}
function tokenChip(label,value,color){const node=frame(`Token / ${label}`,{layout:'HORIZONTAL',gap:8,padding:8,fill:COLORS.surface2,radius:6});const swatch=figma.createRectangle();swatch.resize(20,20);swatch.cornerRadius=5;swatch.fills=solid(color);node.appendChild(swatch);const copy=frame('Token copy',{gap:2,padding:0,fill:COLORS.surface2,radius:0});copy.appendChild(text(label,11,'Medium'));copy.appendChild(text(value,9,'Regular',COLORS.muted));node.appendChild(copy);return node;}
function buttonComponent(name,label,variant='secondary'){const node=figma.createComponent();node.name=`Button / ${name}`;node.layoutMode='HORIZONTAL';node.primaryAxisSizingMode='AUTO';node.counterAxisSizingMode='AUTO';node.paddingTop=9;node.paddingBottom=9;node.paddingLeft=13;node.paddingRight=13;node.itemSpacing=7;node.cornerRadius=8;node.fills=solid(variant==='primary'?COLORS.burgundy:COLORS.surface2);node.strokes=solid(variant==='primary'?COLORS.active:COLORS.hairline);node.appendChild(text(label,12,'Medium'));return node;}
function statusComponent(){const node=figma.createComponent();node.name='Status center / Static preview';node.layoutMode='HORIZONTAL';node.primaryAxisSizingMode='AUTO';node.counterAxisSizingMode='AUTO';node.paddingTop=7;node.paddingBottom=7;node.paddingLeft=10;node.paddingRight=10;node.itemSpacing=8;node.cornerRadius=6;node.fills=solid(COLORS.surface1);node.strokes=solid(COLORS.hairline);const dot=figma.createEllipse();dot.resize(7,7);dot.fills=solid(COLORS.warning);node.appendChild(dot);node.appendChild(text('Static visual preview · backend unavailable',11,'Medium',COLORS.secondary));return node;}
function tableComponent(){const component=figma.createComponent();component.name='Data table / Institutional rankings';component.layoutMode='VERTICAL';component.primaryAxisSizingMode='AUTO';component.counterAxisSizingMode='FIXED';component.resize(1120,480);component.fills=solid(COLORS.surface1);component.strokes=solid(COLORS.hairline);component.cornerRadius=12;const toolbar=frame('Toolbar',{layout:'HORIZONTAL',gap:10,padding:12,fill:COLORS.surface1,radius:0});toolbar.layoutAlign='STRETCH';toolbar.appendChild(text('Asset rankings',15,'Medium'));toolbar.appendChild(text('Search  Filters  Columns  Density  Export',10,'Regular',COLORS.muted));component.appendChild(toolbar);component.appendChild(divider());const columns=['#','Asset','Price','1h','24h','7d','Sparkline','Volume','Market Cap','Funding','OI','Confidence','Source','Freshness','Explain'];for(let row=0;row<8;row++){const line=frame(row===0?'Table header':`Row ${row}`,{layout:'HORIZONTAL',gap:14,padding:10,fill:row===0?COLORS.surface2:COLORS.surface1,radius:0});line.layoutAlign='STRETCH';columns.forEach((column)=>line.appendChild(text(row===0?column:column==='Asset'?['Bitcoin','Ethereum','Solana','XRP','BNB','Dogecoin','Chainlink'][row-1]??'Asset':column==='#'?String(row):column==='Price'?'$65,291.65':'—',row===0?9:10,row===0?'Medium':'Regular',row===0?COLORS.muted:COLORS.secondary)));component.appendChild(line);}return component;}
function chartComponent(){const component=figma.createComponent();component.name='Chart / OHLC market workspace';component.layoutMode='VERTICAL';component.primaryAxisSizingMode='FIXED';component.counterAxisSizingMode='FIXED';component.resize(760,340);component.paddingTop=12;component.paddingRight=12;component.paddingBottom=12;component.paddingLeft=12;component.itemSpacing=10;component.cornerRadius=12;component.fills=solid(COLORS.surface1);component.strokes=solid(COLORS.hairline);const head=frame('Chart toolbar',{layout:'HORIZONTAL',gap:10,padding:0,fill:COLORS.surface1,radius:0});head.layoutAlign='STRETCH';head.appendChild(text('Market composite  $65,291.65',13,'Medium'));head.appendChild(text('Candles  Line  1H  4H  1D  1W  Linear',9,'Regular',COLORS.muted));component.appendChild(head);const plot=figma.createFrame();plot.name='Deterministic OHLC plot';plot.resize(736,260);plot.fills=solid(COLORS.surface2);plot.strokes=solid(COLORS.hairline);plot.cornerRadius=6;for(let index=0;index<48;index++){const candle=figma.createRectangle();const up=Math.sin(index*.61)>=-.1;candle.name=`Candle ${index+1}`;candle.resize(6,Math.max(7,Math.abs(Math.sin(index*.47))*42));candle.x=16+index*14;candle.y=80+Math.sin(index*.23)*46+(up?0:10);candle.fills=solid(up?COLORS.positive:COLORS.negative,.78);plot.appendChild(candle);}component.appendChild(plot);return component;}
function marketPulse(){const node=frame('Market pulse / Mixed composition',{layout:'HORIZONTAL',gap:1,padding:0,fill:COLORS.hairline,radius:12});['Global market cap','24h spot volume','Open interest','Liquidations','Funding','Volatility'].forEach((label,index)=>{const metric=frame(label,{gap:5,padding:13,fill:COLORS.surface1,radius:0});metric.appendChild(text(label,9,'Regular',COLORS.muted));metric.appendChild(text(index<2?'$2.41T':index===2?'$114.6B':index===3?'$180.2M':index===4?'+0.0067%':'52.8',index<2?22:15,'Medium'));node.appendChild(metric);});return node;}
function navigationComponent(){const node=figma.createComponent();node.name='Navigation / Slim edge dock';node.layoutMode='VERTICAL';node.primaryAxisSizingMode='FIXED';node.counterAxisSizingMode='FIXED';node.resize(58,680);node.paddingTop=8;node.paddingRight=6;node.paddingBottom=8;node.paddingLeft=6;node.itemSpacing=5;node.fills=solid(COLORS.canvas);node.strokes=solid(COLORS.hairline);const brand=frame('Q mark',{padding:9,fill:COLORS.burgundy,radius:9});brand.appendChild(text('Q',13,'Bold'));node.appendChild(brand);['Home','Markets','Discovery','Derivatives','Research','Portfolio','Evidence','Operations','Trust'].forEach((label)=>{const item=frame(label,{gap:2,padding:6,fill:label==='Discovery'?COLORS.surface3:COLORS.canvas,radius:8});item.appendChild(text(label.slice(0,1),12,'Medium',label==='Discovery'?COLORS.text:COLORS.muted));item.appendChild(text(label,7,'Regular',label==='Discovery'?COLORS.text:COLORS.muted));node.appendChild(item);});return node;}
function screenFrame(name,viewport,mode,width,height,components){const root=figma.createFrame();root.name=`${name} / ${viewport} / ${mode}`;root.resize(width,height);root.clipsContent=true;root.fills=solid(COLORS.canvas);root.setPluginData('qellyMasterFrame','true');const compact=width<600;const shell=frame('Application shell',{layout:'VERTICAL',gap:0,padding:0,fill:COLORS.canvas,radius:0});shell.resize(width,height);shell.counterAxisSizingMode='FIXED';const ticker=frame('Market ticker',{layout:'HORIZONTAL',gap:18,padding:8,fill:'#090709',radius:0});ticker.layoutAlign='STRETCH';ticker.appendChild(text('QELLY INTELLIGENCE',9,'Medium'));ticker.appendChild(text('BTC $65,291 +1.30%   ETH $1,955 +3.70%   OI $114.6B',9,'Regular',COLORS.muted));shell.appendChild(ticker);const command=frame('Command bar',{layout:'HORIZONTAL',gap:12,padding:10,fill:COLORS.surface1,radius:0});command.layoutAlign='STRETCH';command.appendChild(text(name,compact?11:12,'Medium'));const search=frame('Global command search',{layout:'HORIZONTAL',gap:8,padding:9,fill:COLORS.surface2,radius:8});search.layoutGrow=1;search.appendChild(text('Search assets, markets, research and commands',10,'Regular',COLORS.muted));command.appendChild(search);shell.appendChild(command);const body=frame('Workspace',{layout:'HORIZONTAL',gap:0,padding:0,fill:COLORS.canvas,radius:0});body.layoutGrow=1;body.counterAxisSizingMode='FIXED';body.resize(width,height-82);if(!compact)body.appendChild(navigationComponent().createInstance());const content=frame('Route content',{gap:12,padding:compact?10:18,fill:COLORS.canvas,radius:0});content.layoutGrow=1;content.counterAxisSizingMode='FIXED';content.resize(compact?width:width-58,height-82);content.appendChild(statusComponent().createInstance());content.appendChild(text(name,compact?26:34,'Medium'));content.appendChild(text(`${mode} layout · evidence-backed Qelly master frame`,compact?11:13,'Regular',COLORS.secondary));components.forEach((component)=>content.appendChild(component.createInstance?component.createInstance():component));body.appendChild(content);shell.appendChild(body);root.appendChild(shell);return root;}
function createVariablesAndStyles(){const collection=figma.variables.createVariableCollection('Qelly Premium Semantic');const dark=collection.modes[0].modeId;collection.renameMode(dark,'Dark');const light=collection.addMode('Light');Object.entries(COLORS).forEach(([name,value])=>{const variable=figma.variables.createVariable(`color/${name}`,collection.id,'COLOR');variable.setValueForMode(dark,{...rgb(value),a:1});const lightValue={canvas:'#F5F1F3',surface1:'#FFFFFF',surface2:'#F0EBEE',surface3:'#E8E1E5',raised:'#FFFFFF',text:'#171015',secondary:'#554B50',muted:'#7E7278'}[name]??value;variable.setValueForMode(light,{...rgb(lightValue),a:1});});const display=figma.createTextStyle();display.name='Qelly / Type / Display 1';display.fontName={family:'Inter',style:'Medium'};display.fontSize=48;display.lineHeight={unit:'PERCENT',value:105};display.letterSpacing={unit:'PERCENT',value:-3};const body=figma.createTextStyle();body.name='Qelly / Type / Body';body.fontName={family:'Inter',style:'Regular'};body.fontSize=14;body.lineHeight={unit:'PERCENT',value:150};const surface=figma.createPaintStyle();surface.name='Qelly / Surface / Neutral 1';surface.paints=solid(COLORS.surface1);}
function addFoundation(page,title,description){const board=frame(`${title} foundation`,{gap:16,padding:28,fill:COLORS.canvas,radius:0});board.resize(1440,900);board.counterAxisSizingMode='FIXED';board.appendChild(text(title,40,'Medium'));board.appendChild(text(description,16,'Regular',COLORS.secondary));board.appendChild(divider());page.appendChild(board);return board;}
async function run(){await loadFonts();for(const page of [...figma.root.children])if(page.type==='PAGE'&&page.getPluginData('qellyPremiumGenerated')==='true')page.remove();createVariablesAndStyles();const pages=new Map();for(const name of PAGE_NAMES){const page=figma.createPage();page.name=`QELLY · ${name}`;page.setPluginData('qellyPremiumGenerated','true');pages.set(name,page);addFoundation(page,name,'Editable premium Qelly foundation with neutral institutional materials, original components, responsive constraints, accessibility notes, and provenance requirements.');}
const componentsPage=pages.get('10 Components');const primary=buttonComponent('Primary','Primary action','primary');const secondary=buttonComponent('Secondary','Secondary action');const status=statusComponent();const nav=navigationComponent();const table=tableComponent();const chart=chartComponent();[primary,secondary,status,nav,table,chart].forEach((node)=>componentsPage.appendChild(node));
const colorPage=pages.get('04 Color');const colorBoard=frame('Semantic color tokens',{layout:'HORIZONTAL',gap:8,padding:20,fill:COLORS.canvas,radius:0});Object.entries(COLORS).forEach(([name,value])=>colorBoard.appendChild(tokenChip(name,value,value)));colorPage.appendChild(colorBoard);
const tablePage=pages.get('11 Tables');tablePage.appendChild(table.createInstance());const chartPage=pages.get('12 Charts');chartPage.appendChild(chart.createInstance());const navigationPage=pages.get('09 Navigation');navigationPage.appendChild(nav.createInstance());
const modes={Discovery:[marketPulse(),table],Terminal:[marketPulse(),table,chart],Research:[marketPulse(),table,chart]};const indexes=new Map();for(const [pageName,name,viewport,width,height,mode] of MASTER_SCREENS){const page=pages.get(pageName);const components=modes[mode]??[marketPulse(),table,chart];const master=screenFrame(name,viewport,mode,width,height,components);const index=indexes.get(pageName)??0;master.x=(index%3)*(width+120);master.y=1080+Math.floor(index/3)*(height+120);page.appendChild(master);indexes.set(pageName,index+1);}
figma.currentPage=pages.get('01 Cover');figma.viewport.scrollAndZoomIntoView(figma.currentPage.children.slice(0,1));figma.notify(`Qelly premium design system generated: ${PAGE_NAMES.length} pages and ${MASTER_SCREENS.length} high-fidelity master frames.`);figma.closePlugin('Premium Qelly Figma system generated. Open and review master frames before any quality claim.');}
run().catch((error)=>{figma.notify(`Qelly premium generator failed: ${error.message}`,{error:true});figma.closePlugin(error.message);});
